import { expect, test } from "@playwright/test";

test("seeded research workflow has no severe console errors", async ({ page }) => {
  const severe: string[] = [];
  page.on("console", message => { if (message.type() === "error") severe.push(message.text()); });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Market overview" })).toBeVisible();
  await page.getByRole("link", { name: "Providers" }).click();
  await expect(page.getByRole("heading", { name: "Providers" })).toBeVisible();
  await expect(page.getByText("Deterministic Synthetic Demonstration Provider")).toBeVisible();
  await page.getByRole("link", { name: "Import Jobs" }).click();
  await expect(page.getByRole("heading", { name: "Import jobs" })).toBeVisible();
  await page.getByRole("button", { name: "Create import" }).click();
  await expect(page.getByText(/inserted ·/).first()).toBeVisible();
  await page.getByRole("link", { name: "Data Quality" }).click();
  await expect(page.getByRole("heading", { name: "Data quality" })).toBeVisible();
  await page.getByRole("link", { name: "Asset Explorer" }).click();
  await expect(page.getByRole("link", { name: "AAPL" })).toBeVisible();
  await page.getByRole("link", { name: "Watchlists" }).click();
  const watchlistName = `E2E Research ${Date.now()}`;
  await page.getByLabel("New watchlist name").fill(watchlistName);
  await page.getByRole("button", { name: "Create watchlist" }).click();
  const watchlist = page.locator("article.watchlist").filter({ has: page.getByRole("heading", { name: watchlistName }) });
  await watchlist.getByLabel(`Add asset to ${watchlistName}`).fill("AAPL");
  await watchlist.getByRole("button", { name: "Add" }).click();
  await watchlist.getByRole("link", { name: /AAPL/ }).click();
  await expect(page.getByRole("heading", { name: "AAPL" })).toBeVisible();
  await page.getByRole("link", { name: "Strategy Lab" }).click();
  await expect(page.getByRole("heading", { name: "Strategy Lab" })).toBeVisible();
  await page.getByRole("button", { name: "Run backtest" }).click();
  await expect(page.getByText("Execution assumptions")).toBeVisible();
  await page.getByRole("link", { name: "Paper Portfolios" }).click();
  const portfolioName = `E2E Paper ${Date.now()}`;
  await page.getByLabel("Portfolio name").fill(portfolioName);
  await page.getByRole("button", { name: "Create portfolio" }).click();
  await page.getByRole("link", { name: new RegExp(portfolioName) }).click();
  await page.getByRole("link", { name: "Simulate order" }).click();
  await page.getByRole("button", { name: "Preview risk checks" }).click();
  await expect(page.getByText("All enabled portfolio risk checks passed.")).toBeVisible();
  await page.getByRole("button", { name: "Submit simulated order" }).click();
  await expect(page.getByText("Simulation recorded")).toBeVisible();
  expect(severe).toEqual([]);
});
