"""add backtesting and simulated paper trading

Revision ID: 0002_backtesting_paper_trading
Revises: 0001_foundation
Create Date: 2026-07-28 01:29:14.757038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import packages.database.types


revision: str = '0002_backtesting_paper_trading'
down_revision: Union[str, None] = '0001_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('starting_cash', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_portfolios')),
    sa.UniqueConstraint('name', name=op.f('uq_paper_portfolios_name'))
    )
    op.create_index(op.f('ix_paper_portfolios_status'), 'paper_portfolios', ['status'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('strategy_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('name', name=op.f('uq_strategies_name'))
    )
    op.create_index(op.f('ix_strategies_strategy_type'), 'strategies', ['strategy_type'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_paper_positions_paper_position_quantity_nonnegative')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_paper_positions_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], name=op.f('fk_paper_positions_portfolio_id_paper_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_positions')),
    sa.UniqueConstraint('portfolio_id', 'asset_id', name='uq_paper_position_asset')
    )
    op.create_index(op.f('ix_paper_positions_asset_id'), 'paper_positions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_portfolio_id'), 'paper_positions', ['portfolio_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('event_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('exposure', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], name=op.f('fk_portfolio_snapshots_portfolio_id_paper_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index(op.f('ix_portfolio_snapshots_event_time'), 'portfolio_snapshots', ['event_time'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_table('risk_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('limit_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], name=op.f('fk_risk_rules_portfolio_id_paper_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_rules')),
    sa.UniqueConstraint('portfolio_id', 'rule_type', name='uq_risk_rule_portfolio_type')
    )
    op.create_index(op.f('ix_risk_rules_portfolio_id'), 'risk_rules', ['portfolio_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=False),
    sa.Column('calculation_notes', sa.Text(), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_versions_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_strategy_version_number')
    )
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('asset_symbols', sa.JSON(), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=16), nullable=False),
    sa.Column('start_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('final_equity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('strategy_configuration', sa.JSON(), nullable=False),
    sa.Column('risk_configuration', sa.JSON(), nullable=False),
    sa.Column('execution_assumptions', sa.JSON(), nullable=False),
    sa.Column('source_data_identifiers', sa.JSON(), nullable=False),
    sa.Column('data_source_identifiers', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('application_version', sa.String(length=20), nullable=False),
    sa.Column('is_hypothetical', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_backtest_runs_strategy_version_id_strategy_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_runs'))
    )
    op.create_index(op.f('ix_backtest_runs_status'), 'backtest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_version_id'), 'backtest_runs', ['strategy_version_id'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('client_order_id', sa.String(length=80), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('estimated_fees', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('source_price_bar_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_paper_orders_paper_order_quantity_positive')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_paper_orders_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], name=op.f('fk_paper_orders_portfolio_id_paper_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_price_bar_id'], ['price_bars.id'], name=op.f('fk_paper_orders_source_price_bar_id_price_bars'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_orders')),
    sa.UniqueConstraint('portfolio_id', 'client_order_id', name='uq_paper_order_client_id')
    )
    op.create_index(op.f('ix_paper_orders_asset_id'), 'paper_orders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_order_type'), 'paper_orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_paper_orders_portfolio_id'), 'paper_orders', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_status'), 'paper_orders', ['status'], unique=False)
    op.create_table('backtest_daily_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backtest_run_id', sa.Uuid(), nullable=False),
    sa.Column('event_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.Column('cumulative_fees', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('exposure', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('benchmark_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], name=op.f('fk_backtest_daily_snapshots_backtest_run_id_backtest_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_daily_snapshots')),
    sa.UniqueConstraint('backtest_run_id', 'event_time', name='uq_backtest_snapshot_time')
    )
    op.create_index(op.f('ix_backtest_daily_snapshots_backtest_run_id'), 'backtest_daily_snapshots', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_daily_snapshots_event_time'), 'backtest_daily_snapshots', ['event_time'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backtest_run_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('source_price_bar_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('signal_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('execution_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cash_after', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_backtest_trades_backtest_trade_quantity_positive')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_backtest_trades_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], name=op.f('fk_backtest_trades_backtest_run_id_backtest_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_price_bar_id'], ['price_bars.id'], name=op.f('fk_backtest_trades_source_price_bar_id_price_bars'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_trades'))
    )
    op.create_index(op.f('ix_backtest_trades_asset_id'), 'backtest_trades', ['asset_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_backtest_run_id'), 'backtest_trades', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_execution_time'), 'backtest_trades', ['execution_time'], unique=False)
    op.create_index(op.f('ix_backtest_trades_symbol'), 'backtest_trades', ['symbol'], unique=False)
    op.create_table('paper_fills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('source_price_bar_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('filled_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_paper_fills_paper_fill_quantity_positive')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_paper_fills_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], name=op.f('fk_paper_fills_order_id_paper_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], name=op.f('fk_paper_fills_portfolio_id_paper_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_price_bar_id'], ['price_bars.id'], name=op.f('fk_paper_fills_source_price_bar_id_price_bars'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_fills'))
    )
    op.create_index(op.f('ix_paper_fills_asset_id'), 'paper_fills', ['asset_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_filled_at'), 'paper_fills', ['filled_at'], unique=False)
    op.create_index(op.f('ix_paper_fills_order_id'), 'paper_fills', ['order_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_portfolio_id'), 'paper_fills', ['portfolio_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backtest_run_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('source_price_bar_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('eligible_after', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('strength', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_signals_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], name=op.f('fk_signals_backtest_run_id_backtest_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_price_bar_id'], ['price_bars.id'], name=op.f('fk_signals_source_price_bar_id_price_bars'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_signals_strategy_version_id_strategy_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_asset_id'), 'signals', ['asset_id'], unique=False)
    op.create_index(op.f('ix_signals_backtest_run_id'), 'signals', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_signals_generated_at'), 'signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_signals_strategy_version_id'), 'signals', ['strategy_version_id'], unique=False)
    op.create_table('signal_factors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_signal_factors_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_factors'))
    )
    op.create_index(op.f('ix_signal_factors_signal_id'), 'signal_factors', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_factors_signal_id'), table_name='signal_factors')
    op.drop_table('signal_factors')
    op.drop_index(op.f('ix_signals_strategy_version_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_generated_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_backtest_run_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_asset_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_paper_fills_portfolio_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_order_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_filled_at'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_asset_id'), table_name='paper_fills')
    op.drop_table('paper_fills')
    op.drop_index(op.f('ix_backtest_trades_symbol'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_execution_time'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_backtest_run_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_asset_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_backtest_daily_snapshots_event_time'), table_name='backtest_daily_snapshots')
    op.drop_index(op.f('ix_backtest_daily_snapshots_backtest_run_id'), table_name='backtest_daily_snapshots')
    op.drop_table('backtest_daily_snapshots')
    op.drop_index(op.f('ix_paper_orders_status'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_portfolio_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_order_type'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_asset_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_backtest_runs_strategy_version_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_status'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_risk_rules_portfolio_id'), table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_event_time'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_paper_positions_portfolio_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_asset_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_strategies_strategy_type'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_paper_portfolios_status'), table_name='paper_portfolios')
    op.drop_table('paper_portfolios')
    # ### end Alembic commands ###
