"""market data platform

Revision ID: 10fdd3577a14
Revises: 0002_backtesting_paper_trading
Create Date: 2026-07-28 15:25:29.522149
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import packages.database.types


revision: str = '10fdd3577a14'
down_revision: Union[str, None] = '0002_backtesting_paper_trading'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_calendars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('weekend_days', sa.JSON(), nullable=False),
    sa.Column('holiday_dates', sa.JSON(), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_calendars'))
    )
    op.create_index(op.f('ix_exchange_calendars_code'), 'exchange_calendars', ['code'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('adapter_type', sa.String(length=80), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('credential_environment_keys', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('health', sa.String(length=32), nullable=False),
    sa.Column('last_tested_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_successful_import_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_providers_name'))
    )
    op.create_index(op.f('ix_providers_code'), 'providers', ['code'], unique=True)
    op.create_index(op.f('ix_providers_is_enabled'), 'providers', ['is_enabled'], unique=False)
    op.create_table('asset_metadata_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('original_symbol', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('effective_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('retrieval_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_metadata_versions_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_asset_metadata_versions_provider_id_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_metadata_versions')),
    sa.UniqueConstraint('asset_id', 'provider_id', 'version', name='uq_asset_metadata_version')
    )
    op.create_index(op.f('ix_asset_metadata_versions_asset_id'), 'asset_metadata_versions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_metadata_versions_effective_time'), 'asset_metadata_versions', ['effective_time'], unique=False)
    op.create_index(op.f('ix_asset_metadata_versions_provider_id'), 'asset_metadata_versions', ['provider_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('original_symbol', sa.String(length=32), nullable=False),
    sa.Column('effective_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('publication_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('retrieval_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('old_symbol', sa.String(length=32), nullable=True),
    sa.Column('new_symbol', sa.String(length=32), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_corporate_actions_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_corporate_actions_provider_id_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_actions')),
    sa.UniqueConstraint('provider_id', 'checksum', name='uq_corporate_action_provider_checksum')
    )
    op.create_index(op.f('ix_corporate_actions_action_type'), 'corporate_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_corporate_actions_asset_id'), 'corporate_actions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_effective_time'), 'corporate_actions', ['effective_time'], unique=False)
    op.create_index(op.f('ix_corporate_actions_provider_id'), 'corporate_actions', ['provider_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('request_configuration', sa.JSON(), nullable=False),
    sa.Column('resume_cursor', sa.JSON(), nullable=False),
    sa.Column('requested_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=False),
    sa.CheckConstraint('max_attempts > 0', name=op.f('ck_import_jobs_import_job_max_attempts_positive')),
    sa.CheckConstraint('records_inserted >= 0', name=op.f('ck_import_jobs_import_job_inserted_nonnegative')),
    sa.CheckConstraint('records_processed >= 0', name=op.f('ck_import_jobs_import_job_processed_nonnegative')),
    sa.CheckConstraint('records_skipped >= 0', name=op.f('ck_import_jobs_import_job_skipped_nonnegative')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_import_jobs_provider_id_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_index(op.f('ix_import_jobs_mode'), 'import_jobs', ['mode'], unique=False)
    op.create_index(op.f('ix_import_jobs_next_retry_at'), 'import_jobs', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_import_jobs_provider_id'), 'import_jobs', ['provider_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_requested_at'), 'import_jobs', ['requested_at'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('key_name', sa.String(length=80), nullable=False),
    sa.Column('secret_reference', sa.String(length=160), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_credentials_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials')),
    sa.UniqueConstraint('provider_id', 'key_name', name='uq_provider_credential_key')
    )
    op.create_index(op.f('ix_provider_credentials_provider_id'), 'provider_credentials', ['provider_id'], unique=False)
    op.create_table('trading_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('calendar_id', sa.Uuid(), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('open_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('close_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_early_close', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.CheckConstraint('close_time > open_time', name=op.f('ck_trading_sessions_trading_session_close_after_open')),
    sa.ForeignKeyConstraint(['calendar_id'], ['exchange_calendars.id'], name=op.f('fk_trading_sessions_calendar_id_exchange_calendars'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_sessions')),
    sa.UniqueConstraint('calendar_id', 'session_date', name='uq_calendar_session_date')
    )
    op.create_index(op.f('ix_trading_sessions_calendar_id'), 'trading_sessions', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_trading_sessions_session_date'), 'trading_sessions', ['session_date'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_timestamp', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('retrieval_timestamp', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('publication_timestamp', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('effective_timestamp', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=False),
    sa.Column('started_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], name=op.f('fk_import_batches_job_id_import_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('job_id', 'sequence', name='uq_import_batch_job_sequence')
    )
    op.create_index(op.f('ix_import_batches_job_id'), 'import_batches', ['job_id'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('record_identifier', sa.String(length=160), nullable=True),
    sa.Column('payload_summary', sa.JSON(), nullable=False),
    sa.Column('is_retryable', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_errors_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], name=op.f('fk_import_errors_job_id_import_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    op.create_index(op.f('ix_import_errors_batch_id'), 'import_errors', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_errors_error_code'), 'import_errors', ['error_code'], unique=False)
    op.create_index(op.f('ix_import_errors_job_id'), 'import_errors', ['job_id'], unique=False)
    op.create_index(op.f('ix_import_errors_occurred_at'), 'import_errors', ['occurred_at'], unique=False)
    with op.batch_alter_table('price_bars') as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('original_symbol', sa.String(length=32), server_default='', nullable=False))
        batch_op.add_column(sa.Column('adjustment_status', sa.String(length=24), server_default='unadjusted', nullable=False))
        batch_op.add_column(sa.Column('checksum', sa.String(length=64), server_default='', nullable=False))
        batch_op.add_column(sa.Column('record_version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(op.f('ix_price_bars_provider_id'), ['provider_id'], unique=False)
        batch_op.create_foreign_key(
            op.f('fk_price_bars_provider_id_providers'),
            'providers',
            ['provider_id'],
            ['id'],
            ondelete='RESTRICT',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_bars') as batch_op:
        batch_op.drop_constraint(
            op.f('fk_price_bars_provider_id_providers'), type_='foreignkey'
        )
        batch_op.drop_index(op.f('ix_price_bars_provider_id'))
        batch_op.drop_column('record_version')
        batch_op.drop_column('checksum')
        batch_op.drop_column('adjustment_status')
        batch_op.drop_column('original_symbol')
        batch_op.drop_column('provider_id')
    op.drop_index(op.f('ix_import_errors_occurred_at'), table_name='import_errors')
    op.drop_index(op.f('ix_import_errors_job_id'), table_name='import_errors')
    op.drop_index(op.f('ix_import_errors_error_code'), table_name='import_errors')
    op.drop_index(op.f('ix_import_errors_batch_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_job_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_trading_sessions_session_date'), table_name='trading_sessions')
    op.drop_index(op.f('ix_trading_sessions_calendar_id'), table_name='trading_sessions')
    op.drop_table('trading_sessions')
    op.drop_index(op.f('ix_provider_credentials_provider_id'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_requested_at'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_provider_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_next_retry_at'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_mode'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_corporate_actions_provider_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_effective_time'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_asset_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_action_type'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_asset_metadata_versions_provider_id'), table_name='asset_metadata_versions')
    op.drop_index(op.f('ix_asset_metadata_versions_effective_time'), table_name='asset_metadata_versions')
    op.drop_index(op.f('ix_asset_metadata_versions_asset_id'), table_name='asset_metadata_versions')
    op.drop_table('asset_metadata_versions')
    op.drop_index(op.f('ix_providers_is_enabled'), table_name='providers')
    op.drop_index(op.f('ix_providers_code'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_exchange_calendars_code'), table_name='exchange_calendars')
    op.drop_table('exchange_calendars')
    # ### end Alembic commands ###
