"""real market data operations

Revision ID: 1a52c2d25013
Revises: 10fdd3577a14
Create Date: 2026-07-29 01:20:58.687102
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import packages.database.types


revision: str = "1a52c2d25013"
down_revision: Union[str, None] = "10fdd3577a14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_runs",
        sa.Column(
            "data_classification", sa.String(length=32), server_default="synthetic", nullable=False
        ),
    )
    op.add_column(
        "backtest_runs",
        sa.Column("provider_identifiers", sa.JSON(), server_default="[]", nullable=False),
    )
    op.add_column(
        "backtest_runs",
        sa.Column("import_job_identifiers", sa.JSON(), server_default="[]", nullable=False),
    )
    op.add_column(
        "backtest_runs",
        sa.Column("adjustment_statuses", sa.JSON(), server_default="[]", nullable=False),
    )
    op.add_column(
        "backtest_runs",
        sa.Column("calendar_code", sa.String(length=32), server_default="XNYS", nullable=False),
    )
    op.create_table(
        "import_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("scope_type", sa.String(length=24), nullable=False),
        sa.Column("symbols", sa.JSON(), nullable=False),
        sa.Column("date_range_policy", sa.JSON(), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("adjustment_preference", sa.String(length=24), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "next_run_at", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("last_run_at", packages.database.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_import_schedules_provider_id_providers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_schedules")),
        sa.UniqueConstraint("provider_id", "name", name="uq_import_schedule_provider_name"),
    )
    op.create_index(
        op.f("ix_import_schedules_is_enabled"), "import_schedules", ["is_enabled"], unique=False
    )
    op.create_index(
        op.f("ix_import_schedules_next_run_at"), "import_schedules", ["next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_import_schedules_provider_id"), "import_schedules", ["provider_id"], unique=False
    )
    op.create_table(
        "provider_health_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("configured", sa.Boolean(), nullable=False),
        sa.Column("connectivity_status", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("quota", sa.JSON(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("checked_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_provider_health_snapshots_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_health_snapshots")),
    )
    op.create_index(
        op.f("ix_provider_health_snapshots_checked_at"),
        "provider_health_snapshots",
        ["checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_health_snapshots_provider_id"),
        "provider_health_snapshots",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_health_snapshots_status"),
        "provider_health_snapshots",
        ["status"],
        unique=False,
    )
    op.create_table(
        "provider_rate_limit_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("requests_remaining", sa.Integer(), nullable=True),
        sa.Column("reset_at", packages.database.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("rate_limit_events", sa.Integer(), nullable=False),
        sa.Column("last_response_status", sa.Integer(), nullable=True),
        sa.Column("updated_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_provider_rate_limit_states_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_rate_limit_states")),
    )
    op.create_index(
        op.f("ix_provider_rate_limit_states_provider_id"),
        "provider_rate_limit_states",
        ["provider_id"],
        unique=True,
    )
    op.create_table(
        "provider_symbol_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_symbol", sa.String(length=32), nullable=False),
        sa.Column("provider_symbol", sa.String(length=64), nullable=False),
        sa.Column("exchange_code", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_provider_symbol_mappings_provider_id_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_symbol_mappings")),
        sa.UniqueConstraint("provider_id", "canonical_symbol", name="uq_provider_canonical_symbol"),
        sa.UniqueConstraint("provider_id", "provider_symbol", name="uq_provider_external_symbol"),
    )
    op.create_index(
        op.f("ix_provider_symbol_mappings_canonical_symbol"),
        "provider_symbol_mappings",
        ["canonical_symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_symbol_mappings_provider_id"),
        "provider_symbol_mappings",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_symbol_mappings_provider_symbol"),
        "provider_symbol_mappings",
        ["provider_symbol"],
        unique=False,
    )
    op.create_table(
        "reconciliation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("records_checked", sa.Integer(), nullable=False),
        sa.Column("issue_count", sa.Integer(), nullable=False),
        sa.Column("conflict_count", sa.Integer(), nullable=False),
        sa.Column("started_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "completed_at", packages.database.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_reconciliation_runs_provider_id_providers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_runs")),
    )
    op.create_index(
        op.f("ix_reconciliation_runs_provider_id"),
        "reconciliation_runs",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_runs_status"), "reconciliation_runs", ["status"], unique=False
    )
    op.create_table(
        "job_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["import_jobs.id"],
            name=op.f("fk_job_events_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
    )
    op.create_index(op.f("ix_job_events_created_at"), "job_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_job_events_event_type"), "job_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False)
    op.create_table(
        "reconciliation_issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("provider_id", sa.Uuid(), nullable=True),
        sa.Column("issue_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("record_identifier", sa.String(length=180), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("resolution_decision", sa.String(length=80), nullable=False),
        sa.Column("existing_checksum", sa.String(length=64), nullable=True),
        sa.Column("incoming_checksum", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_reconciliation_issues_asset_id_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_reconciliation_issues_provider_id_providers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_runs.id"],
            name=op.f("fk_reconciliation_issues_run_id_reconciliation_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_issues")),
    )
    op.create_index(
        op.f("ix_reconciliation_issues_asset_id"),
        "reconciliation_issues",
        ["asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_issues_created_at"),
        "reconciliation_issues",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_issues_issue_type"),
        "reconciliation_issues",
        ["issue_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_issues_provider_id"),
        "reconciliation_issues",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_issues_run_id"), "reconciliation_issues", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliation_issues_severity"),
        "reconciliation_issues",
        ["severity"],
        unique=False,
    )
    op.create_table(
        "schedule_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "scheduled_for", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["import_jobs.id"],
            name=op.f("fk_schedule_runs_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["import_schedules.id"],
            name=op.f("fk_schedule_runs_schedule_id_import_schedules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_runs")),
        sa.UniqueConstraint("schedule_id", "scheduled_for", name="uq_schedule_run_due_time"),
    )
    op.create_index(op.f("ix_schedule_runs_job_id"), "schedule_runs", ["job_id"], unique=True)
    op.create_index(
        op.f("ix_schedule_runs_schedule_id"), "schedule_runs", ["schedule_id"], unique=False
    )
    op.create_index(
        op.f("ix_schedule_runs_scheduled_for"), "schedule_runs", ["scheduled_for"], unique=False
    )
    op.create_table(
        "worker_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("worker_identifier", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "last_heartbeat_at", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("stopped_at", packages.database.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("current_job_id", sa.Uuid(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_worker_instances_current_job_id_import_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_instances")),
    )
    op.create_index(
        op.f("ix_worker_instances_current_job_id"),
        "worker_instances",
        ["current_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_worker_instances_last_heartbeat_at"),
        "worker_instances",
        ["last_heartbeat_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_worker_instances_status"), "worker_instances", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_worker_instances_worker_identifier"),
        "worker_instances",
        ["worker_identifier"],
        unique=True,
    )
    op.create_table(
        "job_leases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("worker_id", sa.Uuid(), nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=False),
        sa.Column(
            "acquired_at", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("expires_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "heartbeat_at", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.CheckConstraint("expires_at > acquired_at", name=op.f("ck_job_leases_job_lease_expiry")),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["import_jobs.id"],
            name=op.f("fk_job_leases_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["worker_instances.id"],
            name=op.f("fk_job_leases_worker_id_worker_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_leases")),
        sa.UniqueConstraint("lease_token", name=op.f("uq_job_leases_lease_token")),
    )
    op.create_index(op.f("ix_job_leases_expires_at"), "job_leases", ["expires_at"], unique=False)
    op.create_index(op.f("ix_job_leases_job_id"), "job_leases", ["job_id"], unique=True)
    op.create_index(op.f("ix_job_leases_worker_id"), "job_leases", ["worker_id"], unique=False)
    op.create_table(
        "operational_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=80), nullable=False),
        sa.Column("metric_value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("worker_id", sa.Uuid(), nullable=True),
        sa.Column(
            "recorded_at", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["import_jobs.id"],
            name=op.f("fk_operational_metrics_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["worker_instances.id"],
            name=op.f("fk_operational_metrics_worker_id_worker_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operational_metrics")),
    )
    op.create_index(
        op.f("ix_operational_metrics_job_id"), "operational_metrics", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_operational_metrics_metric_name"),
        "operational_metrics",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_metrics_recorded_at"),
        "operational_metrics",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_metrics_worker_id"), "operational_metrics", ["worker_id"], unique=False
    )
    op.add_column("import_jobs", sa.Column("idempotency_key", sa.String(length=128), nullable=True))
    op.add_column(
        "import_jobs", sa.Column("dry_run", sa.Boolean(), server_default="0", nullable=False)
    )
    op.add_column(
        "import_jobs",
        sa.Column(
            "adjustment_preference",
            sa.String(length=24),
            server_default="unadjusted",
            nullable=False,
        ),
    )
    op.add_column(
        "import_jobs",
        sa.Column("queue_name", sa.String(length=32), server_default="manual", nullable=False),
    )
    op.create_index(
        op.f("ix_import_jobs_idempotency_key"), "import_jobs", ["idempotency_key"], unique=True
    )
    op.create_index(op.f("ix_import_jobs_queue_name"), "import_jobs", ["queue_name"], unique=False)
    with op.batch_alter_table("price_bars") as batch_op:
        batch_op.add_column(sa.Column("import_job_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column("raw_provider_metadata", sa.JSON(), server_default="{}", nullable=False)
        )
        batch_op.create_index(op.f("ix_price_bars_import_job_id"), ["import_job_id"], unique=False)
        batch_op.create_foreign_key(
            op.f("fk_price_bars_import_job_id_import_jobs"),
            "import_jobs",
            ["import_job_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_bars") as batch_op:
        batch_op.drop_constraint(
            op.f("fk_price_bars_import_job_id_import_jobs"), type_="foreignkey"
        )
        batch_op.drop_index(op.f("ix_price_bars_import_job_id"))
        batch_op.drop_column("raw_provider_metadata")
        batch_op.drop_column("import_job_id")
    op.drop_index(op.f("ix_import_jobs_queue_name"), table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_idempotency_key"), table_name="import_jobs")
    op.drop_column("import_jobs", "queue_name")
    op.drop_column("import_jobs", "adjustment_preference")
    op.drop_column("import_jobs", "dry_run")
    op.drop_column("import_jobs", "idempotency_key")
    op.drop_column("backtest_runs", "calendar_code")
    op.drop_column("backtest_runs", "adjustment_statuses")
    op.drop_column("backtest_runs", "import_job_identifiers")
    op.drop_column("backtest_runs", "provider_identifiers")
    op.drop_column("backtest_runs", "data_classification")
    op.drop_index(op.f("ix_operational_metrics_worker_id"), table_name="operational_metrics")
    op.drop_index(op.f("ix_operational_metrics_recorded_at"), table_name="operational_metrics")
    op.drop_index(op.f("ix_operational_metrics_metric_name"), table_name="operational_metrics")
    op.drop_index(op.f("ix_operational_metrics_job_id"), table_name="operational_metrics")
    op.drop_table("operational_metrics")
    op.drop_index(op.f("ix_job_leases_worker_id"), table_name="job_leases")
    op.drop_index(op.f("ix_job_leases_job_id"), table_name="job_leases")
    op.drop_index(op.f("ix_job_leases_expires_at"), table_name="job_leases")
    op.drop_table("job_leases")
    op.drop_index(op.f("ix_worker_instances_worker_identifier"), table_name="worker_instances")
    op.drop_index(op.f("ix_worker_instances_status"), table_name="worker_instances")
    op.drop_index(op.f("ix_worker_instances_last_heartbeat_at"), table_name="worker_instances")
    op.drop_index(op.f("ix_worker_instances_current_job_id"), table_name="worker_instances")
    op.drop_table("worker_instances")
    op.drop_index(op.f("ix_schedule_runs_scheduled_for"), table_name="schedule_runs")
    op.drop_index(op.f("ix_schedule_runs_schedule_id"), table_name="schedule_runs")
    op.drop_index(op.f("ix_schedule_runs_job_id"), table_name="schedule_runs")
    op.drop_table("schedule_runs")
    op.drop_index(op.f("ix_reconciliation_issues_severity"), table_name="reconciliation_issues")
    op.drop_index(op.f("ix_reconciliation_issues_run_id"), table_name="reconciliation_issues")
    op.drop_index(op.f("ix_reconciliation_issues_provider_id"), table_name="reconciliation_issues")
    op.drop_index(op.f("ix_reconciliation_issues_issue_type"), table_name="reconciliation_issues")
    op.drop_index(op.f("ix_reconciliation_issues_created_at"), table_name="reconciliation_issues")
    op.drop_index(op.f("ix_reconciliation_issues_asset_id"), table_name="reconciliation_issues")
    op.drop_table("reconciliation_issues")
    op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
    op.drop_index(op.f("ix_job_events_event_type"), table_name="job_events")
    op.drop_index(op.f("ix_job_events_created_at"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(op.f("ix_reconciliation_runs_status"), table_name="reconciliation_runs")
    op.drop_index(op.f("ix_reconciliation_runs_provider_id"), table_name="reconciliation_runs")
    op.drop_table("reconciliation_runs")
    op.drop_index(
        op.f("ix_provider_symbol_mappings_provider_symbol"), table_name="provider_symbol_mappings"
    )
    op.drop_index(
        op.f("ix_provider_symbol_mappings_provider_id"), table_name="provider_symbol_mappings"
    )
    op.drop_index(
        op.f("ix_provider_symbol_mappings_canonical_symbol"), table_name="provider_symbol_mappings"
    )
    op.drop_table("provider_symbol_mappings")
    op.drop_index(
        op.f("ix_provider_rate_limit_states_provider_id"), table_name="provider_rate_limit_states"
    )
    op.drop_table("provider_rate_limit_states")
    op.drop_index(
        op.f("ix_provider_health_snapshots_status"), table_name="provider_health_snapshots"
    )
    op.drop_index(
        op.f("ix_provider_health_snapshots_provider_id"), table_name="provider_health_snapshots"
    )
    op.drop_index(
        op.f("ix_provider_health_snapshots_checked_at"), table_name="provider_health_snapshots"
    )
    op.drop_table("provider_health_snapshots")
    op.drop_index(op.f("ix_import_schedules_provider_id"), table_name="import_schedules")
    op.drop_index(op.f("ix_import_schedules_next_run_at"), table_name="import_schedules")
    op.drop_index(op.f("ix_import_schedules_is_enabled"), table_name="import_schedules")
    op.drop_table("import_schedules")
    # ### end Alembic commands ###
