"""progressive research and point in time feature store

Revision ID: 2f9e39afd435
Revises: 61293cddc2e2
Create Date: 2026-08-08 01:35:23.663871
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import packages.database.types

revision: str = "2f9e39afd435"
down_revision: str | None = "61293cddc2e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("feature_key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=40), nullable=False),
        sa.Column("entity_type", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','active','deprecated','disabled')",
            name=op.f("ck_feature_definitions_feature_definition_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_feature_definitions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_definitions")),
        sa.UniqueConstraint("workspace_id", "feature_key", name="uq_feature_definition_key"),
    )
    op.create_index(
        op.f("ix_feature_definitions_domain"), "feature_definitions", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_feature_definitions_feature_key"),
        "feature_definitions",
        ["feature_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_definitions_status"), "feature_definitions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_feature_definitions_workspace_id"),
        "feature_definitions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "feature_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("intended_resolution", sa.String(length=24), nullable=False),
        sa.Column("estimated_compute_cost", sa.String(length=16), nullable=False),
        sa.Column(
            "active_from", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("active_to", packages.database.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "active_to IS NULL OR active_to > active_from",
            name=op.f("ck_feature_sets_feature_set_range"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_feature_sets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_sets")),
        sa.UniqueConstraint("workspace_id", "key", "version", name="uq_feature_set_version"),
    )
    op.create_index(
        op.f("ix_feature_sets_active_from"), "feature_sets", ["active_from"], unique=False
    )
    op.create_index(op.f("ix_feature_sets_active_to"), "feature_sets", ["active_to"], unique=False)
    op.create_index(
        op.f("ix_feature_sets_intended_resolution"),
        "feature_sets",
        ["intended_resolution"],
        unique=False,
    )
    op.create_index(op.f("ix_feature_sets_key"), "feature_sets", ["key"], unique=False)
    op.create_index(
        op.f("ix_feature_sets_workspace_id"), "feature_sets", ["workspace_id"], unique=False
    )
    op.create_table(
        "research_resolution_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "active_from", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_resolution_policies_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_resolution_policies")),
        sa.UniqueConstraint("workspace_id", "version", name="uq_resolution_policy_version"),
    )
    op.create_index(
        op.f("ix_research_resolution_policies_active_from"),
        "research_resolution_policies",
        ["active_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_resolution_policies_workspace_id"),
        "research_resolution_policies",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "research_universes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_type", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=160), nullable=False),
        sa.Column("selection_rules", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_universes_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_universes")),
        sa.UniqueConstraint("workspace_id", "name", name="uq_research_universe_name"),
    )
    op.create_index(
        op.f("ix_research_universes_workspace_id"),
        "research_universes",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "feature_definition_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feature_definition_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("output_type", sa.String(length=32), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("frequency", sa.String(length=32), nullable=False),
        sa.Column("lookback_requirement", sa.String(length=80), nullable=False),
        sa.Column("computation_method", sa.String(length=160), nullable=False),
        sa.Column("implementation_version", sa.String(length=64), nullable=False),
        sa.Column("required_datasets", sa.JSON(), nullable=False),
        sa.Column("required_graph_drivers", sa.JSON(), nullable=False),
        sa.Column("temporal_policy", sa.JSON(), nullable=False),
        sa.Column("missing_data_policy", sa.String(length=80), nullable=False),
        sa.Column("normalization_policy", sa.String(length=80), nullable=False),
        sa.Column("cost_class", sa.String(length=16), nullable=False),
        sa.Column("determinism", sa.String(length=24), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "cost_class IN ('free','low','medium','high','premium')",
            name=op.f("ck_feature_definition_versions_feature_version_cost"),
        ),
        sa.CheckConstraint(
            "determinism IN ('deterministic','non_deterministic')",
            name=op.f("ck_feature_definition_versions_feature_version_determinism"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_definition_id"],
            ["feature_definitions.id"],
            name=op.f("fk_feature_definition_versions_feature_definition_id_feature_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_definition_versions")),
        sa.UniqueConstraint(
            "feature_definition_id", "version", name="uq_feature_definition_version"
        ),
    )
    op.create_index(
        op.f("ix_feature_definition_versions_feature_definition_id"),
        "feature_definition_versions",
        ["feature_definition_id"],
        unique=False,
    )
    op.create_table(
        "research_budgets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.String(length=24), nullable=False),
        sa.Column("limits", sa.JSON(), nullable=False),
        sa.Column("cost_class", sa.String(length=16), nullable=False),
        sa.Column("monetary_estimate", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["research_resolution_policies.id"],
            name=op.f("fk_research_budgets_policy_id_research_resolution_policies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_budgets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_budgets")),
        sa.UniqueConstraint("workspace_id", "policy_id", "level", name="uq_research_budget_level"),
    )
    op.create_index(op.f("ix_research_budgets_level"), "research_budgets", ["level"], unique=False)
    op.create_index(
        op.f("ix_research_budgets_policy_id"), "research_budgets", ["policy_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_budgets_workspace_id"), "research_budgets", ["workspace_id"], unique=False
    )
    op.create_table(
        "research_universe_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("universe_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "effective_from", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "effective_to", packages.database.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "simulation_eligible_time",
            packages.database.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("membership_checksum", sa.String(length=64), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_research_universe_versions_universe_version_range"),
        ),
        sa.ForeignKeyConstraint(
            ["universe_id"],
            ["research_universes.id"],
            name=op.f("fk_research_universe_versions_universe_id_research_universes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_universe_versions")),
        sa.UniqueConstraint("universe_id", "version", name="uq_research_universe_version"),
    )
    op.create_index(
        op.f("ix_research_universe_versions_effective_from"),
        "research_universe_versions",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_universe_versions_effective_to"),
        "research_universe_versions",
        ["effective_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_universe_versions_simulation_eligible_time"),
        "research_universe_versions",
        ["simulation_eligible_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_universe_versions_universe_id"),
        "research_universe_versions",
        ["universe_id"],
        unique=False,
    )
    op.create_index(
        "ix_universe_version_as_of",
        "research_universe_versions",
        ["universe_id", "simulation_eligible_time", "effective_from"],
        unique=False,
    )
    op.create_table(
        "feature_materialization_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("feature_set_id", sa.Uuid(), nullable=True),
        sa.Column("universe_version_id", sa.Uuid(), nullable=True),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("router_override", sa.Boolean(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("error_class", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "requested_at", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("started_at", packages.database.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "completed_at", packages.database.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','failed','cancelled','deferred')",
            name=op.f("ck_feature_materialization_jobs_feature_job_status"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_set_id"],
            ["feature_sets.id"],
            name=op.f("fk_feature_materialization_jobs_feature_set_id_feature_sets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["universe_version_id"],
            ["research_universe_versions.id"],
            name=op.f(
                "fk_feature_materialization_jobs_universe_version_id_research_universe_versions"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_feature_materialization_jobs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_materialization_jobs")),
        sa.UniqueConstraint("workspace_id", "idempotency_key", name="uq_feature_job_workspace_key"),
    )
    op.create_index(
        op.f("ix_feature_materialization_jobs_feature_set_id"),
        "feature_materialization_jobs",
        ["feature_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_materialization_jobs_requested_at"),
        "feature_materialization_jobs",
        ["requested_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_materialization_jobs_status"),
        "feature_materialization_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_materialization_jobs_universe_version_id"),
        "feature_materialization_jobs",
        ["universe_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_materialization_jobs_workspace_id"),
        "feature_materialization_jobs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "feature_set_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feature_set_id", sa.Uuid(), nullable=False),
        sa.Column("feature_version_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_set_id"],
            ["feature_sets.id"],
            name=op.f("fk_feature_set_memberships_feature_set_id_feature_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["feature_version_id"],
            ["feature_definition_versions.id"],
            name=op.f("fk_feature_set_memberships_feature_version_id_feature_definition_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_set_memberships")),
        sa.UniqueConstraint("feature_set_id", "feature_version_id", name="uq_feature_set_member"),
        sa.UniqueConstraint("feature_set_id", "position", name="uq_feature_set_position"),
    )
    op.create_index(
        op.f("ix_feature_set_memberships_feature_set_id"),
        "feature_set_memberships",
        ["feature_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_set_memberships_feature_version_id"),
        "feature_set_memberships",
        ["feature_version_id"],
        unique=False,
    )
    op.create_table(
        "feature_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("universe_version_id", sa.Uuid(), nullable=False),
        sa.Column("feature_set_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_time", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("entity_ids", sa.JSON(), nullable=False),
        sa.Column("feature_value_ids", sa.JSON(), nullable=False),
        sa.Column("application_sha", sa.String(length=64), nullable=False),
        sa.Column("migration_head", sa.String(length=40), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_set_id"],
            ["feature_sets.id"],
            name=op.f("fk_feature_snapshots_feature_set_id_feature_sets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["universe_version_id"],
            ["research_universe_versions.id"],
            name=op.f("fk_feature_snapshots_universe_version_id_research_universe_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_feature_snapshots_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_snapshots")),
    )
    op.create_index(
        op.f("ix_feature_snapshots_as_of_time"), "feature_snapshots", ["as_of_time"], unique=False
    )
    op.create_index(
        op.f("ix_feature_snapshots_checksum"), "feature_snapshots", ["checksum"], unique=True
    )
    op.create_index(
        op.f("ix_feature_snapshots_feature_set_id"),
        "feature_snapshots",
        ["feature_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_snapshots_universe_version_id"),
        "feature_snapshots",
        ["universe_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_snapshots_workspace_id"),
        "feature_snapshots",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "feature_values",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("feature_version_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "observation_time", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "effective_time", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "calculation_time", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "simulation_eligible_time",
            packages.database.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("numeric_value", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("text_value", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("quality_state", sa.String(length=32), nullable=False),
        sa.Column("quality_flags", sa.JSON(), nullable=False),
        sa.Column("input_checksum", sa.String(length=64), nullable=False),
        sa.Column("computation_checksum", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("deterministic_seed", sa.Integer(), nullable=True),
        sa.Column("normalization", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "quality_state IN ('complete','partial','missing_inputs','stale_inputs',"
            "'ambiguous_inputs','low_confidence_graph','revised','temporally_unsafe',"
            "'failed_computation')",
            name=op.f("ck_feature_values_feature_value_quality"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["economic_entities.id"],
            name=op.f("fk_feature_values_entity_id_economic_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["feature_version_id"],
            ["feature_definition_versions.id"],
            name=op.f("fk_feature_values_feature_version_id_feature_definition_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["feature_materialization_jobs.id"],
            name=op.f("fk_feature_values_job_id_feature_materialization_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_feature_values_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_values")),
        sa.UniqueConstraint(
            "feature_version_id",
            "entity_id",
            "observation_time",
            "input_checksum",
            name="uq_feature_value_input_identity",
        ),
    )
    op.create_index(
        "ix_feature_value_as_of",
        "feature_values",
        ["feature_version_id", "entity_id", "simulation_eligible_time", "observation_time"],
        unique=False,
    )
    op.create_index(
        "ix_feature_value_matrix",
        "feature_values",
        ["entity_id", "simulation_eligible_time", "feature_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_values_computation_checksum"),
        "feature_values",
        ["computation_checksum"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_values_entity_id"), "feature_values", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_feature_values_feature_version_id"),
        "feature_values",
        ["feature_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_values_input_checksum"), "feature_values", ["input_checksum"], unique=False
    )
    op.create_index(op.f("ix_feature_values_job_id"), "feature_values", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_feature_values_observation_time"),
        "feature_values",
        ["observation_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_values_quality_state"), "feature_values", ["quality_state"], unique=False
    )
    op.create_index(
        op.f("ix_feature_values_simulation_eligible_time"),
        "feature_values",
        ["simulation_eligible_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_values_workspace_id"), "feature_values", ["workspace_id"], unique=False
    )
    op.create_table(
        "research_candidate_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("universe_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("current_level", sa.String(length=24), nullable=False),
        sa.Column("previous_level", sa.String(length=24), nullable=True),
        sa.Column("entered_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("promotion_reason", sa.Text(), nullable=True),
        sa.Column("demotion_reason", sa.Text(), nullable=True),
        sa.Column("supporting_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("budget_impact", sa.JSON(), nullable=False),
        sa.Column(
            "next_review_time", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["economic_entities.id"],
            name=op.f("fk_research_candidate_states_entity_id_economic_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["research_resolution_policies.id"],
            name=op.f("fk_research_candidate_states_policy_id_research_resolution_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supporting_snapshot_id"],
            ["feature_snapshots.id"],
            name=op.f("fk_research_candidate_states_supporting_snapshot_id_feature_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["universe_id"],
            ["research_universes.id"],
            name=op.f("fk_research_candidate_states_universe_id_research_universes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_candidate_states_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_candidate_states")),
        sa.UniqueConstraint(
            "workspace_id",
            "universe_id",
            "entity_id",
            "policy_id",
            name="uq_candidate_policy_state",
        ),
    )
    op.create_index(
        op.f("ix_research_candidate_states_current_level"),
        "research_candidate_states",
        ["current_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_candidate_states_entity_id"),
        "research_candidate_states",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_candidate_states_next_review_time"),
        "research_candidate_states",
        ["next_review_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_candidate_states_policy_id"),
        "research_candidate_states",
        ["policy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_candidate_states_supporting_snapshot_id"),
        "research_candidate_states",
        ["supporting_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_candidate_states_universe_id"),
        "research_candidate_states",
        ["universe_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_candidate_states_workspace_id"),
        "research_candidate_states",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "research_screening_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("universe_version_id", sa.Uuid(), nullable=False),
        sa.Column("feature_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_time", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("total_candidates", sa.Integer(), nullable=False),
        sa.Column("promoted", sa.Integer(), nullable=False),
        sa.Column("deferred", sa.Integer(), nullable=False),
        sa.Column("demoted", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("budget_usage", sa.JSON(), nullable=False),
        sa.Column("reason_distribution", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["feature_snapshots.id"],
            name=op.f("fk_research_screening_runs_feature_snapshot_id_feature_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["research_resolution_policies.id"],
            name=op.f("fk_research_screening_runs_policy_id_research_resolution_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["universe_version_id"],
            ["research_universe_versions.id"],
            name=op.f("fk_research_screening_runs_universe_version_id_research_universe_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_screening_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_screening_runs")),
    )
    op.create_index(
        op.f("ix_research_screening_runs_as_of_time"),
        "research_screening_runs",
        ["as_of_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_screening_runs_checksum"),
        "research_screening_runs",
        ["checksum"],
        unique=True,
    )
    op.create_index(
        op.f("ix_research_screening_runs_feature_snapshot_id"),
        "research_screening_runs",
        ["feature_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_screening_runs_policy_id"),
        "research_screening_runs",
        ["policy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_screening_runs_universe_version_id"),
        "research_screening_runs",
        ["universe_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_screening_runs_workspace_id"),
        "research_screening_runs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "research_universe_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("universe_version_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("valid_to", packages.database.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "simulation_eligible_time",
            packages.database.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("source_manifest_id", sa.Uuid(), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_research_universe_memberships_universe_membership_range"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["economic_entities.id"],
            name=op.f("fk_research_universe_memberships_entity_id_economic_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_manifest_id"],
            ["data_manifests.id"],
            name=op.f("fk_research_universe_memberships_source_manifest_id_data_manifests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["universe_version_id"],
            ["research_universe_versions.id"],
            name=op.f(
                "fk_research_universe_memberships_universe_version_id_research_universe_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_universe_memberships")),
        sa.UniqueConstraint(
            "universe_version_id", "entity_id", name="uq_universe_membership_entity"
        ),
    )
    op.create_index(
        op.f("ix_research_universe_memberships_entity_id"),
        "research_universe_memberships",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_universe_memberships_simulation_eligible_time"),
        "research_universe_memberships",
        ["simulation_eligible_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_universe_memberships_source_manifest_id"),
        "research_universe_memberships",
        ["source_manifest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_universe_memberships_universe_version_id"),
        "research_universe_memberships",
        ["universe_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_universe_memberships_valid_from"),
        "research_universe_memberships",
        ["valid_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_universe_memberships_valid_to"),
        "research_universe_memberships",
        ["valid_to"],
        unique=False,
    )
    op.create_index(
        "ix_universe_membership_as_of",
        "research_universe_memberships",
        ["universe_version_id", "simulation_eligible_time", "valid_from"],
        unique=False,
    )
    op.create_table(
        "feature_lineage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feature_value_id", sa.Uuid(), nullable=False),
        sa.Column("source_manifest_ids", sa.JSON(), nullable=False),
        sa.Column("source_observation_refs", sa.JSON(), nullable=False),
        sa.Column("graph_relationship_ids", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("grouped_input_manifest", sa.JSON(), nullable=False),
        sa.Column("computation_version", sa.String(length=64), nullable=False),
        sa.Column("lineage_checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_value_id"],
            ["feature_values.id"],
            name=op.f("fk_feature_lineage_feature_value_id_feature_values"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_lineage")),
        sa.UniqueConstraint(
            "feature_value_id", "lineage_checksum", name="uq_feature_lineage_checksum"
        ),
    )
    op.create_index(
        op.f("ix_feature_lineage_feature_value_id"),
        "feature_lineage",
        ["feature_value_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_lineage_lineage_checksum"),
        "feature_lineage",
        ["lineage_checksum"],
        unique=False,
    )
    op.create_table(
        "research_budget_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("screening_run_id", sa.Uuid(), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column(
            "recorded_at", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["research_budgets.id"],
            name=op.f("fk_research_budget_usage_budget_id_research_budgets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["screening_run_id"],
            ["research_screening_runs.id"],
            name=op.f("fk_research_budget_usage_screening_run_id_research_screening_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_budget_usage")),
    )
    op.create_index(
        op.f("ix_research_budget_usage_budget_id"),
        "research_budget_usage",
        ["budget_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_budget_usage_decision"),
        "research_budget_usage",
        ["decision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_budget_usage_screening_run_id"),
        "research_budget_usage",
        ["screening_run_id"],
        unique=False,
    )
    op.create_table(
        "research_screening_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("screening_run_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("score_components", sa.JSON(), nullable=False),
        sa.Column("recommendation", sa.String(length=24), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("missing_information", sa.JSON(), nullable=False),
        sa.Column("budget_impact", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["economic_entities.id"],
            name=op.f("fk_research_screening_decisions_entity_id_economic_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["screening_run_id"],
            ["research_screening_runs.id"],
            name=op.f("fk_research_screening_decisions_screening_run_id_research_screening_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_screening_decisions")),
        sa.UniqueConstraint("screening_run_id", "entity_id", name="uq_screening_decision_entity"),
    )
    op.create_index(
        op.f("ix_research_screening_decisions_entity_id"),
        "research_screening_decisions",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_screening_decisions_recommendation"),
        "research_screening_decisions",
        ["recommendation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_screening_decisions_score"),
        "research_screening_decisions",
        ["score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_screening_decisions_screening_run_id"),
        "research_screening_decisions",
        ["screening_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_research_screening_decisions_screening_run_id"),
        table_name="research_screening_decisions",
    )
    op.drop_index(
        op.f("ix_research_screening_decisions_score"), table_name="research_screening_decisions"
    )
    op.drop_index(
        op.f("ix_research_screening_decisions_recommendation"),
        table_name="research_screening_decisions",
    )
    op.drop_index(
        op.f("ix_research_screening_decisions_entity_id"), table_name="research_screening_decisions"
    )
    op.drop_table("research_screening_decisions")
    op.drop_index(
        op.f("ix_research_budget_usage_screening_run_id"), table_name="research_budget_usage"
    )
    op.drop_index(op.f("ix_research_budget_usage_decision"), table_name="research_budget_usage")
    op.drop_index(op.f("ix_research_budget_usage_budget_id"), table_name="research_budget_usage")
    op.drop_table("research_budget_usage")
    op.drop_index(op.f("ix_feature_lineage_lineage_checksum"), table_name="feature_lineage")
    op.drop_index(op.f("ix_feature_lineage_feature_value_id"), table_name="feature_lineage")
    op.drop_table("feature_lineage")
    op.drop_index("ix_universe_membership_as_of", table_name="research_universe_memberships")
    op.drop_index(
        op.f("ix_research_universe_memberships_valid_to"),
        table_name="research_universe_memberships",
    )
    op.drop_index(
        op.f("ix_research_universe_memberships_valid_from"),
        table_name="research_universe_memberships",
    )
    op.drop_index(
        op.f("ix_research_universe_memberships_universe_version_id"),
        table_name="research_universe_memberships",
    )
    op.drop_index(
        op.f("ix_research_universe_memberships_source_manifest_id"),
        table_name="research_universe_memberships",
    )
    op.drop_index(
        op.f("ix_research_universe_memberships_simulation_eligible_time"),
        table_name="research_universe_memberships",
    )
    op.drop_index(
        op.f("ix_research_universe_memberships_entity_id"),
        table_name="research_universe_memberships",
    )
    op.drop_table("research_universe_memberships")
    op.drop_index(
        op.f("ix_research_screening_runs_workspace_id"), table_name="research_screening_runs"
    )
    op.drop_index(
        op.f("ix_research_screening_runs_universe_version_id"), table_name="research_screening_runs"
    )
    op.drop_index(
        op.f("ix_research_screening_runs_policy_id"), table_name="research_screening_runs"
    )
    op.drop_index(
        op.f("ix_research_screening_runs_feature_snapshot_id"), table_name="research_screening_runs"
    )
    op.drop_index(op.f("ix_research_screening_runs_checksum"), table_name="research_screening_runs")
    op.drop_index(
        op.f("ix_research_screening_runs_as_of_time"), table_name="research_screening_runs"
    )
    op.drop_table("research_screening_runs")
    op.drop_index(
        op.f("ix_research_candidate_states_workspace_id"), table_name="research_candidate_states"
    )
    op.drop_index(
        op.f("ix_research_candidate_states_universe_id"), table_name="research_candidate_states"
    )
    op.drop_index(
        op.f("ix_research_candidate_states_supporting_snapshot_id"),
        table_name="research_candidate_states",
    )
    op.drop_index(
        op.f("ix_research_candidate_states_policy_id"), table_name="research_candidate_states"
    )
    op.drop_index(
        op.f("ix_research_candidate_states_next_review_time"),
        table_name="research_candidate_states",
    )
    op.drop_index(
        op.f("ix_research_candidate_states_entity_id"), table_name="research_candidate_states"
    )
    op.drop_index(
        op.f("ix_research_candidate_states_current_level"), table_name="research_candidate_states"
    )
    op.drop_table("research_candidate_states")
    op.drop_index(op.f("ix_feature_values_workspace_id"), table_name="feature_values")
    op.drop_index(op.f("ix_feature_values_simulation_eligible_time"), table_name="feature_values")
    op.drop_index(op.f("ix_feature_values_quality_state"), table_name="feature_values")
    op.drop_index(op.f("ix_feature_values_observation_time"), table_name="feature_values")
    op.drop_index(op.f("ix_feature_values_job_id"), table_name="feature_values")
    op.drop_index(op.f("ix_feature_values_input_checksum"), table_name="feature_values")
    op.drop_index(op.f("ix_feature_values_feature_version_id"), table_name="feature_values")
    op.drop_index(op.f("ix_feature_values_entity_id"), table_name="feature_values")
    op.drop_index(op.f("ix_feature_values_computation_checksum"), table_name="feature_values")
    op.drop_index("ix_feature_value_matrix", table_name="feature_values")
    op.drop_index("ix_feature_value_as_of", table_name="feature_values")
    op.drop_table("feature_values")
    op.drop_index(op.f("ix_feature_snapshots_workspace_id"), table_name="feature_snapshots")
    op.drop_index(op.f("ix_feature_snapshots_universe_version_id"), table_name="feature_snapshots")
    op.drop_index(op.f("ix_feature_snapshots_feature_set_id"), table_name="feature_snapshots")
    op.drop_index(op.f("ix_feature_snapshots_checksum"), table_name="feature_snapshots")
    op.drop_index(op.f("ix_feature_snapshots_as_of_time"), table_name="feature_snapshots")
    op.drop_table("feature_snapshots")
    op.drop_index(
        op.f("ix_feature_set_memberships_feature_version_id"), table_name="feature_set_memberships"
    )
    op.drop_index(
        op.f("ix_feature_set_memberships_feature_set_id"), table_name="feature_set_memberships"
    )
    op.drop_table("feature_set_memberships")
    op.drop_index(
        op.f("ix_feature_materialization_jobs_workspace_id"),
        table_name="feature_materialization_jobs",
    )
    op.drop_index(
        op.f("ix_feature_materialization_jobs_universe_version_id"),
        table_name="feature_materialization_jobs",
    )
    op.drop_index(
        op.f("ix_feature_materialization_jobs_status"), table_name="feature_materialization_jobs"
    )
    op.drop_index(
        op.f("ix_feature_materialization_jobs_requested_at"),
        table_name="feature_materialization_jobs",
    )
    op.drop_index(
        op.f("ix_feature_materialization_jobs_feature_set_id"),
        table_name="feature_materialization_jobs",
    )
    op.drop_table("feature_materialization_jobs")
    op.drop_index("ix_universe_version_as_of", table_name="research_universe_versions")
    op.drop_index(
        op.f("ix_research_universe_versions_universe_id"), table_name="research_universe_versions"
    )
    op.drop_index(
        op.f("ix_research_universe_versions_simulation_eligible_time"),
        table_name="research_universe_versions",
    )
    op.drop_index(
        op.f("ix_research_universe_versions_effective_to"), table_name="research_universe_versions"
    )
    op.drop_index(
        op.f("ix_research_universe_versions_effective_from"),
        table_name="research_universe_versions",
    )
    op.drop_table("research_universe_versions")
    op.drop_index(op.f("ix_research_budgets_workspace_id"), table_name="research_budgets")
    op.drop_index(op.f("ix_research_budgets_policy_id"), table_name="research_budgets")
    op.drop_index(op.f("ix_research_budgets_level"), table_name="research_budgets")
    op.drop_table("research_budgets")
    op.drop_index(
        op.f("ix_feature_definition_versions_feature_definition_id"),
        table_name="feature_definition_versions",
    )
    op.drop_table("feature_definition_versions")
    op.drop_index(op.f("ix_research_universes_workspace_id"), table_name="research_universes")
    op.drop_table("research_universes")
    op.drop_index(
        op.f("ix_research_resolution_policies_workspace_id"),
        table_name="research_resolution_policies",
    )
    op.drop_index(
        op.f("ix_research_resolution_policies_active_from"),
        table_name="research_resolution_policies",
    )
    op.drop_table("research_resolution_policies")
    op.drop_index(op.f("ix_feature_sets_workspace_id"), table_name="feature_sets")
    op.drop_index(op.f("ix_feature_sets_key"), table_name="feature_sets")
    op.drop_index(op.f("ix_feature_sets_intended_resolution"), table_name="feature_sets")
    op.drop_index(op.f("ix_feature_sets_active_to"), table_name="feature_sets")
    op.drop_index(op.f("ix_feature_sets_active_from"), table_name="feature_sets")
    op.drop_table("feature_sets")
    op.drop_index(op.f("ix_feature_definitions_workspace_id"), table_name="feature_definitions")
    op.drop_index(op.f("ix_feature_definitions_status"), table_name="feature_definitions")
    op.drop_index(op.f("ix_feature_definitions_feature_key"), table_name="feature_definitions")
    op.drop_index(op.f("ix_feature_definitions_domain"), table_name="feature_definitions")
    op.drop_table("feature_definitions")
    # ### end Alembic commands ###
