"""prospective calibration feedback and paper portfolio

Revision ID: 4e398fc4c9a1
Revises: e2517ff0412b
Create Date: 2026-08-15 16:14:44.579394
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import packages.database.types

revision: str = "4e398fc4c9a1"
down_revision: str | None = "e2517ff0412b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_key", sa.String(length=160), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('SUGGESTED','APPROVED','REJECTED','APPLIED','EXPIRED')",
            name=op.f("ck_feedback_recommendations_feedback_recommendation_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_feedback_recommendations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_recommendations")),
    )
    op.create_index(
        op.f("ix_feedback_recommendations_status"),
        "feedback_recommendations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_recommendations_subject_key"),
        "feedback_recommendations",
        ["subject_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_recommendations_subject_type"),
        "feedback_recommendations",
        ["subject_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_recommendations_workspace_id"),
        "feedback_recommendations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "forecast_calibration_analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_mode", sa.String(length=24), nullable=False),
        sa.Column("cohort", sa.JSON(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("bins", sa.JSON(), nullable=False),
        sa.Column("methodology_version", sa.String(length=40), nullable=False),
        sa.Column("as_of_time", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_forecast_calibration_analyses_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_calibration_analyses")),
        sa.UniqueConstraint("checksum", name=op.f("uq_forecast_calibration_analyses_checksum")),
    )
    op.create_index(
        op.f("ix_forecast_calibration_analyses_as_of_time"),
        "forecast_calibration_analyses",
        ["as_of_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_calibration_analyses_evaluation_mode"),
        "forecast_calibration_analyses",
        ["evaluation_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_calibration_analyses_status"),
        "forecast_calibration_analyses",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_calibration_analyses_workspace_id"),
        "forecast_calibration_analyses",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "forecast_target_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("outcome_type", sa.String(length=40), nullable=False),
        sa.Column("specification", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_forecast_target_definitions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_target_definitions")),
        sa.UniqueConstraint("workspace_id", "key", "version", name="uq_forecast_target_version"),
    )
    op.create_index(
        op.f("ix_forecast_target_definitions_key"),
        "forecast_target_definitions",
        ["key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_target_definitions_workspace_id"),
        "forecast_target_definitions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "paper_portfolio_construction_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("execution_mode", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_paper_portfolio_construction_policies_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_portfolio_construction_policies")),
        sa.UniqueConstraint("workspace_id", "version", name="uq_paper_construction_policy_version"),
    )
    op.create_index(
        op.f("ix_paper_portfolio_construction_policies_workspace_id"),
        "paper_portfolio_construction_policies",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "paper_research_eligibility_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("gates", sa.JSON(), nullable=False),
        sa.Column("uncalibrated_limits", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_paper_research_eligibility_policies_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_research_eligibility_policies")),
        sa.UniqueConstraint("workspace_id", "version", name="uq_paper_eligibility_policy_version"),
    )
    op.create_index(
        op.f("ix_paper_research_eligibility_policies_workspace_id"),
        "paper_research_eligibility_policies",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "research_reliability_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_key", sa.String(length=160), nullable=False),
        sa.Column("evaluation_mode", sa.String(length=24), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("evidence_references", sa.JSON(), nullable=False),
        sa.Column("methodology_version", sa.String(length=40), nullable=False),
        sa.Column("as_of_time", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_reliability_snapshots_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_reliability_snapshots")),
        sa.UniqueConstraint("checksum", name=op.f("uq_research_reliability_snapshots_checksum")),
        sa.UniqueConstraint(
            "workspace_id",
            "subject_type",
            "subject_key",
            "as_of_time",
            name="uq_reliability_subject_asof",
        ),
    )
    op.create_index(
        op.f("ix_research_reliability_snapshots_as_of_time"),
        "research_reliability_snapshots",
        ["as_of_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_reliability_snapshots_evaluation_mode"),
        "research_reliability_snapshots",
        ["evaluation_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_reliability_snapshots_subject_key"),
        "research_reliability_snapshots",
        ["subject_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_reliability_snapshots_subject_type"),
        "research_reliability_snapshots",
        ["subject_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_reliability_snapshots_workspace_id"),
        "research_reliability_snapshots",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "paper_portfolio_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("target_weights", sa.JSON(), nullable=False),
        sa.Column("current_weights", sa.JSON(), nullable=False),
        sa.Column("risk_results", sa.JSON(), nullable=False),
        sa.Column("scenario_results", sa.JSON(), nullable=False),
        sa.Column("order_preview", sa.JSON(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("as_of_time", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','RISK_REVIEW','APPROVED_FOR_SIMULATION','REJECTED',"
            "'EXECUTED_SIMULATION','EXPIRED')",
            name=op.f("ck_paper_portfolio_plans_paper_portfolio_plan_status"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["paper_portfolio_construction_policies.id"],
            name=op.f("fk_paper_portfolio_plans_policy_id_paper_portfolio_construction_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["paper_portfolios.id"],
            name=op.f("fk_paper_portfolio_plans_portfolio_id_paper_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_paper_portfolio_plans_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_portfolio_plans")),
        sa.UniqueConstraint("checksum", name=op.f("uq_paper_portfolio_plans_checksum")),
    )
    op.create_index(
        op.f("ix_paper_portfolio_plans_as_of_time"),
        "paper_portfolio_plans",
        ["as_of_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_portfolio_plans_portfolio_id"),
        "paper_portfolio_plans",
        ["portfolio_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_portfolio_plans_status"), "paper_portfolio_plans", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_paper_portfolio_plans_workspace_id"),
        "paper_portfolio_plans",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "paper_portfolio_evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("benchmark", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("attribution", sa.JSON(), nullable=False),
        sa.Column(
            "evaluated_at", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["paper_portfolio_plans.id"],
            name=op.f("fk_paper_portfolio_evaluations_plan_id_paper_portfolio_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_paper_portfolio_evaluations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_portfolio_evaluations")),
        sa.UniqueConstraint("checksum", name=op.f("uq_paper_portfolio_evaluations_checksum")),
    )
    op.create_index(
        op.f("ix_paper_portfolio_evaluations_evaluated_at"),
        "paper_portfolio_evaluations",
        ["evaluated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_portfolio_evaluations_plan_id"),
        "paper_portfolio_evaluations",
        ["plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_portfolio_evaluations_workspace_id"),
        "paper_portfolio_evaluations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "research_forecasts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("target_definition_id", sa.Uuid(), nullable=False),
        sa.Column("research_case_id", sa.Uuid(), nullable=True),
        sa.Column("dossier_id", sa.Uuid(), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("forecast_type", sa.String(length=32), nullable=False),
        sa.Column("forecast_value", sa.JSON(), nullable=False),
        sa.Column("evaluation_mode", sa.String(length=24), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("as_of_time", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "target_start_time", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "target_end_time", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "outcome_eligible_time",
            packages.database.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("locked_at", packages.database.types.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "evaluation_mode IN ('PROSPECTIVE','HISTORICAL_REPLAY','FIXTURE')",
            name=op.f("ck_research_forecasts_forecast_evaluation_mode"),
        ),
        sa.CheckConstraint(
            "forecast_type IN ('DIRECTIONAL','PROBABILITY','CONTINUOUS','INTERVAL','RANK',"
            "'SCENARIO_CONDITIONAL')",
            name=op.f("ck_research_forecasts_research_forecast_type"),
        ),
        sa.CheckConstraint(
            "state IN ('OPEN','LOCKED','INVALIDATED')",
            name=op.f("ck_research_forecasts_research_forecast_state"),
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["research_dossiers.id"],
            name=op.f("fk_research_forecasts_dossier_id_research_dossiers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["research_case_id"],
            ["research_cases.id"],
            name=op.f("fk_research_forecasts_research_case_id_research_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["research_forecasts.id"],
            name=op.f("fk_research_forecasts_supersedes_id_research_forecasts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_definition_id"],
            ["forecast_target_definitions.id"],
            name=op.f("fk_research_forecasts_target_definition_id_forecast_target_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_forecasts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_forecasts")),
        sa.UniqueConstraint("checksum", name=op.f("uq_research_forecasts_checksum")),
    )
    op.create_index(
        "ix_forecast_workspace_maturity",
        "research_forecasts",
        ["workspace_id", "outcome_eligible_time", "state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_forecasts_as_of_time"), "research_forecasts", ["as_of_time"], unique=False
    )
    op.create_index(
        op.f("ix_research_forecasts_dossier_id"), "research_forecasts", ["dossier_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_forecasts_evaluation_mode"),
        "research_forecasts",
        ["evaluation_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_forecasts_forecast_type"),
        "research_forecasts",
        ["forecast_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_forecasts_outcome_eligible_time"),
        "research_forecasts",
        ["outcome_eligible_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_forecasts_research_case_id"),
        "research_forecasts",
        ["research_case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_forecasts_state"), "research_forecasts", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_research_forecasts_supersedes_id"),
        "research_forecasts",
        ["supersedes_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_forecasts_target_definition_id"),
        "research_forecasts",
        ["target_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_forecasts_workspace_id"),
        "research_forecasts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "forecast_outcome_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("forecast_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("realized_value", sa.JSON(), nullable=False),
        sa.Column(
            "observed_at", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("source_manifest", sa.JSON(), nullable=False),
        sa.Column("outcome_checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_id"],
            ["research_forecasts.id"],
            name=op.f("fk_forecast_outcome_observations_forecast_id_research_forecasts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_forecast_outcome_observations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_outcome_observations")),
        sa.UniqueConstraint("forecast_id", "version", name="uq_forecast_outcome_version"),
        sa.UniqueConstraint(
            "outcome_checksum", name=op.f("uq_forecast_outcome_observations_outcome_checksum")
        ),
    )
    op.create_index(
        op.f("ix_forecast_outcome_observations_forecast_id"),
        "forecast_outcome_observations",
        ["forecast_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_outcome_observations_observed_at"),
        "forecast_outcome_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_outcome_observations_workspace_id"),
        "forecast_outcome_observations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "paper_allocation_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("forecast_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("asset_symbol", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("calibration_state", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("as_of_time", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_id"],
            ["research_forecasts.id"],
            name=op.f("fk_paper_allocation_candidates_forecast_id_research_forecasts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["paper_research_eligibility_policies.id"],
            name=op.f(
                "fk_paper_allocation_candidates_policy_id_paper_research_eligibility_policies"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_paper_allocation_candidates_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_allocation_candidates")),
        sa.UniqueConstraint("checksum", name=op.f("uq_paper_allocation_candidates_checksum")),
    )
    op.create_index(
        op.f("ix_paper_allocation_candidates_as_of_time"),
        "paper_allocation_candidates",
        ["as_of_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_allocation_candidates_asset_symbol"),
        "paper_allocation_candidates",
        ["asset_symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_allocation_candidates_calibration_state"),
        "paper_allocation_candidates",
        ["calibration_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_allocation_candidates_forecast_id"),
        "paper_allocation_candidates",
        ["forecast_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_allocation_candidates_workspace_id"),
        "paper_allocation_candidates",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "forecast_scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("forecast_id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_mode", sa.String(length=24), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("scored_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_id"],
            ["research_forecasts.id"],
            name=op.f("fk_forecast_scores_forecast_id_research_forecasts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["forecast_outcome_observations.id"],
            name=op.f("fk_forecast_scores_observation_id_forecast_outcome_observations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_forecast_scores_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_scores")),
        sa.UniqueConstraint("checksum", name=op.f("uq_forecast_scores_checksum")),
        sa.UniqueConstraint("observation_id", name=op.f("uq_forecast_scores_observation_id")),
    )
    op.create_index(
        op.f("ix_forecast_scores_evaluation_mode"),
        "forecast_scores",
        ["evaluation_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_scores_forecast_id"), "forecast_scores", ["forecast_id"], unique=False
    )
    op.create_index(
        op.f("ix_forecast_scores_scored_at"), "forecast_scores", ["scored_at"], unique=False
    )
    op.create_index(
        op.f("ix_forecast_scores_workspace_id"), "forecast_scores", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_forecast_scores_workspace_id"), table_name="forecast_scores")
    op.drop_index(op.f("ix_forecast_scores_scored_at"), table_name="forecast_scores")
    op.drop_index(op.f("ix_forecast_scores_forecast_id"), table_name="forecast_scores")
    op.drop_index(op.f("ix_forecast_scores_evaluation_mode"), table_name="forecast_scores")
    op.drop_table("forecast_scores")
    op.drop_index(
        op.f("ix_paper_allocation_candidates_workspace_id"),
        table_name="paper_allocation_candidates",
    )
    op.drop_index(
        op.f("ix_paper_allocation_candidates_forecast_id"), table_name="paper_allocation_candidates"
    )
    op.drop_index(
        op.f("ix_paper_allocation_candidates_calibration_state"),
        table_name="paper_allocation_candidates",
    )
    op.drop_index(
        op.f("ix_paper_allocation_candidates_asset_symbol"),
        table_name="paper_allocation_candidates",
    )
    op.drop_index(
        op.f("ix_paper_allocation_candidates_as_of_time"), table_name="paper_allocation_candidates"
    )
    op.drop_table("paper_allocation_candidates")
    op.drop_index(
        op.f("ix_forecast_outcome_observations_workspace_id"),
        table_name="forecast_outcome_observations",
    )
    op.drop_index(
        op.f("ix_forecast_outcome_observations_observed_at"),
        table_name="forecast_outcome_observations",
    )
    op.drop_index(
        op.f("ix_forecast_outcome_observations_forecast_id"),
        table_name="forecast_outcome_observations",
    )
    op.drop_table("forecast_outcome_observations")
    op.drop_index(op.f("ix_research_forecasts_workspace_id"), table_name="research_forecasts")
    op.drop_index(
        op.f("ix_research_forecasts_target_definition_id"), table_name="research_forecasts"
    )
    op.drop_index(op.f("ix_research_forecasts_supersedes_id"), table_name="research_forecasts")
    op.drop_index(op.f("ix_research_forecasts_state"), table_name="research_forecasts")
    op.drop_index(op.f("ix_research_forecasts_research_case_id"), table_name="research_forecasts")
    op.drop_index(
        op.f("ix_research_forecasts_outcome_eligible_time"), table_name="research_forecasts"
    )
    op.drop_index(op.f("ix_research_forecasts_forecast_type"), table_name="research_forecasts")
    op.drop_index(op.f("ix_research_forecasts_evaluation_mode"), table_name="research_forecasts")
    op.drop_index(op.f("ix_research_forecasts_dossier_id"), table_name="research_forecasts")
    op.drop_index(op.f("ix_research_forecasts_as_of_time"), table_name="research_forecasts")
    op.drop_index("ix_forecast_workspace_maturity", table_name="research_forecasts")
    op.drop_table("research_forecasts")
    op.drop_index(
        op.f("ix_paper_portfolio_evaluations_workspace_id"),
        table_name="paper_portfolio_evaluations",
    )
    op.drop_index(
        op.f("ix_paper_portfolio_evaluations_plan_id"), table_name="paper_portfolio_evaluations"
    )
    op.drop_index(
        op.f("ix_paper_portfolio_evaluations_evaluated_at"),
        table_name="paper_portfolio_evaluations",
    )
    op.drop_table("paper_portfolio_evaluations")
    op.drop_index(op.f("ix_paper_portfolio_plans_workspace_id"), table_name="paper_portfolio_plans")
    op.drop_index(op.f("ix_paper_portfolio_plans_status"), table_name="paper_portfolio_plans")
    op.drop_index(op.f("ix_paper_portfolio_plans_portfolio_id"), table_name="paper_portfolio_plans")
    op.drop_index(op.f("ix_paper_portfolio_plans_as_of_time"), table_name="paper_portfolio_plans")
    op.drop_table("paper_portfolio_plans")
    op.drop_index(
        op.f("ix_research_reliability_snapshots_workspace_id"),
        table_name="research_reliability_snapshots",
    )
    op.drop_index(
        op.f("ix_research_reliability_snapshots_subject_type"),
        table_name="research_reliability_snapshots",
    )
    op.drop_index(
        op.f("ix_research_reliability_snapshots_subject_key"),
        table_name="research_reliability_snapshots",
    )
    op.drop_index(
        op.f("ix_research_reliability_snapshots_evaluation_mode"),
        table_name="research_reliability_snapshots",
    )
    op.drop_index(
        op.f("ix_research_reliability_snapshots_as_of_time"),
        table_name="research_reliability_snapshots",
    )
    op.drop_table("research_reliability_snapshots")
    op.drop_index(
        op.f("ix_paper_research_eligibility_policies_workspace_id"),
        table_name="paper_research_eligibility_policies",
    )
    op.drop_table("paper_research_eligibility_policies")
    op.drop_index(
        op.f("ix_paper_portfolio_construction_policies_workspace_id"),
        table_name="paper_portfolio_construction_policies",
    )
    op.drop_table("paper_portfolio_construction_policies")
    op.drop_index(
        op.f("ix_forecast_target_definitions_workspace_id"),
        table_name="forecast_target_definitions",
    )
    op.drop_index(
        op.f("ix_forecast_target_definitions_key"), table_name="forecast_target_definitions"
    )
    op.drop_table("forecast_target_definitions")
    op.drop_index(
        op.f("ix_forecast_calibration_analyses_workspace_id"),
        table_name="forecast_calibration_analyses",
    )
    op.drop_index(
        op.f("ix_forecast_calibration_analyses_status"), table_name="forecast_calibration_analyses"
    )
    op.drop_index(
        op.f("ix_forecast_calibration_analyses_evaluation_mode"),
        table_name="forecast_calibration_analyses",
    )
    op.drop_index(
        op.f("ix_forecast_calibration_analyses_as_of_time"),
        table_name="forecast_calibration_analyses",
    )
    op.drop_table("forecast_calibration_analyses")
    op.drop_index(
        op.f("ix_feedback_recommendations_workspace_id"), table_name="feedback_recommendations"
    )
    op.drop_index(
        op.f("ix_feedback_recommendations_subject_type"), table_name="feedback_recommendations"
    )
    op.drop_index(
        op.f("ix_feedback_recommendations_subject_key"), table_name="feedback_recommendations"
    )
    op.drop_index(op.f("ix_feedback_recommendations_status"), table_name="feedback_recommendations")
    op.drop_table("feedback_recommendations")
    # ### end Alembic commands ###
