"""private beta operations reliability

Revision ID: 5595df1fe1cf
Revises: 4e398fc4c9a1
Create Date: 2026-08-15 18:33:38.751650
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import packages.database.types


revision: str = '5595df1fe1cf'
down_revision: Union[str, None] = '4e398fc4c9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_manifests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backup_reference', sa.String(length=240), nullable=False),
    sa.Column('application_version', sa.String(length=24), nullable=False),
    sa.Column('alembic_revision', sa.String(length=32), nullable=False),
    sa.Column('object_store_reference', sa.String(length=240), nullable=True),
    sa.Column('configuration_version', sa.String(length=64), nullable=False),
    sa.Column('checksums', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('verification_state', sa.String(length=24), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_manifests')),
    sa.UniqueConstraint('backup_reference', name=op.f('uq_backup_manifests_backup_reference'))
    )
    op.create_index(op.f('ix_backup_manifests_created_at'), 'backup_manifests', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_manifests_status'), 'backup_manifests', ['status'], unique=False)
    op.create_index(op.f('ix_backup_manifests_verification_state'), 'backup_manifests', ['verification_state'], unique=False)
    op.create_table('scheduler_heartbeats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheduler_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('software_sha', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_heartbeats'))
    )
    op.create_index(op.f('ix_scheduler_heartbeats_last_heartbeat_at'), 'scheduler_heartbeats', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_scheduler_heartbeats_lease_expires_at'), 'scheduler_heartbeats', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_scheduler_heartbeats_scheduler_id'), 'scheduler_heartbeats', ['scheduler_id'], unique=True)
    op.create_index(op.f('ix_scheduler_heartbeats_status'), 'scheduler_heartbeats', ['status'], unique=False)
    op.create_table('maintenance_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('allow_reads', sa.Boolean(), nullable=False),
    sa.Column('activated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('activated_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_user_id'], ['user_profiles.id'], name=op.f('fk_maintenance_states_activated_by_user_id_user_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_states'))
    )
    op.create_index(op.f('ix_maintenance_states_activated_by_user_id'), 'maintenance_states', ['activated_by_user_id'], unique=False)
    op.create_index(op.f('ix_maintenance_states_enabled'), 'maintenance_states', ['enabled'], unique=False)
    op.create_table('provider_circuit_breakers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('opened_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_probe_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error_category', sa.String(length=40), nullable=True),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_circuit_breakers_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_circuit_breakers'))
    )
    op.create_index(op.f('ix_provider_circuit_breakers_next_probe_at'), 'provider_circuit_breakers', ['next_probe_at'], unique=False)
    op.create_index(op.f('ix_provider_circuit_breakers_provider_id'), 'provider_circuit_breakers', ['provider_id'], unique=True)
    op.create_index(op.f('ix_provider_circuit_breakers_state'), 'provider_circuit_breakers', ['state'], unique=False)
    op.create_table('restore_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backup_manifest_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('record_counts', sa.JSON(), nullable=False),
    sa.Column('checksums_match', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('verified_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backup_manifest_id'], ['backup_manifests.id'], name=op.f('fk_restore_verifications_backup_manifest_id_backup_manifests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restore_verifications'))
    )
    op.create_index(op.f('ix_restore_verifications_backup_manifest_id'), 'restore_verifications', ['backup_manifest_id'], unique=False)
    op.create_index(op.f('ix_restore_verifications_status'), 'restore_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_restore_verifications_verified_at'), 'restore_verifications', ['verified_at'], unique=False)
    op.create_table('operational_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('deduplication_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.String(length=240), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('unaffected', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_operational_alerts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_alerts')),
    sa.UniqueConstraint('workspace_id', 'deduplication_key', 'status', name='uq_active_alert')
    )
    op.create_index(op.f('ix_operational_alerts_category'), 'operational_alerts', ['category'], unique=False)
    op.create_index(op.f('ix_operational_alerts_last_seen_at'), 'operational_alerts', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_operational_alerts_severity'), 'operational_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_operational_alerts_status'), 'operational_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_operational_alerts_workspace_id'), 'operational_alerts', ['workspace_id'], unique=False)
    op.create_table('scheduled_task_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(length=24), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('next_due_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_scheduled_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('maximum_runtime_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_policy', sa.JSON(), nullable=False),
    sa.Column('concurrency_policy', sa.JSON(), nullable=False),
    sa.Column('resource_budget', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('maximum_runtime_seconds > 0', name=op.f('ck_scheduled_task_definitions_scheduled_task_runtime_positive')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_scheduled_task_definitions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_task_definitions')),
    sa.UniqueConstraint('workspace_id', 'task_type', 'name', name='uq_scheduled_task_scope')
    )
    op.create_index(op.f('ix_scheduled_task_definitions_enabled'), 'scheduled_task_definitions', ['enabled'], unique=False)
    op.create_index(op.f('ix_scheduled_task_definitions_next_due_at'), 'scheduled_task_definitions', ['next_due_at'], unique=False)
    op.create_index(op.f('ix_scheduled_task_definitions_provider'), 'scheduled_task_definitions', ['provider'], unique=False)
    op.create_index(op.f('ix_scheduled_task_definitions_schedule_type'), 'scheduled_task_definitions', ['schedule_type'], unique=False)
    op.create_index(op.f('ix_scheduled_task_definitions_task_type'), 'scheduled_task_definitions', ['task_type'], unique=False)
    op.create_index(op.f('ix_scheduled_task_definitions_workspace_id'), 'scheduled_task_definitions', ['workspace_id'], unique=False)
    op.create_table('data_freshness_statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('cadence', sa.JSON(), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('calendar', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('last_eligible_update_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('expected_next_update_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('stale_after_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('provider_delayed', sa.Boolean(), nullable=False),
    sa.Column('last_job_id', sa.Uuid(), nullable=True),
    sa.Column('current_error', sa.Text(), nullable=True),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_job_id'], ['import_jobs.id'], name=op.f('fk_data_freshness_statuses_last_job_id_import_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_data_freshness_statuses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_freshness_statuses')),
    sa.UniqueConstraint('workspace_id', 'provider', 'dataset', name='uq_data_freshness_scope')
    )
    op.create_index(op.f('ix_data_freshness_statuses_criticality'), 'data_freshness_statuses', ['criticality'], unique=False)
    op.create_index(op.f('ix_data_freshness_statuses_dataset'), 'data_freshness_statuses', ['dataset'], unique=False)
    op.create_index(op.f('ix_data_freshness_statuses_last_job_id'), 'data_freshness_statuses', ['last_job_id'], unique=False)
    op.create_index(op.f('ix_data_freshness_statuses_provider'), 'data_freshness_statuses', ['provider'], unique=False)
    op.create_index(op.f('ix_data_freshness_statuses_stale_after_at'), 'data_freshness_statuses', ['stale_after_at'], unique=False)
    op.create_index(op.f('ix_data_freshness_statuses_status'), 'data_freshness_statuses', ['status'], unique=False)
    op.create_index(op.f('ix_data_freshness_statuses_workspace_id'), 'data_freshness_statuses', ['workspace_id'], unique=False)
    op.create_table('scheduled_task_occurrences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_for', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('claimed_by', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error_category', sa.String(length=40), nullable=True),
    sa.Column('sanitized_error', sa.Text(), nullable=True),
    sa.Column('result_manifest', sa.JSON(), nullable=False),
    sa.Column('resource_usage', sa.JSON(), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['scheduled_task_definitions.id'], name='fk_task_occurrence_definition', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_scheduled_task_occurrences_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_task_occurrences')),
    sa.UniqueConstraint('definition_id', 'scheduled_for', name='uq_scheduled_task_occurrence'),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_scheduled_task_occurrences_idempotency_key'))
    )
    op.create_index(op.f('ix_scheduled_task_occurrences_claimed_by'), 'scheduled_task_occurrences', ['claimed_by'], unique=False)
    op.create_index(op.f('ix_scheduled_task_occurrences_definition_id'), 'scheduled_task_occurrences', ['definition_id'], unique=False)
    op.create_index(op.f('ix_scheduled_task_occurrences_error_category'), 'scheduled_task_occurrences', ['error_category'], unique=False)
    op.create_index(op.f('ix_scheduled_task_occurrences_lease_expires_at'), 'scheduled_task_occurrences', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_scheduled_task_occurrences_next_retry_at'), 'scheduled_task_occurrences', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_scheduled_task_occurrences_scheduled_for'), 'scheduled_task_occurrences', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_task_occurrences_status'), 'scheduled_task_occurrences', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_task_occurrences_workspace_id'), 'scheduled_task_occurrences', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_task_occurrences_workspace_id'), table_name='scheduled_task_occurrences')
    op.drop_index(op.f('ix_scheduled_task_occurrences_status'), table_name='scheduled_task_occurrences')
    op.drop_index(op.f('ix_scheduled_task_occurrences_scheduled_for'), table_name='scheduled_task_occurrences')
    op.drop_index(op.f('ix_scheduled_task_occurrences_next_retry_at'), table_name='scheduled_task_occurrences')
    op.drop_index(op.f('ix_scheduled_task_occurrences_lease_expires_at'), table_name='scheduled_task_occurrences')
    op.drop_index(op.f('ix_scheduled_task_occurrences_error_category'), table_name='scheduled_task_occurrences')
    op.drop_index(op.f('ix_scheduled_task_occurrences_definition_id'), table_name='scheduled_task_occurrences')
    op.drop_index(op.f('ix_scheduled_task_occurrences_claimed_by'), table_name='scheduled_task_occurrences')
    op.drop_table('scheduled_task_occurrences')
    op.drop_index(op.f('ix_data_freshness_statuses_workspace_id'), table_name='data_freshness_statuses')
    op.drop_index(op.f('ix_data_freshness_statuses_status'), table_name='data_freshness_statuses')
    op.drop_index(op.f('ix_data_freshness_statuses_stale_after_at'), table_name='data_freshness_statuses')
    op.drop_index(op.f('ix_data_freshness_statuses_provider'), table_name='data_freshness_statuses')
    op.drop_index(op.f('ix_data_freshness_statuses_last_job_id'), table_name='data_freshness_statuses')
    op.drop_index(op.f('ix_data_freshness_statuses_dataset'), table_name='data_freshness_statuses')
    op.drop_index(op.f('ix_data_freshness_statuses_criticality'), table_name='data_freshness_statuses')
    op.drop_table('data_freshness_statuses')
    op.drop_index(op.f('ix_scheduled_task_definitions_workspace_id'), table_name='scheduled_task_definitions')
    op.drop_index(op.f('ix_scheduled_task_definitions_task_type'), table_name='scheduled_task_definitions')
    op.drop_index(op.f('ix_scheduled_task_definitions_schedule_type'), table_name='scheduled_task_definitions')
    op.drop_index(op.f('ix_scheduled_task_definitions_provider'), table_name='scheduled_task_definitions')
    op.drop_index(op.f('ix_scheduled_task_definitions_next_due_at'), table_name='scheduled_task_definitions')
    op.drop_index(op.f('ix_scheduled_task_definitions_enabled'), table_name='scheduled_task_definitions')
    op.drop_table('scheduled_task_definitions')
    op.drop_index(op.f('ix_operational_alerts_workspace_id'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_status'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_severity'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_last_seen_at'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_category'), table_name='operational_alerts')
    op.drop_table('operational_alerts')
    op.drop_index(op.f('ix_restore_verifications_verified_at'), table_name='restore_verifications')
    op.drop_index(op.f('ix_restore_verifications_status'), table_name='restore_verifications')
    op.drop_index(op.f('ix_restore_verifications_backup_manifest_id'), table_name='restore_verifications')
    op.drop_table('restore_verifications')
    op.drop_index(op.f('ix_provider_circuit_breakers_state'), table_name='provider_circuit_breakers')
    op.drop_index(op.f('ix_provider_circuit_breakers_provider_id'), table_name='provider_circuit_breakers')
    op.drop_index(op.f('ix_provider_circuit_breakers_next_probe_at'), table_name='provider_circuit_breakers')
    op.drop_table('provider_circuit_breakers')
    op.drop_index(op.f('ix_maintenance_states_enabled'), table_name='maintenance_states')
    op.drop_index(op.f('ix_maintenance_states_activated_by_user_id'), table_name='maintenance_states')
    op.drop_table('maintenance_states')
    op.drop_index(op.f('ix_scheduler_heartbeats_status'), table_name='scheduler_heartbeats')
    op.drop_index(op.f('ix_scheduler_heartbeats_scheduler_id'), table_name='scheduler_heartbeats')
    op.drop_index(op.f('ix_scheduler_heartbeats_lease_expires_at'), table_name='scheduler_heartbeats')
    op.drop_index(op.f('ix_scheduler_heartbeats_last_heartbeat_at'), table_name='scheduler_heartbeats')
    op.drop_table('scheduler_heartbeats')
    op.drop_index(op.f('ix_backup_manifests_verification_state'), table_name='backup_manifests')
    op.drop_index(op.f('ix_backup_manifests_status'), table_name='backup_manifests')
    op.drop_index(op.f('ix_backup_manifests_created_at'), table_name='backup_manifests')
    op.drop_table('backup_manifests')
    # ### end Alembic commands ###
