"""economic driver graph and relevance router

Revision ID: 61293cddc2e2
Revises: 7f4af62df2fe
Create Date: 2026-08-08 00:18:59.886949
"""
from typing import Sequence, Union

from alembic import op
import packages.database.types
import sqlalchemy as sa


revision: str = '61293cddc2e2'
down_revision: Union[str, None] = '7f4af62df2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('valid_from', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('first_seen', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_verified', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('event_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('observation_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('publication_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('retrieval_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revision_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('time_precision', sa.String(length=24), nullable=False),
    sa.Column('source_time_zone', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('source_manifest_id', sa.Uuid(), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('candidate','verified','disputed','expired','rejected')", name=op.f('ck_economic_entities_economic_entity_status_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_economic_entities_economic_entity_confidence_range')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_economic_entities_economic_entity_valid_range')),
    sa.ForeignKeyConstraint(['source_manifest_id'], ['data_manifests.id'], name=op.f('fk_economic_entities_source_manifest_id_data_manifests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_economic_entities_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_economic_entities')),
    sa.UniqueConstraint('workspace_id', 'entity_type', 'normalized_name', name='uq_economic_entity_identity')
    )
    op.create_index(op.f('ix_economic_entities_canonical_name'), 'economic_entities', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_economic_entities_entity_type'), 'economic_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_economic_entities_last_verified'), 'economic_entities', ['last_verified'], unique=False)
    op.create_index(op.f('ix_economic_entities_simulation_eligible_time'), 'economic_entities', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_economic_entities_source_manifest_id'), 'economic_entities', ['source_manifest_id'], unique=False)
    op.create_index(op.f('ix_economic_entities_status'), 'economic_entities', ['status'], unique=False)
    op.create_index(op.f('ix_economic_entities_valid_from'), 'economic_entities', ['valid_from'], unique=False)
    op.create_index(op.f('ix_economic_entities_valid_to'), 'economic_entities', ['valid_to'], unique=False)
    op.create_index(op.f('ix_economic_entities_workspace_id'), 'economic_entities', ['workspace_id'], unique=False)
    op.create_index('ix_economic_entity_workspace_eligible', 'economic_entities', ['workspace_id', 'simulation_eligible_time'], unique=False)
    op.create_index('ix_economic_entity_workspace_type_status', 'economic_entities', ['workspace_id', 'entity_type', 'status'], unique=False)
    op.create_table('company_driver_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('prior_version', sa.String(length=40), nullable=False),
    sa.Column('generated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('trigger_reason', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['company_entity_id'], ['economic_entities.id'], name=op.f('fk_company_driver_profiles_company_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_company_driver_profiles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_driver_profiles')),
    sa.UniqueConstraint('workspace_id', 'company_entity_id', 'version', name='uq_company_driver_profile_version')
    )
    op.create_index('ix_company_driver_profile_latest', 'company_driver_profiles', ['workspace_id', 'company_entity_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_company_driver_profiles_company_entity_id'), 'company_driver_profiles', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_company_driver_profiles_simulation_eligible_time'), 'company_driver_profiles', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_company_driver_profiles_workspace_id'), 'company_driver_profiles', ['workspace_id'], unique=False)
    op.create_table('economic_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('subject_entity_id', sa.Uuid(), nullable=False),
    sa.Column('predicate', sa.String(length=48), nullable=False),
    sa.Column('object_entity_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('strength', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('valid_from', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('method_version', sa.String(length=40), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.CheckConstraint("status IN ('candidate','verified','disputed','expired','rejected')", name=op.f('ck_economic_relationships_economic_relationship_status_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_economic_relationships_confidence_range')),
    sa.CheckConstraint('strength IS NULL OR (strength >= 0 AND strength <= 1)', name=op.f('ck_economic_relationships_economic_relationship_strength_range')),
    sa.CheckConstraint('subject_entity_id <> object_entity_id', name=op.f('ck_economic_relationships_economic_relationship_not_self')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_economic_relationships_economic_relationship_valid_range')),
    sa.ForeignKeyConstraint(['object_entity_id'], ['economic_entities.id'], name=op.f('fk_economic_relationships_object_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['economic_entities.id'], name=op.f('fk_economic_relationships_subject_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_economic_relationships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_economic_relationships')),
    sa.UniqueConstraint('workspace_id', 'subject_entity_id', 'predicate', 'object_entity_id', 'valid_from', name='uq_economic_relationship_version')
    )
    op.create_index('ix_economic_relationship_inbound', 'economic_relationships', ['workspace_id', 'object_entity_id', 'status', 'simulation_eligible_time'], unique=False)
    op.create_index('ix_economic_relationship_outbound', 'economic_relationships', ['workspace_id', 'subject_entity_id', 'status', 'simulation_eligible_time'], unique=False)
    op.create_index('ix_economic_relationship_predicate_subject', 'economic_relationships', ['workspace_id', 'predicate', 'subject_entity_id'], unique=False)
    op.create_index(op.f('ix_economic_relationships_last_verified_at'), 'economic_relationships', ['last_verified_at'], unique=False)
    op.create_index(op.f('ix_economic_relationships_object_entity_id'), 'economic_relationships', ['object_entity_id'], unique=False)
    op.create_index(op.f('ix_economic_relationships_predicate'), 'economic_relationships', ['predicate'], unique=False)
    op.create_index(op.f('ix_economic_relationships_simulation_eligible_time'), 'economic_relationships', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_economic_relationships_status'), 'economic_relationships', ['status'], unique=False)
    op.create_index(op.f('ix_economic_relationships_subject_entity_id'), 'economic_relationships', ['subject_entity_id'], unique=False)
    op.create_index(op.f('ix_economic_relationships_valid_from'), 'economic_relationships', ['valid_from'], unique=False)
    op.create_index(op.f('ix_economic_relationships_valid_to'), 'economic_relationships', ['valid_to'], unique=False)
    op.create_index(op.f('ix_economic_relationships_workspace_id'), 'economic_relationships', ['workspace_id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.Column('normalized_alias', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('valid_from', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['economic_entities.id'], name=op.f('fk_entity_aliases_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_entity_aliases_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_aliases')),
    sa.UniqueConstraint('entity_id', 'normalized_alias', name='uq_entity_alias_entity_value')
    )
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_normalized_alias'), 'entity_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_entity_aliases_simulation_eligible_time'), 'entity_aliases', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_entity_aliases_workspace_id'), 'entity_aliases', ['workspace_id'], unique=False)
    op.create_table('entity_identifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(length=48), nullable=False),
    sa.Column('value', sa.String(length=240), nullable=False),
    sa.Column('normalized_value', sa.String(length=240), nullable=False),
    sa.Column('mapping_method', sa.String(length=48), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('evidence_reference', sa.String(length=700), nullable=True),
    sa.Column('resolver_version', sa.String(length=40), nullable=False),
    sa.Column('resolved_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_from', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_entity_identifiers_entity_identifier_confidence_range')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_entity_identifiers_entity_identifier_valid_range')),
    sa.ForeignKeyConstraint(['entity_id'], ['economic_entities.id'], name=op.f('fk_entity_identifiers_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_entity_identifiers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_identifiers')),
    sa.UniqueConstraint('workspace_id', 'namespace', 'normalized_value', name='uq_entity_identifier_value')
    )
    op.create_index('ix_entity_identifier_entity_namespace', 'entity_identifiers', ['entity_id', 'namespace'], unique=False)
    op.create_index(op.f('ix_entity_identifiers_entity_id'), 'entity_identifiers', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_identifiers_namespace'), 'entity_identifiers', ['namespace'], unique=False)
    op.create_index(op.f('ix_entity_identifiers_normalized_value'), 'entity_identifiers', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_entity_identifiers_simulation_eligible_time'), 'entity_identifiers', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_entity_identifiers_workspace_id'), 'entity_identifiers', ['workspace_id'], unique=False)
    op.create_table('entity_resolution_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(length=48), nullable=False),
    sa.Column('value', sa.String(length=240), nullable=False),
    sa.Column('normalized_value', sa.String(length=240), nullable=False),
    sa.Column('candidate_entity_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=48), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('resolver_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resolved_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_from', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('candidate','confirmed','rejected','ambiguous')", name=op.f('ck_entity_resolution_candidates_status_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_entity_resolution_candidates_confidence_range')),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['economic_entities.id'], name=op.f('fk_entity_resolution_candidates_candidate_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_entity_resolution_candidates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_resolution_candidates')),
    sa.UniqueConstraint('workspace_id', 'namespace', 'normalized_value', 'candidate_entity_id', name='uq_resolution_candidate_mapping')
    )
    op.create_index(op.f('ix_entity_resolution_candidates_candidate_entity_id'), 'entity_resolution_candidates', ['candidate_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_resolution_candidates_namespace'), 'entity_resolution_candidates', ['namespace'], unique=False)
    op.create_index(op.f('ix_entity_resolution_candidates_normalized_value'), 'entity_resolution_candidates', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_entity_resolution_candidates_simulation_eligible_time'), 'entity_resolution_candidates', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_entity_resolution_candidates_status'), 'entity_resolution_candidates', ['status'], unique=False)
    op.create_index(op.f('ix_entity_resolution_candidates_workspace_id'), 'entity_resolution_candidates', ['workspace_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_manifest_id', sa.Uuid(), nullable=True),
    sa.Column('sec_filing_id', sa.Uuid(), nullable=True),
    sa.Column('source_record_identifier', sa.String(length=300), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=True),
    sa.Column('publication_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('structured_payload', sa.JSON(), nullable=False),
    sa.Column('content_reference', sa.String(length=700), nullable=True),
    sa.Column('supporting_text', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_evidence_records_evidence_confidence_range')),
    sa.ForeignKeyConstraint(['sec_filing_id'], ['sec_filings.id'], name=op.f('fk_evidence_records_sec_filing_id_sec_filings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['economic_entities.id'], name=op.f('fk_evidence_records_source_entity_id_economic_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_manifest_id'], ['data_manifests.id'], name=op.f('fk_evidence_records_source_manifest_id_data_manifests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_evidence_records_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_records')),
    sa.UniqueConstraint('workspace_id', 'checksum', 'source_record_identifier', name='uq_evidence_source')
    )
    op.create_index(op.f('ix_evidence_records_checksum'), 'evidence_records', ['checksum'], unique=False)
    op.create_index(op.f('ix_evidence_records_evidence_type'), 'evidence_records', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_records_sec_filing_id'), 'evidence_records', ['sec_filing_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_simulation_eligible_time'), 'evidence_records', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_evidence_records_source_entity_id'), 'evidence_records', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_source_manifest_id'), 'evidence_records', ['source_manifest_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_source_record_identifier'), 'evidence_records', ['source_record_identifier'], unique=False)
    op.create_index(op.f('ix_evidence_records_workspace_id'), 'evidence_records', ['workspace_id'], unique=False)
    op.create_index('ix_evidence_workspace_eligible', 'evidence_records', ['workspace_id', 'simulation_eligible_time'], unique=False)
    op.create_table('graph_recompute_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('requested_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','cancelled')", name=op.f('ck_graph_recompute_jobs_graph_recompute_status_valid')),
    sa.ForeignKeyConstraint(['company_entity_id'], ['economic_entities.id'], name=op.f('fk_graph_recompute_jobs_company_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_graph_recompute_jobs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_recompute_jobs')),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_graph_recompute_workspace_key')
    )
    op.create_index(op.f('ix_graph_recompute_jobs_company_entity_id'), 'graph_recompute_jobs', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_graph_recompute_jobs_requested_at'), 'graph_recompute_jobs', ['requested_at'], unique=False)
    op.create_index(op.f('ix_graph_recompute_jobs_status'), 'graph_recompute_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_graph_recompute_jobs_workspace_id'), 'graph_recompute_jobs', ['workspace_id'], unique=False)
    op.create_table('company_driver_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('driver_category', sa.String(length=48), nullable=False),
    sa.Column('linked_entity_ids', sa.JSON(), nullable=False),
    sa.Column('supporting_relationship_ids', sa.JSON(), nullable=False),
    sa.Column('prior_relevance', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('evidence_relevance', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('historical_evidence_relevance', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('user_override', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('effective_relevance', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_company_driver_entries_driver_confidence_range')),
    sa.CheckConstraint('effective_relevance >= 0 AND effective_relevance <= 1', name=op.f('ck_company_driver_entries_driver_effective_range')),
    sa.CheckConstraint('evidence_relevance >= 0 AND evidence_relevance <= 1', name=op.f('ck_company_driver_entries_driver_evidence_range')),
    sa.CheckConstraint('prior_relevance >= 0 AND prior_relevance <= 1', name=op.f('ck_company_driver_entries_driver_prior_range')),
    sa.ForeignKeyConstraint(['profile_id'], ['company_driver_profiles.id'], name=op.f('fk_company_driver_entries_profile_id_company_driver_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_company_driver_entries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_driver_entries')),
    sa.UniqueConstraint('profile_id', 'driver_category', name='uq_driver_entry_profile_category')
    )
    op.create_index(op.f('ix_company_driver_entries_driver_category'), 'company_driver_entries', ['driver_category'], unique=False)
    op.create_index(op.f('ix_company_driver_entries_effective_relevance'), 'company_driver_entries', ['effective_relevance'], unique=False)
    op.create_index(op.f('ix_company_driver_entries_profile_id'), 'company_driver_entries', ['profile_id'], unique=False)
    op.create_index(op.f('ix_company_driver_entries_workspace_id'), 'company_driver_entries', ['workspace_id'], unique=False)
    op.create_index('ix_driver_entry_profile_relevance', 'company_driver_entries', ['profile_id', 'effective_relevance'], unique=False)
    op.create_table('data_relevance_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('supporting_graph_paths', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('router_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('PROCESS','DEFER','IGNORE','REVIEW')", name=op.f('ck_data_relevance_decisions_data_relevance_decision_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_data_relevance_decisions_route_confidence_range')),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name=op.f('ck_data_relevance_decisions_route_score_range')),
    sa.ForeignKeyConstraint(['company_entity_id'], ['economic_entities.id'], name=op.f('fk_data_relevance_decisions_company_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['company_driver_profiles.id'], name=op.f('fk_data_relevance_decisions_profile_id_company_driver_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_data_relevance_decisions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_relevance_decisions')),
    sa.UniqueConstraint('profile_id', 'dataset_id', 'router_version', name='uq_data_relevance_version')
    )
    op.create_index('ix_data_relevance_company_created', 'data_relevance_decisions', ['company_entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_data_relevance_decisions_company_entity_id'), 'data_relevance_decisions', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_data_relevance_decisions_dataset_id'), 'data_relevance_decisions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_data_relevance_decisions_decision'), 'data_relevance_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_data_relevance_decisions_profile_id'), 'data_relevance_decisions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_data_relevance_decisions_workspace_id'), 'data_relevance_decisions', ['workspace_id'], unique=False)
    op.create_table('entity_resolution_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('decided_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('confirmed','rejected')", name=op.f('ck_entity_resolution_decisions_resolution_decision_value_valid')),
    sa.ForeignKeyConstraint(['candidate_id'], ['entity_resolution_candidates.id'], name=op.f('fk_entity_resolution_decisions_candidate_id_entity_resolution_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['user_profiles.id'], name=op.f('fk_entity_resolution_decisions_decided_by_user_id_user_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_entity_resolution_decisions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_resolution_decisions')),
    sa.UniqueConstraint('candidate_id', name='uq_resolution_decision_candidate')
    )
    op.create_index(op.f('ix_entity_resolution_decisions_candidate_id'), 'entity_resolution_decisions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_entity_resolution_decisions_decided_by_user_id'), 'entity_resolution_decisions', ['decided_by_user_id'], unique=False)
    op.create_index(op.f('ix_entity_resolution_decisions_workspace_id'), 'entity_resolution_decisions', ['workspace_id'], unique=False)
    op.create_table('graph_quality_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('relationship_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detected_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("issue_type IN ('orphan_entity','duplicate_candidate','ambiguous_identifier','expired_relationship','missing_evidence','conflicting_evidence','low_confidence','stale_verification','temporal_inconsistency','cycle_anomaly')", name=op.f('ck_graph_quality_issues_graph_quality_issue_type_valid')),
    sa.CheckConstraint("status IN ('open','acknowledged','resolved')", name=op.f('ck_graph_quality_issues_graph_quality_status_valid')),
    sa.ForeignKeyConstraint(['entity_id'], ['economic_entities.id'], name=op.f('fk_graph_quality_issues_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['economic_relationships.id'], name=op.f('fk_graph_quality_issues_relationship_id_economic_relationships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_graph_quality_issues_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_quality_issues'))
    )
    op.create_index(op.f('ix_graph_quality_issues_entity_id'), 'graph_quality_issues', ['entity_id'], unique=False)
    op.create_index(op.f('ix_graph_quality_issues_issue_type'), 'graph_quality_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_graph_quality_issues_relationship_id'), 'graph_quality_issues', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_graph_quality_issues_status'), 'graph_quality_issues', ['status'], unique=False)
    op.create_index(op.f('ix_graph_quality_issues_workspace_id'), 'graph_quality_issues', ['workspace_id'], unique=False)
    op.create_table('relationship_confidence_components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_id', sa.Uuid(), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('component', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.CheckConstraint('value >= 0 AND value <= 1', name=op.f('ck_relationship_confidence_components_component_range')),
    sa.ForeignKeyConstraint(['relationship_id'], ['economic_relationships.id'], name=op.f('fk_relationship_confidence_components_relationship_id_economic_relationships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_relationship_confidence_components_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_confidence_components')),
    sa.UniqueConstraint('relationship_id', 'formula_version', 'component', name='uq_relationship_confidence')
    )
    op.create_index(op.f('ix_relationship_confidence_components_relationship_id'), 'relationship_confidence_components', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_relationship_confidence_components_workspace_id'), 'relationship_confidence_components', ['workspace_id'], unique=False)
    op.create_table('relationship_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=24), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.CheckConstraint("direction IN ('supporting','contradicting')", name=op.f('ck_relationship_evidence_relationship_evidence_direction')),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name=op.f('ck_relationship_evidence_relationship_evidence_weight_range')),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_records.id'], name=op.f('fk_relationship_evidence_evidence_id_evidence_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['economic_relationships.id'], name=op.f('fk_relationship_evidence_relationship_id_economic_relationships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_relationship_evidence_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_evidence')),
    sa.UniqueConstraint('relationship_id', 'evidence_id', 'direction', name='uq_relationship_evidence_link')
    )
    op.create_index(op.f('ix_relationship_evidence_evidence_id'), 'relationship_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_relationship_id'), 'relationship_evidence', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_workspace_id'), 'relationship_evidence', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_evidence_workspace_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_relationship_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_evidence_id'), table_name='relationship_evidence')
    op.drop_table('relationship_evidence')
    op.drop_index(op.f('ix_relationship_confidence_components_workspace_id'), table_name='relationship_confidence_components')
    op.drop_index(op.f('ix_relationship_confidence_components_relationship_id'), table_name='relationship_confidence_components')
    op.drop_table('relationship_confidence_components')
    op.drop_index(op.f('ix_graph_quality_issues_workspace_id'), table_name='graph_quality_issues')
    op.drop_index(op.f('ix_graph_quality_issues_status'), table_name='graph_quality_issues')
    op.drop_index(op.f('ix_graph_quality_issues_relationship_id'), table_name='graph_quality_issues')
    op.drop_index(op.f('ix_graph_quality_issues_issue_type'), table_name='graph_quality_issues')
    op.drop_index(op.f('ix_graph_quality_issues_entity_id'), table_name='graph_quality_issues')
    op.drop_table('graph_quality_issues')
    op.drop_index(op.f('ix_entity_resolution_decisions_workspace_id'), table_name='entity_resolution_decisions')
    op.drop_index(op.f('ix_entity_resolution_decisions_decided_by_user_id'), table_name='entity_resolution_decisions')
    op.drop_index(op.f('ix_entity_resolution_decisions_candidate_id'), table_name='entity_resolution_decisions')
    op.drop_table('entity_resolution_decisions')
    op.drop_index(op.f('ix_data_relevance_decisions_workspace_id'), table_name='data_relevance_decisions')
    op.drop_index(op.f('ix_data_relevance_decisions_profile_id'), table_name='data_relevance_decisions')
    op.drop_index(op.f('ix_data_relevance_decisions_decision'), table_name='data_relevance_decisions')
    op.drop_index(op.f('ix_data_relevance_decisions_dataset_id'), table_name='data_relevance_decisions')
    op.drop_index(op.f('ix_data_relevance_decisions_company_entity_id'), table_name='data_relevance_decisions')
    op.drop_index('ix_data_relevance_company_created', table_name='data_relevance_decisions')
    op.drop_table('data_relevance_decisions')
    op.drop_index('ix_driver_entry_profile_relevance', table_name='company_driver_entries')
    op.drop_index(op.f('ix_company_driver_entries_workspace_id'), table_name='company_driver_entries')
    op.drop_index(op.f('ix_company_driver_entries_profile_id'), table_name='company_driver_entries')
    op.drop_index(op.f('ix_company_driver_entries_effective_relevance'), table_name='company_driver_entries')
    op.drop_index(op.f('ix_company_driver_entries_driver_category'), table_name='company_driver_entries')
    op.drop_table('company_driver_entries')
    op.drop_index(op.f('ix_graph_recompute_jobs_workspace_id'), table_name='graph_recompute_jobs')
    op.drop_index(op.f('ix_graph_recompute_jobs_status'), table_name='graph_recompute_jobs')
    op.drop_index(op.f('ix_graph_recompute_jobs_requested_at'), table_name='graph_recompute_jobs')
    op.drop_index(op.f('ix_graph_recompute_jobs_company_entity_id'), table_name='graph_recompute_jobs')
    op.drop_table('graph_recompute_jobs')
    op.drop_index('ix_evidence_workspace_eligible', table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_workspace_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_source_record_identifier'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_source_manifest_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_source_entity_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_simulation_eligible_time'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_sec_filing_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_evidence_type'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_checksum'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_entity_resolution_candidates_workspace_id'), table_name='entity_resolution_candidates')
    op.drop_index(op.f('ix_entity_resolution_candidates_status'), table_name='entity_resolution_candidates')
    op.drop_index(op.f('ix_entity_resolution_candidates_simulation_eligible_time'), table_name='entity_resolution_candidates')
    op.drop_index(op.f('ix_entity_resolution_candidates_normalized_value'), table_name='entity_resolution_candidates')
    op.drop_index(op.f('ix_entity_resolution_candidates_namespace'), table_name='entity_resolution_candidates')
    op.drop_index(op.f('ix_entity_resolution_candidates_candidate_entity_id'), table_name='entity_resolution_candidates')
    op.drop_table('entity_resolution_candidates')
    op.drop_index(op.f('ix_entity_identifiers_workspace_id'), table_name='entity_identifiers')
    op.drop_index(op.f('ix_entity_identifiers_simulation_eligible_time'), table_name='entity_identifiers')
    op.drop_index(op.f('ix_entity_identifiers_normalized_value'), table_name='entity_identifiers')
    op.drop_index(op.f('ix_entity_identifiers_namespace'), table_name='entity_identifiers')
    op.drop_index(op.f('ix_entity_identifiers_entity_id'), table_name='entity_identifiers')
    op.drop_index('ix_entity_identifier_entity_namespace', table_name='entity_identifiers')
    op.drop_table('entity_identifiers')
    op.drop_index(op.f('ix_entity_aliases_workspace_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_simulation_eligible_time'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_normalized_alias'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_economic_relationships_workspace_id'), table_name='economic_relationships')
    op.drop_index(op.f('ix_economic_relationships_valid_to'), table_name='economic_relationships')
    op.drop_index(op.f('ix_economic_relationships_valid_from'), table_name='economic_relationships')
    op.drop_index(op.f('ix_economic_relationships_subject_entity_id'), table_name='economic_relationships')
    op.drop_index(op.f('ix_economic_relationships_status'), table_name='economic_relationships')
    op.drop_index(op.f('ix_economic_relationships_simulation_eligible_time'), table_name='economic_relationships')
    op.drop_index(op.f('ix_economic_relationships_predicate'), table_name='economic_relationships')
    op.drop_index(op.f('ix_economic_relationships_object_entity_id'), table_name='economic_relationships')
    op.drop_index(op.f('ix_economic_relationships_last_verified_at'), table_name='economic_relationships')
    op.drop_index('ix_economic_relationship_predicate_subject', table_name='economic_relationships')
    op.drop_index('ix_economic_relationship_outbound', table_name='economic_relationships')
    op.drop_index('ix_economic_relationship_inbound', table_name='economic_relationships')
    op.drop_table('economic_relationships')
    op.drop_index(op.f('ix_company_driver_profiles_workspace_id'), table_name='company_driver_profiles')
    op.drop_index(op.f('ix_company_driver_profiles_simulation_eligible_time'), table_name='company_driver_profiles')
    op.drop_index(op.f('ix_company_driver_profiles_company_entity_id'), table_name='company_driver_profiles')
    op.drop_index('ix_company_driver_profile_latest', table_name='company_driver_profiles')
    op.drop_table('company_driver_profiles')
    op.drop_index('ix_economic_entity_workspace_type_status', table_name='economic_entities')
    op.drop_index('ix_economic_entity_workspace_eligible', table_name='economic_entities')
    op.drop_index(op.f('ix_economic_entities_workspace_id'), table_name='economic_entities')
    op.drop_index(op.f('ix_economic_entities_valid_to'), table_name='economic_entities')
    op.drop_index(op.f('ix_economic_entities_valid_from'), table_name='economic_entities')
    op.drop_index(op.f('ix_economic_entities_status'), table_name='economic_entities')
    op.drop_index(op.f('ix_economic_entities_source_manifest_id'), table_name='economic_entities')
    op.drop_index(op.f('ix_economic_entities_simulation_eligible_time'), table_name='economic_entities')
    op.drop_index(op.f('ix_economic_entities_last_verified'), table_name='economic_entities')
    op.drop_index(op.f('ix_economic_entities_entity_type'), table_name='economic_entities')
    op.drop_index(op.f('ix_economic_entities_canonical_name'), table_name='economic_entities')
    op.drop_table('economic_entities')
    # ### end Alembic commands ###
