"""upstream integrations and SEC intelligence

Revision ID: 6b8d9e0f1a2b
Revises: 4a2523700bdb
Create Date: 2026-07-30 22:40:58.514366
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from packages.database.types import UTCDateTime

revision: str = "6b8d9e0f1a2b"
down_revision: str | None = "4a2523700bdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APPLICATION_TABLES = (
    "analytics_comparison_records",
    "external_engine_runs",
    "optimization_experiments",
    "sec_companies",
    "sec_documents",
    "sec_facts",
    "sec_filings",
    "sec_ingestion_jobs",
    "sec_insider_transactions",
    "sec_institutional_holdings",
    "sec_parse_results",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sec_companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('tickers', sa.JSON(), nullable=False),
    sa.Column('sic', sa.String(length=8), nullable=True),
    sa.Column('submissions_url', sa.String(length=500), nullable=False),
    sa.Column('facts_url', sa.String(length=500), nullable=False),
    sa.Column('retrieved_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sec_companies'))
    )
    op.create_index(op.f('ix_sec_companies_cik'), 'sec_companies', ['cik'], unique=True)
    op.create_index(op.f('ix_sec_companies_name'), 'sec_companies', ['name'], unique=False)
    op.create_index(op.f('ix_sec_companies_source_checksum'), 'sec_companies', ['source_checksum'], unique=False)
    op.create_table('sec_filings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('accession_number', sa.String(length=24), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('accepted_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('reporting_period', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=700), nullable=False),
    sa.Column('retrieved_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=False),
    sa.Column('raw_document_reference', sa.String(length=500), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('edgartools_version', sa.String(length=40), nullable=False),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('simulation_eligible_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['sec_companies.id'], name=op.f('fk_sec_filings_company_id_sec_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sec_filings'))
    )
    op.create_index(op.f('ix_sec_filings_accepted_at'), 'sec_filings', ['accepted_at'], unique=False)
    op.create_index(op.f('ix_sec_filings_accession_number'), 'sec_filings', ['accession_number'], unique=True)
    op.create_index(op.f('ix_sec_filings_company_id'), 'sec_filings', ['company_id'], unique=False)
    op.create_index(op.f('ix_sec_filings_content_checksum'), 'sec_filings', ['content_checksum'], unique=False)
    op.create_index(op.f('ix_sec_filings_filing_date'), 'sec_filings', ['filing_date'], unique=False)
    op.create_index(op.f('ix_sec_filings_form_type'), 'sec_filings', ['form_type'], unique=False)
    op.create_index(op.f('ix_sec_filings_is_amendment'), 'sec_filings', ['is_amendment'], unique=False)
    op.create_index(op.f('ix_sec_filings_simulation_eligible_at'), 'sec_filings', ['simulation_eligible_at'], unique=False)
    op.create_table('analytics_comparison_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('return_series_checksum', sa.String(length=64), nullable=False),
    sa.Column('benchmark', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('canonical_metrics', sa.JSON(), nullable=False),
    sa.Column('adapter_metrics', sa.JSON(), nullable=False),
    sa.Column('reconciliation', sa.JSON(), nullable=False),
    sa.Column('methodology_notes', sa.JSON(), nullable=False),
    sa.Column('engine_versions', sa.JSON(), nullable=False),
    sa.Column('agreement_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_analytics_comparison_records_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_comparison_records'))
    )
    op.create_index(op.f('ix_analytics_comparison_records_agreement_status'), 'analytics_comparison_records', ['agreement_status'], unique=False)
    op.create_index(op.f('ix_analytics_comparison_records_return_series_checksum'), 'analytics_comparison_records', ['return_series_checksum'], unique=False)
    op.create_index(op.f('ix_analytics_comparison_records_workspace_id'), 'analytics_comparison_records', ['workspace_id'], unique=False)
    op.create_table('external_engine_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('engine', sa.String(length=40), nullable=False),
    sa.Column('engine_version', sa.String(length=80), nullable=False),
    sa.Column('engine_commit', sa.String(length=64), nullable=True),
    sa.Column('request_checksum', sa.String(length=64), nullable=False),
    sa.Column('request_manifest', sa.JSON(), nullable=False),
    sa.Column('result_manifest', sa.JSON(), nullable=False),
    sa.Column('comparison', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_external_engine_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_engine_runs'))
    )
    op.create_index(op.f('ix_external_engine_runs_engine'), 'external_engine_runs', ['engine'], unique=False)
    op.create_index(op.f('ix_external_engine_runs_request_checksum'), 'external_engine_runs', ['request_checksum'], unique=False)
    op.create_index(op.f('ix_external_engine_runs_status'), 'external_engine_runs', ['status'], unique=False)
    op.create_index(op.f('ix_external_engine_runs_workspace_id'), 'external_engine_runs', ['workspace_id'], unique=False)
    op.create_table('optimization_experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=48), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('asset_universe', sa.JSON(), nullable=False),
    sa.Column('input_return_checksum', sa.String(length=64), nullable=False),
    sa.Column('covariance_estimator', sa.JSON(), nullable=False),
    sa.Column('expected_return_estimator', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('training_period', sa.JSON(), nullable=False),
    sa.Column('validation_period', sa.JSON(), nullable=False),
    sa.Column('resulting_weights', sa.JSON(), nullable=False),
    sa.Column('objective_values', sa.JSON(), nullable=False),
    sa.Column('risk_metrics', sa.JSON(), nullable=False),
    sa.Column('optimizer_version', sa.String(length=40), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_optimization_experiments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_experiments'))
    )
    op.create_index(op.f('ix_optimization_experiments_input_return_checksum'), 'optimization_experiments', ['input_return_checksum'], unique=False)
    op.create_index(op.f('ix_optimization_experiments_model'), 'optimization_experiments', ['model'], unique=False)
    op.create_index(op.f('ix_optimization_experiments_workspace_id'), 'optimization_experiments', ['workspace_id'], unique=False)
    op.create_table('sec_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.String(length=700), nullable=False),
    sa.Column('content_reference', sa.String(length=500), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['sec_filings.id'], name=op.f('fk_sec_documents_filing_id_sec_filings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sec_documents')),
    sa.UniqueConstraint('filing_id', 'sequence', name='uq_sec_document_filing_sequence')
    )
    op.create_index(op.f('ix_sec_documents_content_checksum'), 'sec_documents', ['content_checksum'], unique=False)
    op.create_index(op.f('ix_sec_documents_document_type'), 'sec_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_sec_documents_filing_id'), 'sec_documents', ['filing_id'], unique=False)
    op.create_table('sec_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=True),
    sa.Column('taxonomy', sa.String(length=40), nullable=False),
    sa.Column('concept', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('filed_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['sec_companies.id'], name=op.f('fk_sec_facts_company_id_sec_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_id'], ['sec_filings.id'], name=op.f('fk_sec_facts_filing_id_sec_filings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sec_facts'))
    )
    op.create_index(op.f('ix_sec_facts_company_id'), 'sec_facts', ['company_id'], unique=False)
    op.create_index(op.f('ix_sec_facts_concept'), 'sec_facts', ['concept'], unique=False)
    op.create_index(op.f('ix_sec_facts_filed_at'), 'sec_facts', ['filed_at'], unique=False)
    op.create_index(op.f('ix_sec_facts_filing_id'), 'sec_facts', ['filing_id'], unique=False)
    op.create_index(op.f('ix_sec_facts_period_end'), 'sec_facts', ['period_end'], unique=False)
    op.create_index(op.f('ix_sec_facts_taxonomy'), 'sec_facts', ['taxonomy'], unique=False)
    op.create_table('sec_ingestion_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('forms', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user_profiles.id'], name=op.f('fk_sec_ingestion_jobs_requested_by_user_id_user_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sec_ingestion_jobs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sec_ingestion_jobs')),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_sec_ingestion_workspace_idempotency')
    )
    op.create_index(op.f('ix_sec_ingestion_jobs_cik'), 'sec_ingestion_jobs', ['cik'], unique=False)
    op.create_index(op.f('ix_sec_ingestion_jobs_requested_by_user_id'), 'sec_ingestion_jobs', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_sec_ingestion_jobs_status'), 'sec_ingestion_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_sec_ingestion_jobs_workspace_id'), 'sec_ingestion_jobs', ['workspace_id'], unique=False)
    op.create_table('sec_insider_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('owner_name', sa.String(length=240), nullable=False),
    sa.Column('relationship', sa.String(length=120), nullable=False),
    sa.Column('transaction_code', sa.String(length=8), nullable=False),
    sa.Column('security_title', sa.String(length=160), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('acquired_disposed', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['sec_companies.id'], name=op.f('fk_sec_insider_transactions_company_id_sec_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_id'], ['sec_filings.id'], name=op.f('fk_sec_insider_transactions_filing_id_sec_filings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sec_insider_transactions'))
    )
    op.create_index(op.f('ix_sec_insider_transactions_company_id'), 'sec_insider_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_sec_insider_transactions_filing_id'), 'sec_insider_transactions', ['filing_id'], unique=False)
    op.create_index(op.f('ix_sec_insider_transactions_owner_name'), 'sec_insider_transactions', ['owner_name'], unique=False)
    op.create_index(op.f('ix_sec_insider_transactions_transaction_date'), 'sec_insider_transactions', ['transaction_date'], unique=False)
    op.create_table('sec_institutional_holdings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('issuer_name', sa.String(length=240), nullable=False),
    sa.Column('cusip', sa.String(length=12), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('voting_authority', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['sec_companies.id'], name=op.f('fk_sec_institutional_holdings_company_id_sec_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filing_id'], ['sec_filings.id'], name=op.f('fk_sec_institutional_holdings_filing_id_sec_filings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sec_institutional_holdings'))
    )
    op.create_index(op.f('ix_sec_institutional_holdings_as_of_date'), 'sec_institutional_holdings', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_sec_institutional_holdings_company_id'), 'sec_institutional_holdings', ['company_id'], unique=False)
    op.create_index(op.f('ix_sec_institutional_holdings_cusip'), 'sec_institutional_holdings', ['cusip'], unique=False)
    op.create_index(op.f('ix_sec_institutional_holdings_filing_id'), 'sec_institutional_holdings', ['filing_id'], unique=False)
    op.create_index(op.f('ix_sec_institutional_holdings_issuer_name'), 'sec_institutional_holdings', ['issuer_name'], unique=False)
    op.create_table('sec_parse_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_job_id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('parser_checksum', sa.String(length=64), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('parsed_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['sec_filings.id'], name=op.f('fk_sec_parse_results_filing_id_sec_filings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['sec_ingestion_jobs.id'], name=op.f('fk_sec_parse_results_ingestion_job_id_sec_ingestion_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sec_parse_results'))
    )
    op.create_index(op.f('ix_sec_parse_results_filing_id'), 'sec_parse_results', ['filing_id'], unique=False)
    op.create_index(op.f('ix_sec_parse_results_ingestion_job_id'), 'sec_parse_results', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_sec_parse_results_status'), 'sec_parse_results', ['status'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        for table_name in APPLICATION_TABLES:
            op.execute(sa.text(f'ALTER TABLE public."{table_name}" ENABLE ROW LEVEL SECURITY'))
        op.execute(
            sa.text(
                """
                DO $mil$
                BEGIN
                    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                        REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM anon;
                        REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM anon;
                    END IF;
                    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                        REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM authenticated;
                        REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
                    END IF;
                END
                $mil$;
                """
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sec_parse_results_status'), table_name='sec_parse_results')
    op.drop_index(op.f('ix_sec_parse_results_ingestion_job_id'), table_name='sec_parse_results')
    op.drop_index(op.f('ix_sec_parse_results_filing_id'), table_name='sec_parse_results')
    op.drop_table('sec_parse_results')
    op.drop_index(op.f('ix_sec_institutional_holdings_issuer_name'), table_name='sec_institutional_holdings')
    op.drop_index(op.f('ix_sec_institutional_holdings_filing_id'), table_name='sec_institutional_holdings')
    op.drop_index(op.f('ix_sec_institutional_holdings_cusip'), table_name='sec_institutional_holdings')
    op.drop_index(op.f('ix_sec_institutional_holdings_company_id'), table_name='sec_institutional_holdings')
    op.drop_index(op.f('ix_sec_institutional_holdings_as_of_date'), table_name='sec_institutional_holdings')
    op.drop_table('sec_institutional_holdings')
    op.drop_index(op.f('ix_sec_insider_transactions_transaction_date'), table_name='sec_insider_transactions')
    op.drop_index(op.f('ix_sec_insider_transactions_owner_name'), table_name='sec_insider_transactions')
    op.drop_index(op.f('ix_sec_insider_transactions_filing_id'), table_name='sec_insider_transactions')
    op.drop_index(op.f('ix_sec_insider_transactions_company_id'), table_name='sec_insider_transactions')
    op.drop_table('sec_insider_transactions')
    op.drop_index(op.f('ix_sec_ingestion_jobs_workspace_id'), table_name='sec_ingestion_jobs')
    op.drop_index(op.f('ix_sec_ingestion_jobs_status'), table_name='sec_ingestion_jobs')
    op.drop_index(op.f('ix_sec_ingestion_jobs_requested_by_user_id'), table_name='sec_ingestion_jobs')
    op.drop_index(op.f('ix_sec_ingestion_jobs_cik'), table_name='sec_ingestion_jobs')
    op.drop_table('sec_ingestion_jobs')
    op.drop_index(op.f('ix_sec_facts_taxonomy'), table_name='sec_facts')
    op.drop_index(op.f('ix_sec_facts_period_end'), table_name='sec_facts')
    op.drop_index(op.f('ix_sec_facts_filing_id'), table_name='sec_facts')
    op.drop_index(op.f('ix_sec_facts_filed_at'), table_name='sec_facts')
    op.drop_index(op.f('ix_sec_facts_concept'), table_name='sec_facts')
    op.drop_index(op.f('ix_sec_facts_company_id'), table_name='sec_facts')
    op.drop_table('sec_facts')
    op.drop_index(op.f('ix_sec_documents_filing_id'), table_name='sec_documents')
    op.drop_index(op.f('ix_sec_documents_document_type'), table_name='sec_documents')
    op.drop_index(op.f('ix_sec_documents_content_checksum'), table_name='sec_documents')
    op.drop_table('sec_documents')
    op.drop_index(op.f('ix_optimization_experiments_workspace_id'), table_name='optimization_experiments')
    op.drop_index(op.f('ix_optimization_experiments_model'), table_name='optimization_experiments')
    op.drop_index(op.f('ix_optimization_experiments_input_return_checksum'), table_name='optimization_experiments')
    op.drop_table('optimization_experiments')
    op.drop_index(op.f('ix_external_engine_runs_workspace_id'), table_name='external_engine_runs')
    op.drop_index(op.f('ix_external_engine_runs_status'), table_name='external_engine_runs')
    op.drop_index(op.f('ix_external_engine_runs_request_checksum'), table_name='external_engine_runs')
    op.drop_index(op.f('ix_external_engine_runs_engine'), table_name='external_engine_runs')
    op.drop_table('external_engine_runs')
    op.drop_index(op.f('ix_analytics_comparison_records_workspace_id'), table_name='analytics_comparison_records')
    op.drop_index(op.f('ix_analytics_comparison_records_return_series_checksum'), table_name='analytics_comparison_records')
    op.drop_index(op.f('ix_analytics_comparison_records_agreement_status'), table_name='analytics_comparison_records')
    op.drop_table('analytics_comparison_records')
    op.drop_index(op.f('ix_sec_filings_simulation_eligible_at'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_is_amendment'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_form_type'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_filing_date'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_content_checksum'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_company_id'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_accession_number'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_accepted_at'), table_name='sec_filings')
    op.drop_table('sec_filings')
    op.drop_index(op.f('ix_sec_companies_source_checksum'), table_name='sec_companies')
    op.drop_index(op.f('ix_sec_companies_name'), table_name='sec_companies')
    op.drop_index(op.f('ix_sec_companies_cik'), table_name='sec_companies')
    op.drop_table('sec_companies')
    # ### end Alembic commands ###
