"""temporal world data foundation

Revision ID: 7f4af62df2fe
Revises: 6b8d9e0f1a2b
Create Date: 2026-08-07 23:23:36.355502
"""
from typing import Sequence, Union

from alembic import op
import packages.database.types
import sqlalchemy as sa


revision: str = '7f4af62df2fe'
down_revision: Union[str, None] = '6b8d9e0f1a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('units', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=80), nullable=False),
    sa.Column('geography', sa.String(length=120), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_series')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_energy_source_external')
    )
    op.create_index(op.f('ix_energy_series_external_id'), 'energy_series', ['external_id'], unique=False)
    op.create_index(op.f('ix_energy_series_source_id'), 'energy_series', ['source_id'], unique=False)
    op.create_table('macro_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('units', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=80), nullable=False),
    sa.Column('seasonal_adjustment', sa.String(length=120), nullable=True),
    sa.Column('release_id', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macro_series')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_macro_source_external')
    )
    op.create_index(op.f('ix_macro_series_external_id'), 'macro_series', ['external_id'], unique=False)
    op.create_index(op.f('ix_macro_series_source_id'), 'macro_series', ['source_id'], unique=False)
    op.create_table('raw_data_objects',
    sa.Column('key', sa.String(length=700), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('byte_count', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_raw_data_objects'))
    )
    op.create_index(op.f('ix_raw_data_objects_checksum'), 'raw_data_objects', ['checksum'], unique=True)
    op.create_table('data_manifests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=96), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('retrieval_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source_updated_time', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('temporal_coverage_start', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('temporal_coverage_end', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('raw_object_reference', sa.String(length=700), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('checksum_algorithm', sa.String(length=16), nullable=False),
    sa.Column('byte_count', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('quality_summary', sa.JSON(), nullable=False),
    sa.Column('license_identifier', sa.String(length=120), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('parent_manifest_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('record_count >= 0', name=op.f('ck_data_manifests_manifest_record_count_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], name=op.f('fk_data_manifests_job_id_import_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_manifest_id'], ['data_manifests.id'], name=op.f('fk_data_manifests_parent_manifest_id_data_manifests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_manifests')),
    sa.UniqueConstraint('source_id', 'dataset_id', 'checksum', name='uq_manifest_dataset_checksum')
    )
    op.create_index(op.f('ix_data_manifests_checksum'), 'data_manifests', ['checksum'], unique=False)
    op.create_index(op.f('ix_data_manifests_dataset_id'), 'data_manifests', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_data_manifests_job_id'), 'data_manifests', ['job_id'], unique=False)
    op.create_index(op.f('ix_data_manifests_parent_manifest_id'), 'data_manifests', ['parent_manifest_id'], unique=False)
    op.create_index(op.f('ix_data_manifests_retrieval_time'), 'data_manifests', ['retrieval_time'], unique=False)
    op.create_index(op.f('ix_data_manifests_source_id'), 'data_manifests', ['source_id'], unique=False)
    op.create_table('energy_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('source_value', sa.String(length=120), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('event_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('observation_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('publication_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('retrieval_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revision_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('time_precision', sa.String(length=24), nullable=False),
    sa.Column('source_time_zone', sa.String(length=64), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('manifest_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['data_manifests.id'], name=op.f('fk_energy_observations_manifest_id_data_manifests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['series_id'], ['energy_series.id'], name=op.f('fk_energy_observations_series_id_energy_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_observations')),
    sa.UniqueConstraint('series_id', 'observation_time', 'source_value', name='uq_energy_observation')
    )
    op.create_index(op.f('ix_energy_observations_manifest_id'), 'energy_observations', ['manifest_id'], unique=False)
    op.create_index(op.f('ix_energy_observations_observation_time'), 'energy_observations', ['observation_time'], unique=False)
    op.create_index(op.f('ix_energy_observations_series_id'), 'energy_observations', ['series_id'], unique=False)
    op.create_index(op.f('ix_energy_observations_simulation_eligible_time'), 'energy_observations', ['simulation_eligible_time'], unique=False)
    op.create_index('ix_energy_series_observation', 'energy_observations', ['series_id', 'observation_time'], unique=False)
    op.create_table('ingestion_checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=96), nullable=False),
    sa.Column('cursor_json', sa.JSON(), nullable=False),
    sa.Column('last_manifest_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_manifest_id'], ['data_manifests.id'], name=op.f('fk_ingestion_checkpoints_last_manifest_id_data_manifests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_checkpoints')),
    sa.UniqueConstraint('source_id', 'dataset_id', name='uq_checkpoint_dataset')
    )
    op.create_index(op.f('ix_ingestion_checkpoints_dataset_id'), 'ingestion_checkpoints', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ingestion_checkpoints_source_id'), 'ingestion_checkpoints', ['source_id'], unique=False)
    op.create_table('macro_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('source_value', sa.String(length=120), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('event_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('observation_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('publication_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('retrieval_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revision_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('realtime_end', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('time_precision', sa.String(length=24), nullable=False),
    sa.Column('source_time_zone', sa.String(length=64), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('manifest_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['data_manifests.id'], name=op.f('fk_macro_observations_manifest_id_data_manifests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.id'], name=op.f('fk_macro_observations_series_id_macro_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macro_observations')),
    sa.UniqueConstraint('series_id', 'observation_time', 'revision_time', 'source_value', name='uq_macro_observation_vintage')
    )
    op.create_index('ix_macro_as_of', 'macro_observations', ['series_id', 'observation_time', 'simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_macro_observations_manifest_id'), 'macro_observations', ['manifest_id'], unique=False)
    op.create_index(op.f('ix_macro_observations_observation_time'), 'macro_observations', ['observation_time'], unique=False)
    op.create_index(op.f('ix_macro_observations_series_id'), 'macro_observations', ['series_id'], unique=False)
    op.create_index(op.f('ix_macro_observations_simulation_eligible_time'), 'macro_observations', ['simulation_eligible_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macro_observations_simulation_eligible_time'), table_name='macro_observations')
    op.drop_index(op.f('ix_macro_observations_series_id'), table_name='macro_observations')
    op.drop_index(op.f('ix_macro_observations_observation_time'), table_name='macro_observations')
    op.drop_index(op.f('ix_macro_observations_manifest_id'), table_name='macro_observations')
    op.drop_index('ix_macro_as_of', table_name='macro_observations')
    op.drop_table('macro_observations')
    op.drop_index(op.f('ix_ingestion_checkpoints_source_id'), table_name='ingestion_checkpoints')
    op.drop_index(op.f('ix_ingestion_checkpoints_dataset_id'), table_name='ingestion_checkpoints')
    op.drop_table('ingestion_checkpoints')
    op.drop_index('ix_energy_series_observation', table_name='energy_observations')
    op.drop_index(op.f('ix_energy_observations_simulation_eligible_time'), table_name='energy_observations')
    op.drop_index(op.f('ix_energy_observations_series_id'), table_name='energy_observations')
    op.drop_index(op.f('ix_energy_observations_observation_time'), table_name='energy_observations')
    op.drop_index(op.f('ix_energy_observations_manifest_id'), table_name='energy_observations')
    op.drop_table('energy_observations')
    op.drop_index(op.f('ix_data_manifests_source_id'), table_name='data_manifests')
    op.drop_index(op.f('ix_data_manifests_retrieval_time'), table_name='data_manifests')
    op.drop_index(op.f('ix_data_manifests_parent_manifest_id'), table_name='data_manifests')
    op.drop_index(op.f('ix_data_manifests_job_id'), table_name='data_manifests')
    op.drop_index(op.f('ix_data_manifests_dataset_id'), table_name='data_manifests')
    op.drop_index(op.f('ix_data_manifests_checksum'), table_name='data_manifests')
    op.drop_table('data_manifests')
    op.drop_index(op.f('ix_raw_data_objects_checksum'), table_name='raw_data_objects')
    op.drop_table('raw_data_objects')
    op.drop_index(op.f('ix_macro_series_source_id'), table_name='macro_series')
    op.drop_index(op.f('ix_macro_series_external_id'), table_name='macro_series')
    op.drop_table('macro_series')
    op.drop_index(op.f('ix_energy_series_source_id'), table_name='energy_series')
    op.drop_index(op.f('ix_energy_series_external_id'), table_name='energy_series')
    op.drop_table('energy_series')
    # ### end Alembic commands ###
