"""adversarial scenario and counterfactual intelligence

Revision ID: e2517ff0412b
Revises: eb1ff477509f
Create Date: 2026-08-15 13:43:59.551147
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import packages.database.types


revision: str = 'e2517ff0412b'
down_revision: Union[str, None] = 'eb1ff477509f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterfactual_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reference_state', sa.JSON(), nullable=False),
    sa.Column('intervention', sa.JSON(), nullable=False),
    sa.Column('mechanism_path', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('identification_status', sa.String(length=32), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('horizon', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_counterfactual_definitions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterfactual_definitions'))
    )
    op.create_index(op.f('ix_counterfactual_definitions_as_of_time'), 'counterfactual_definitions', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_counterfactual_definitions_workspace_id'), 'counterfactual_definitions', ['workspace_id'], unique=False)
    op.create_table('scenario_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scenario_type', sa.String(length=32), nullable=False),
    sa.Column('plausibility', sa.String(length=16), nullable=False),
    sa.Column('horizon', sa.String(length=80), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('source_evidence', sa.JSON(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_scenario_definitions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_definitions')),
    sa.UniqueConstraint('workspace_id', 'checksum', name='uq_scenario_definition_sum')
    )
    op.create_index(op.f('ix_scenario_definitions_as_of_time'), 'scenario_definitions', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_scenario_definitions_checksum'), 'scenario_definitions', ['checksum'], unique=False)
    op.create_index(op.f('ix_scenario_definitions_scenario_type'), 'scenario_definitions', ['scenario_type'], unique=False)
    op.create_index(op.f('ix_scenario_definitions_workspace_id'), 'scenario_definitions', ['workspace_id'], unique=False)
    op.create_table('counterfactual_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('comparison', sa.JSON(), nullable=False),
    sa.Column('identification_status', sa.String(length=32), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['counterfactual_definitions.id'], name=op.f('fk_counterfactual_runs_definition_id_counterfactual_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_counterfactual_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterfactual_runs')),
    sa.UniqueConstraint('checksum', name=op.f('uq_counterfactual_runs_checksum'))
    )
    op.create_index(op.f('ix_counterfactual_runs_as_of_time'), 'counterfactual_runs', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_counterfactual_runs_definition_id'), 'counterfactual_runs', ['definition_id'], unique=False)
    op.create_index(op.f('ix_counterfactual_runs_workspace_id'), 'counterfactual_runs', ['workspace_id'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario_definitions.id'], name=op.f('fk_scenario_runs_scenario_id_scenario_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_scenario_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_runs')),
    sa.UniqueConstraint('checksum', name=op.f('uq_scenario_runs_checksum'))
    )
    op.create_index(op.f('ix_scenario_runs_as_of_time'), 'scenario_runs', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_scenario_runs_scenario_id'), 'scenario_runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_runs_workspace_id'), 'scenario_runs', ['workspace_id'], unique=False)
    op.create_table('scenario_shocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('units', sa.String(length=40), nullable=False),
    sa.Column('timing', sa.JSON(), nullable=False),
    sa.Column('recovery', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('source_assumption', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario_definitions.id'], name=op.f('fk_scenario_shocks_scenario_id_scenario_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_shocks'))
    )
    op.create_index(op.f('ix_scenario_shocks_scenario_id'), 'scenario_shocks', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_shocks_target'), 'scenario_shocks', ['target'], unique=False)
    op.create_table('scenario_impacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('impact_type', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('units', sa.String(length=40), nullable=False),
    sa.Column('transmission_path', sa.JSON(), nullable=False),
    sa.Column('sensitivity', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['scenario_runs.id'], name=op.f('fk_scenario_impacts_run_id_scenario_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_impacts'))
    )
    op.create_index(op.f('ix_scenario_impacts_run_id'), 'scenario_impacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_scenario_impacts_subject'), 'scenario_impacts', ['subject'], unique=False)
    op.create_table('research_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('subject_entity_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=True),
    sa.Column('experiment_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('promotion_state', sa.String(length=40), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['factor_experiments.id'], name=op.f('fk_research_cases_experiment_id_factor_experiments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['research_hypotheses.id'], name=op.f('fk_research_cases_hypothesis_id_research_hypotheses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['economic_entities.id'], name=op.f('fk_research_cases_subject_entity_id_economic_entities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_cases_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_cases')),
    sa.UniqueConstraint('workspace_id', 'checksum', name='uq_research_case_sum')
    )
    op.create_index(op.f('ix_research_cases_as_of_time'), 'research_cases', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_research_cases_checksum'), 'research_cases', ['checksum'], unique=False)
    op.create_index(op.f('ix_research_cases_experiment_id'), 'research_cases', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_research_cases_hypothesis_id'), 'research_cases', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_research_cases_simulation_eligible_time'), 'research_cases', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_research_cases_subject_entity_id'), 'research_cases', ['subject_entity_id'], unique=False)
    op.create_index(op.f('ix_research_cases_workspace_id'), 'research_cases', ['workspace_id'], unique=False)
    op.create_table('research_assumptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('research_case_id', sa.Uuid(), nullable=False),
    sa.Column('assumption_type', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('importance', sa.String(length=16), nullable=False),
    sa.Column('sensitivity', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], name=op.f('fk_research_assumptions_research_case_id_research_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_assumptions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_assumptions'))
    )
    op.create_index(op.f('ix_research_assumptions_assumption_type'), 'research_assumptions', ['assumption_type'], unique=False)
    op.create_index(op.f('ix_research_assumptions_research_case_id'), 'research_assumptions', ['research_case_id'], unique=False)
    op.create_index(op.f('ix_research_assumptions_workspace_id'), 'research_assumptions', ['workspace_id'], unique=False)
    op.create_table('research_confidence_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('research_case_id', sa.Uuid(), nullable=False),
    sa.Column('formula_version', sa.String(length=40), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], name=op.f('fk_research_confidence_profiles_research_case_id_research_cases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_confidence_profiles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_confidence_profiles')),
    sa.UniqueConstraint('checksum', name=op.f('uq_research_confidence_profiles_checksum'))
    )
    op.create_index(op.f('ix_research_confidence_profiles_as_of_time'), 'research_confidence_profiles', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_research_confidence_profiles_research_case_id'), 'research_confidence_profiles', ['research_case_id'], unique=False)
    op.create_index(op.f('ix_research_confidence_profiles_workspace_id'), 'research_confidence_profiles', ['workspace_id'], unique=False)
    op.create_table('research_dossiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('research_case_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], name=op.f('fk_research_dossiers_research_case_id_research_cases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_dossiers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_dossiers')),
    sa.UniqueConstraint('checksum', name=op.f('uq_research_dossiers_checksum'))
    )
    op.create_index(op.f('ix_research_dossiers_as_of_time'), 'research_dossiers', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_research_dossiers_research_case_id'), 'research_dossiers', ['research_case_id'], unique=False)
    op.create_index(op.f('ix_research_dossiers_workspace_id'), 'research_dossiers', ['workspace_id'], unique=False)
    op.create_table('research_fragility_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('research_case_id', sa.Uuid(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], name=op.f('fk_research_fragility_analyses_research_case_id_research_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_fragility_analyses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_fragility_analyses'))
    )
    op.create_index(op.f('ix_research_fragility_analyses_as_of_time'), 'research_fragility_analyses', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_research_fragility_analyses_classification'), 'research_fragility_analyses', ['classification'], unique=False)
    op.create_index(op.f('ix_research_fragility_analyses_research_case_id'), 'research_fragility_analyses', ['research_case_id'], unique=False)
    op.create_index(op.f('ix_research_fragility_analyses_workspace_id'), 'research_fragility_analyses', ['workspace_id'], unique=False)
    op.create_table('skeptic_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('research_case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('completed_at', packages.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','RUNNING','NEEDS_EVIDENCE','QUALIFIED','BLOCKED','INVALIDATED','COMPLETED')", name=op.f('ck_skeptic_reviews_skeptic_review_status')),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], name=op.f('fk_skeptic_reviews_research_case_id_research_cases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_skeptic_reviews_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skeptic_reviews')),
    sa.UniqueConstraint('checksum', name=op.f('uq_skeptic_reviews_checksum'))
    )
    op.create_index(op.f('ix_skeptic_reviews_as_of_time'), 'skeptic_reviews', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_skeptic_reviews_research_case_id'), 'skeptic_reviews', ['research_case_id'], unique=False)
    op.create_index(op.f('ix_skeptic_reviews_simulation_eligible_time'), 'skeptic_reviews', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_skeptic_reviews_status'), 'skeptic_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_skeptic_reviews_workspace_id'), 'skeptic_reviews', ['workspace_id'], unique=False)
    op.create_table('skeptic_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('affected_claim', sa.Text(), nullable=False),
    sa.Column('falsification_condition', sa.Text(), nullable=False),
    sa.Column('proposed_test', sa.Text(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')", name=op.f('ck_skeptic_challenges_skeptic_challenge_severity')),
    sa.CheckConstraint("status IN ('OPEN','TESTING','RESOLVED','ACCEPTED_RISK','INVALIDATES_CLAIM')", name=op.f('ck_skeptic_challenges_skeptic_challenge_status')),
    sa.ForeignKeyConstraint(['review_id'], ['skeptic_reviews.id'], name=op.f('fk_skeptic_challenges_review_id_skeptic_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_skeptic_challenges_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skeptic_challenges'))
    )
    op.create_index(op.f('ix_skeptic_challenges_category'), 'skeptic_challenges', ['category'], unique=False)
    op.create_index(op.f('ix_skeptic_challenges_review_id'), 'skeptic_challenges', ['review_id'], unique=False)
    op.create_index(op.f('ix_skeptic_challenges_severity'), 'skeptic_challenges', ['severity'], unique=False)
    op.create_index(op.f('ix_skeptic_challenges_simulation_eligible_time'), 'skeptic_challenges', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_skeptic_challenges_status'), 'skeptic_challenges', ['status'], unique=False)
    op.create_index(op.f('ix_skeptic_challenges_workspace_id'), 'skeptic_challenges', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skeptic_challenges_workspace_id'), table_name='skeptic_challenges')
    op.drop_index(op.f('ix_skeptic_challenges_status'), table_name='skeptic_challenges')
    op.drop_index(op.f('ix_skeptic_challenges_simulation_eligible_time'), table_name='skeptic_challenges')
    op.drop_index(op.f('ix_skeptic_challenges_severity'), table_name='skeptic_challenges')
    op.drop_index(op.f('ix_skeptic_challenges_review_id'), table_name='skeptic_challenges')
    op.drop_index(op.f('ix_skeptic_challenges_category'), table_name='skeptic_challenges')
    op.drop_table('skeptic_challenges')
    op.drop_index(op.f('ix_skeptic_reviews_workspace_id'), table_name='skeptic_reviews')
    op.drop_index(op.f('ix_skeptic_reviews_status'), table_name='skeptic_reviews')
    op.drop_index(op.f('ix_skeptic_reviews_simulation_eligible_time'), table_name='skeptic_reviews')
    op.drop_index(op.f('ix_skeptic_reviews_research_case_id'), table_name='skeptic_reviews')
    op.drop_index(op.f('ix_skeptic_reviews_as_of_time'), table_name='skeptic_reviews')
    op.drop_table('skeptic_reviews')
    op.drop_index(op.f('ix_research_fragility_analyses_workspace_id'), table_name='research_fragility_analyses')
    op.drop_index(op.f('ix_research_fragility_analyses_research_case_id'), table_name='research_fragility_analyses')
    op.drop_index(op.f('ix_research_fragility_analyses_classification'), table_name='research_fragility_analyses')
    op.drop_index(op.f('ix_research_fragility_analyses_as_of_time'), table_name='research_fragility_analyses')
    op.drop_table('research_fragility_analyses')
    op.drop_index(op.f('ix_research_dossiers_workspace_id'), table_name='research_dossiers')
    op.drop_index(op.f('ix_research_dossiers_research_case_id'), table_name='research_dossiers')
    op.drop_index(op.f('ix_research_dossiers_as_of_time'), table_name='research_dossiers')
    op.drop_table('research_dossiers')
    op.drop_index(op.f('ix_research_confidence_profiles_workspace_id'), table_name='research_confidence_profiles')
    op.drop_index(op.f('ix_research_confidence_profiles_research_case_id'), table_name='research_confidence_profiles')
    op.drop_index(op.f('ix_research_confidence_profiles_as_of_time'), table_name='research_confidence_profiles')
    op.drop_table('research_confidence_profiles')
    op.drop_index(op.f('ix_research_assumptions_workspace_id'), table_name='research_assumptions')
    op.drop_index(op.f('ix_research_assumptions_research_case_id'), table_name='research_assumptions')
    op.drop_index(op.f('ix_research_assumptions_assumption_type'), table_name='research_assumptions')
    op.drop_table('research_assumptions')
    op.drop_index(op.f('ix_research_cases_workspace_id'), table_name='research_cases')
    op.drop_index(op.f('ix_research_cases_subject_entity_id'), table_name='research_cases')
    op.drop_index(op.f('ix_research_cases_simulation_eligible_time'), table_name='research_cases')
    op.drop_index(op.f('ix_research_cases_hypothesis_id'), table_name='research_cases')
    op.drop_index(op.f('ix_research_cases_experiment_id'), table_name='research_cases')
    op.drop_index(op.f('ix_research_cases_checksum'), table_name='research_cases')
    op.drop_index(op.f('ix_research_cases_as_of_time'), table_name='research_cases')
    op.drop_table('research_cases')
    op.drop_index(op.f('ix_scenario_impacts_subject'), table_name='scenario_impacts')
    op.drop_index(op.f('ix_scenario_impacts_run_id'), table_name='scenario_impacts')
    op.drop_table('scenario_impacts')
    op.drop_index(op.f('ix_scenario_shocks_target'), table_name='scenario_shocks')
    op.drop_index(op.f('ix_scenario_shocks_scenario_id'), table_name='scenario_shocks')
    op.drop_table('scenario_shocks')
    op.drop_index(op.f('ix_scenario_runs_workspace_id'), table_name='scenario_runs')
    op.drop_index(op.f('ix_scenario_runs_scenario_id'), table_name='scenario_runs')
    op.drop_index(op.f('ix_scenario_runs_as_of_time'), table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index(op.f('ix_counterfactual_runs_workspace_id'), table_name='counterfactual_runs')
    op.drop_index(op.f('ix_counterfactual_runs_definition_id'), table_name='counterfactual_runs')
    op.drop_index(op.f('ix_counterfactual_runs_as_of_time'), table_name='counterfactual_runs')
    op.drop_table('counterfactual_runs')
    op.drop_index(op.f('ix_scenario_definitions_workspace_id'), table_name='scenario_definitions')
    op.drop_index(op.f('ix_scenario_definitions_scenario_type'), table_name='scenario_definitions')
    op.drop_index(op.f('ix_scenario_definitions_checksum'), table_name='scenario_definitions')
    op.drop_index(op.f('ix_scenario_definitions_as_of_time'), table_name='scenario_definitions')
    op.drop_table('scenario_definitions')
    op.drop_index(op.f('ix_counterfactual_definitions_workspace_id'), table_name='counterfactual_definitions')
    op.drop_index(op.f('ix_counterfactual_definitions_as_of_time'), table_name='counterfactual_definitions')
    op.drop_table('counterfactual_definitions')
    # ### end Alembic commands ###
