"""research memory signal independence and divergence intelligence

Revision ID: eb1ff477509f
Revises: ed23735efb90
Create Date: 2026-08-15 10:40:13.812968
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import packages.database.types


revision: str = 'eb1ff477509f'
down_revision: str | None = 'ed23735efb90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divergence_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('required_features', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('temporal_truth_policy', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_divergence_definitions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divergence_definitions')),
    sa.UniqueConstraint('workspace_id', 'key', 'version', name='uq_divergence_definition_version')
    )
    op.create_index(op.f('ix_divergence_definitions_key'), 'divergence_definitions', ['key'], unique=False)
    op.create_index(op.f('ix_divergence_definitions_workspace_id'), 'divergence_definitions', ['workspace_id'], unique=False)
    op.create_table('factor_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_key', sa.String(length=120), nullable=False),
    sa.Column('information_family', sa.String(length=80), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('methodology', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_factor_clusters_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factor_clusters')),
    sa.UniqueConstraint('workspace_id', 'cluster_key', 'version', name='uq_factor_cluster_version')
    )
    op.create_index(op.f('ix_factor_clusters_as_of_time'), 'factor_clusters', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_factor_clusters_cluster_key'), 'factor_clusters', ['cluster_key'], unique=False)
    op.create_index(op.f('ix_factor_clusters_information_family'), 'factor_clusters', ['information_family'], unique=False)
    op.create_index(op.f('ix_factor_clusters_workspace_id'), 'factor_clusters', ['workspace_id'], unique=False)
    op.create_table('factor_redundancy_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('factor_a', sa.String(length=160), nullable=False),
    sa.Column('factor_b', sa.String(length=160), nullable=False),
    sa.Column('methodology', sa.String(length=48), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_factor_redundancy_results_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factor_redundancy_results')),
    sa.UniqueConstraint('workspace_id', 'checksum', name='uq_factor_redundancy_checksum')
    )
    op.create_index(op.f('ix_factor_redundancy_results_as_of_time'), 'factor_redundancy_results', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_factor_redundancy_results_checksum'), 'factor_redundancy_results', ['checksum'], unique=False)
    op.create_index(op.f('ix_factor_redundancy_results_factor_a'), 'factor_redundancy_results', ['factor_a'], unique=False)
    op.create_index(op.f('ix_factor_redundancy_results_factor_b'), 'factor_redundancy_results', ['factor_b'], unique=False)
    op.create_index(op.f('ix_factor_redundancy_results_workspace_id'), 'factor_redundancy_results', ['workspace_id'], unique=False)
    op.create_table('information_value_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('resource_key', sa.String(length=160), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_information_value_records_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_information_value_records')),
    sa.UniqueConstraint('workspace_id', 'resource_key', 'as_of_time', name='uq_information_value_asof')
    )
    op.create_index(op.f('ix_information_value_records_as_of_time'), 'information_value_records', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_information_value_records_resource_key'), 'information_value_records', ['resource_key'], unique=False)
    op.create_index(op.f('ix_information_value_records_resource_type'), 'information_value_records', ['resource_type'], unique=False)
    op.create_index(op.f('ix_information_value_records_workspace_id'), 'information_value_records', ['workspace_id'], unique=False)
    op.create_table('research_method_reliability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_method_reliability_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_method_reliability')),
    sa.UniqueConstraint('workspace_id', 'method', 'as_of_time', name='uq_method_reliability_asof')
    )
    op.create_index(op.f('ix_research_method_reliability_as_of_time'), 'research_method_reliability', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_research_method_reliability_method'), 'research_method_reliability', ['method'], unique=False)
    op.create_index(op.f('ix_research_method_reliability_workspace_id'), 'research_method_reliability', ['workspace_id'], unique=False)
    op.create_table('research_regime_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('method', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_regime_definitions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_regime_definitions')),
    sa.UniqueConstraint('workspace_id', 'key', 'version', name='uq_research_regime_version')
    )
    op.create_index(op.f('ix_research_regime_definitions_key'), 'research_regime_definitions', ['key'], unique=False)
    op.create_index(op.f('ix_research_regime_definitions_workspace_id'), 'research_regime_definitions', ['workspace_id'], unique=False)
    op.create_table('research_regime_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('subject_entity_id', sa.Uuid(), nullable=True),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['research_regime_definitions.id'], name=op.f('fk_research_regime_assignments_definition_id_research_regime_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['economic_entities.id'], name=op.f('fk_research_regime_assignments_subject_entity_id_economic_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_regime_assignments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_regime_assignments')),
    sa.UniqueConstraint('definition_id', 'subject_entity_id', 'as_of_time', name='uq_regime_assignment')
    )
    op.create_index(op.f('ix_research_regime_assignments_active'), 'research_regime_assignments', ['active'], unique=False)
    op.create_index(op.f('ix_research_regime_assignments_as_of_time'), 'research_regime_assignments', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_research_regime_assignments_definition_id'), 'research_regime_assignments', ['definition_id'], unique=False)
    op.create_index(op.f('ix_research_regime_assignments_simulation_eligible_time'), 'research_regime_assignments', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_research_regime_assignments_subject_entity_id'), 'research_regime_assignments', ['subject_entity_id'], unique=False)
    op.create_index(op.f('ix_research_regime_assignments_workspace_id'), 'research_regime_assignments', ['workspace_id'], unique=False)
    op.create_table('divergence_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('subject_entity_id', sa.Uuid(), nullable=False),
    sa.Column('research_candidate_id', sa.Uuid(), nullable=True),
    sa.Column('feature_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('domain_values', sa.JSON(), nullable=False),
    sa.Column('magnitude_components', sa.JSON(), nullable=False),
    sa.Column('disagreement_magnitude', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('persistence_periods', sa.Integer(), nullable=False),
    sa.Column('data_completeness', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('historical_analogues', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('research_priority', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DETECTED','UNDER_REVIEW','EXPLAINED','UNEXPLAINED','DISMISSED','RESEARCH_PROMOTED')", name=op.f('ck_divergence_events_divergence_event_status')),
    sa.ForeignKeyConstraint(['definition_id'], ['divergence_definitions.id'], name=op.f('fk_divergence_events_definition_id_divergence_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], name=op.f('fk_divergence_events_feature_snapshot_id_feature_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_candidate_id'], ['research_candidate_states.id'], name=op.f('fk_divergence_events_research_candidate_id_research_candidate_states'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['economic_entities.id'], name=op.f('fk_divergence_events_subject_entity_id_economic_entities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_divergence_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divergence_events')),
    sa.UniqueConstraint('workspace_id', 'checksum', name='uq_divergence_event_checksum')
    )
    op.create_index(op.f('ix_divergence_events_as_of_time'), 'divergence_events', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_divergence_events_checksum'), 'divergence_events', ['checksum'], unique=False)
    op.create_index(op.f('ix_divergence_events_definition_id'), 'divergence_events', ['definition_id'], unique=False)
    op.create_index(op.f('ix_divergence_events_disagreement_magnitude'), 'divergence_events', ['disagreement_magnitude'], unique=False)
    op.create_index(op.f('ix_divergence_events_feature_snapshot_id'), 'divergence_events', ['feature_snapshot_id'], unique=False)
    op.create_index(op.f('ix_divergence_events_research_candidate_id'), 'divergence_events', ['research_candidate_id'], unique=False)
    op.create_index(op.f('ix_divergence_events_simulation_eligible_time'), 'divergence_events', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_divergence_events_status'), 'divergence_events', ['status'], unique=False)
    op.create_index(op.f('ix_divergence_events_subject_entity_id'), 'divergence_events', ['subject_entity_id'], unique=False)
    op.create_index(op.f('ix_divergence_events_workspace_id'), 'divergence_events', ['workspace_id'], unique=False)
    op.create_index('ix_divergence_subject_asof', 'divergence_events', ['subject_entity_id', 'as_of_time'], unique=False)
    op.create_table('hypothesis_memory_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('matched_memory_ids', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('override_authorized', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("classification IN ('NEW','RETEST','VARIANT','DUPLICATE','KNOWN_FAILURE','KNOWN_SUCCESS','CONTRADICTED')", name=op.f('ck_hypothesis_memory_decisions_memory_decision_classification')),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['research_hypotheses.id'], name=op.f('fk_hypothesis_memory_decisions_hypothesis_id_research_hypotheses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_hypothesis_memory_decisions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypothesis_memory_decisions'))
    )
    op.create_index(op.f('ix_hypothesis_memory_decisions_classification'), 'hypothesis_memory_decisions', ['classification'], unique=False)
    op.create_index(op.f('ix_hypothesis_memory_decisions_created_at'), 'hypothesis_memory_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_hypothesis_memory_decisions_decision'), 'hypothesis_memory_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_hypothesis_memory_decisions_hypothesis_id'), 'hypothesis_memory_decisions', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_memory_decisions_workspace_id'), 'hypothesis_memory_decisions', ['workspace_id'], unique=False)
    op.create_table('research_memory_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('subject_entity_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_version', sa.Integer(), nullable=False),
    sa.Column('hypothesis_checksum', sa.String(length=64), nullable=False),
    sa.Column('mechanism_checksum', sa.String(length=64), nullable=False),
    sa.Column('feature_key', sa.String(length=160), nullable=False),
    sa.Column('feature_version', sa.Integer(), nullable=False),
    sa.Column('outcome_key', sa.String(length=160), nullable=False),
    sa.Column('conclusion', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('graph_path', sa.JSON(), nullable=False),
    sa.Column('datasets', sa.JSON(), nullable=False),
    sa.Column('feature_domains', sa.JSON(), nullable=False),
    sa.Column('applicability', sa.JSON(), nullable=False),
    sa.Column('regime_context', sa.JSON(), nullable=False),
    sa.Column('period_context', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('failure_reasons', sa.JSON(), nullable=False),
    sa.Column('success_conditions', sa.JSON(), nullable=False),
    sa.Column('failure_conditions', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('first_learned_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_confirmed_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','WEAK','CONTRADICTED','SUPERSEDED','RETIRED')", name=op.f('ck_research_memory_entries_research_memory_status')),
    sa.CheckConstraint('schema_version > 0', name=op.f('ck_research_memory_entries_research_memory_schema_version')),
    sa.ForeignKeyConstraint(['experiment_id'], ['factor_experiments.id'], name=op.f('fk_research_memory_entries_experiment_id_factor_experiments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['research_hypotheses.id'], name=op.f('fk_research_memory_entries_hypothesis_id_research_hypotheses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['economic_entities.id'], name=op.f('fk_research_memory_entries_subject_entity_id_economic_entities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_memory_entries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_memory_entries')),
    sa.UniqueConstraint('workspace_id', 'checksum', name='uq_research_memory_checksum')
    )
    op.create_index('ix_memory_mechanism_outcome', 'research_memory_entries', ['workspace_id', 'mechanism_checksum', 'outcome_key'], unique=False)
    op.create_index('ix_memory_subject_status_asof', 'research_memory_entries', ['subject_entity_id', 'status', 'simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_checksum'), 'research_memory_entries', ['checksum'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_conclusion'), 'research_memory_entries', ['conclusion'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_experiment_id'), 'research_memory_entries', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_feature_key'), 'research_memory_entries', ['feature_key'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_first_learned_at'), 'research_memory_entries', ['first_learned_at'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_hypothesis_checksum'), 'research_memory_entries', ['hypothesis_checksum'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_hypothesis_id'), 'research_memory_entries', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_mechanism_checksum'), 'research_memory_entries', ['mechanism_checksum'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_outcome_key'), 'research_memory_entries', ['outcome_key'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_simulation_eligible_time'), 'research_memory_entries', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_status'), 'research_memory_entries', ['status'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_subject_entity_id'), 'research_memory_entries', ['subject_entity_id'], unique=False)
    op.create_index(op.f('ix_research_memory_entries_workspace_id'), 'research_memory_entries', ['workspace_id'], unique=False)
    op.create_table('research_outcome_attribution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['factor_experiments.id'], name=op.f('fk_research_outcome_attribution_experiment_id_factor_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_outcome_attribution_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_outcome_attribution')),
    sa.UniqueConstraint('experiment_id', 'reason_code', name='uq_research_outcome_reason')
    )
    op.create_index(op.f('ix_research_outcome_attribution_category'), 'research_outcome_attribution', ['category'], unique=False)
    op.create_index(op.f('ix_research_outcome_attribution_experiment_id'), 'research_outcome_attribution', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_research_outcome_attribution_passed'), 'research_outcome_attribution', ['passed'], unique=False)
    op.create_index(op.f('ix_research_outcome_attribution_reason_code'), 'research_outcome_attribution', ['reason_code'], unique=False)
    op.create_index(op.f('ix_research_outcome_attribution_simulation_eligible_time'), 'research_outcome_attribution', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_research_outcome_attribution_workspace_id'), 'research_outcome_attribution', ['workspace_id'], unique=False)
    op.create_table('signal_independence_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('factor_key', sa.String(length=160), nullable=False),
    sa.Column('baseline_version', sa.String(length=40), nullable=False),
    sa.Column('methodology_version', sa.String(length=40), nullable=False),
    sa.Column('predictive_strength', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('independent_contribution', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('redundancy_score', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('independent_information_score', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('formula', sa.JSON(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('as_of_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['factor_experiments.id'], name=op.f('fk_signal_independence_analyses_experiment_id_factor_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_signal_independence_analyses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_independence_analyses')),
    sa.UniqueConstraint('workspace_id', 'checksum', name='uq_signal_independence_checksum')
    )
    op.create_index(op.f('ix_signal_independence_analyses_as_of_time'), 'signal_independence_analyses', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_signal_independence_analyses_checksum'), 'signal_independence_analyses', ['checksum'], unique=False)
    op.create_index(op.f('ix_signal_independence_analyses_experiment_id'), 'signal_independence_analyses', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_signal_independence_analyses_factor_key'), 'signal_independence_analyses', ['factor_key'], unique=False)
    op.create_index(op.f('ix_signal_independence_analyses_independent_information_score'), 'signal_independence_analyses', ['independent_information_score'], unique=False)
    op.create_index(op.f('ix_signal_independence_analyses_simulation_eligible_time'), 'signal_independence_analyses', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_signal_independence_analyses_workspace_id'), 'signal_independence_analyses', ['workspace_id'], unique=False)
    op.create_table('research_contradictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('memory_a_id', sa.Uuid(), nullable=False),
    sa.Column('memory_b_id', sa.Uuid(), nullable=False),
    sa.Column('conflicting_dimension', sa.String(length=120), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('possible_explanations', sa.JSON(), nullable=False),
    sa.Column('discovered_at', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('simulation_eligible_time', packages.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_a_id'], ['research_memory_entries.id'], name=op.f('fk_research_contradictions_memory_a_id_research_memory_entries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['memory_b_id'], ['research_memory_entries.id'], name=op.f('fk_research_contradictions_memory_b_id_research_memory_entries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_research_contradictions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_contradictions')),
    sa.UniqueConstraint('memory_a_id', 'memory_b_id', name='uq_research_contradiction_pair')
    )
    op.create_index(op.f('ix_research_contradictions_conflicting_dimension'), 'research_contradictions', ['conflicting_dimension'], unique=False)
    op.create_index(op.f('ix_research_contradictions_discovered_at'), 'research_contradictions', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_research_contradictions_memory_a_id'), 'research_contradictions', ['memory_a_id'], unique=False)
    op.create_index(op.f('ix_research_contradictions_memory_b_id'), 'research_contradictions', ['memory_b_id'], unique=False)
    op.create_index(op.f('ix_research_contradictions_simulation_eligible_time'), 'research_contradictions', ['simulation_eligible_time'], unique=False)
    op.create_index(op.f('ix_research_contradictions_workspace_id'), 'research_contradictions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_contradictions_workspace_id'), table_name='research_contradictions')
    op.drop_index(op.f('ix_research_contradictions_simulation_eligible_time'), table_name='research_contradictions')
    op.drop_index(op.f('ix_research_contradictions_memory_b_id'), table_name='research_contradictions')
    op.drop_index(op.f('ix_research_contradictions_memory_a_id'), table_name='research_contradictions')
    op.drop_index(op.f('ix_research_contradictions_discovered_at'), table_name='research_contradictions')
    op.drop_index(op.f('ix_research_contradictions_conflicting_dimension'), table_name='research_contradictions')
    op.drop_table('research_contradictions')
    op.drop_index(op.f('ix_signal_independence_analyses_workspace_id'), table_name='signal_independence_analyses')
    op.drop_index(op.f('ix_signal_independence_analyses_simulation_eligible_time'), table_name='signal_independence_analyses')
    op.drop_index(op.f('ix_signal_independence_analyses_independent_information_score'), table_name='signal_independence_analyses')
    op.drop_index(op.f('ix_signal_independence_analyses_factor_key'), table_name='signal_independence_analyses')
    op.drop_index(op.f('ix_signal_independence_analyses_experiment_id'), table_name='signal_independence_analyses')
    op.drop_index(op.f('ix_signal_independence_analyses_checksum'), table_name='signal_independence_analyses')
    op.drop_index(op.f('ix_signal_independence_analyses_as_of_time'), table_name='signal_independence_analyses')
    op.drop_table('signal_independence_analyses')
    op.drop_index(op.f('ix_research_outcome_attribution_workspace_id'), table_name='research_outcome_attribution')
    op.drop_index(op.f('ix_research_outcome_attribution_simulation_eligible_time'), table_name='research_outcome_attribution')
    op.drop_index(op.f('ix_research_outcome_attribution_reason_code'), table_name='research_outcome_attribution')
    op.drop_index(op.f('ix_research_outcome_attribution_passed'), table_name='research_outcome_attribution')
    op.drop_index(op.f('ix_research_outcome_attribution_experiment_id'), table_name='research_outcome_attribution')
    op.drop_index(op.f('ix_research_outcome_attribution_category'), table_name='research_outcome_attribution')
    op.drop_table('research_outcome_attribution')
    op.drop_index(op.f('ix_research_memory_entries_workspace_id'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_subject_entity_id'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_status'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_simulation_eligible_time'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_outcome_key'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_mechanism_checksum'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_hypothesis_id'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_hypothesis_checksum'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_first_learned_at'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_feature_key'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_experiment_id'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_conclusion'), table_name='research_memory_entries')
    op.drop_index(op.f('ix_research_memory_entries_checksum'), table_name='research_memory_entries')
    op.drop_index('ix_memory_subject_status_asof', table_name='research_memory_entries')
    op.drop_index('ix_memory_mechanism_outcome', table_name='research_memory_entries')
    op.drop_table('research_memory_entries')
    op.drop_index(op.f('ix_hypothesis_memory_decisions_workspace_id'), table_name='hypothesis_memory_decisions')
    op.drop_index(op.f('ix_hypothesis_memory_decisions_hypothesis_id'), table_name='hypothesis_memory_decisions')
    op.drop_index(op.f('ix_hypothesis_memory_decisions_decision'), table_name='hypothesis_memory_decisions')
    op.drop_index(op.f('ix_hypothesis_memory_decisions_created_at'), table_name='hypothesis_memory_decisions')
    op.drop_index(op.f('ix_hypothesis_memory_decisions_classification'), table_name='hypothesis_memory_decisions')
    op.drop_table('hypothesis_memory_decisions')
    op.drop_index('ix_divergence_subject_asof', table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_workspace_id'), table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_subject_entity_id'), table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_status'), table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_simulation_eligible_time'), table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_research_candidate_id'), table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_feature_snapshot_id'), table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_disagreement_magnitude'), table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_definition_id'), table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_checksum'), table_name='divergence_events')
    op.drop_index(op.f('ix_divergence_events_as_of_time'), table_name='divergence_events')
    op.drop_table('divergence_events')
    op.drop_index(op.f('ix_research_regime_assignments_workspace_id'), table_name='research_regime_assignments')
    op.drop_index(op.f('ix_research_regime_assignments_subject_entity_id'), table_name='research_regime_assignments')
    op.drop_index(op.f('ix_research_regime_assignments_simulation_eligible_time'), table_name='research_regime_assignments')
    op.drop_index(op.f('ix_research_regime_assignments_definition_id'), table_name='research_regime_assignments')
    op.drop_index(op.f('ix_research_regime_assignments_as_of_time'), table_name='research_regime_assignments')
    op.drop_index(op.f('ix_research_regime_assignments_active'), table_name='research_regime_assignments')
    op.drop_table('research_regime_assignments')
    op.drop_index(op.f('ix_research_regime_definitions_workspace_id'), table_name='research_regime_definitions')
    op.drop_index(op.f('ix_research_regime_definitions_key'), table_name='research_regime_definitions')
    op.drop_table('research_regime_definitions')
    op.drop_index(op.f('ix_research_method_reliability_workspace_id'), table_name='research_method_reliability')
    op.drop_index(op.f('ix_research_method_reliability_method'), table_name='research_method_reliability')
    op.drop_index(op.f('ix_research_method_reliability_as_of_time'), table_name='research_method_reliability')
    op.drop_table('research_method_reliability')
    op.drop_index(op.f('ix_information_value_records_workspace_id'), table_name='information_value_records')
    op.drop_index(op.f('ix_information_value_records_resource_type'), table_name='information_value_records')
    op.drop_index(op.f('ix_information_value_records_resource_key'), table_name='information_value_records')
    op.drop_index(op.f('ix_information_value_records_as_of_time'), table_name='information_value_records')
    op.drop_table('information_value_records')
    op.drop_index(op.f('ix_factor_redundancy_results_workspace_id'), table_name='factor_redundancy_results')
    op.drop_index(op.f('ix_factor_redundancy_results_factor_b'), table_name='factor_redundancy_results')
    op.drop_index(op.f('ix_factor_redundancy_results_factor_a'), table_name='factor_redundancy_results')
    op.drop_index(op.f('ix_factor_redundancy_results_checksum'), table_name='factor_redundancy_results')
    op.drop_index(op.f('ix_factor_redundancy_results_as_of_time'), table_name='factor_redundancy_results')
    op.drop_table('factor_redundancy_results')
    op.drop_index(op.f('ix_factor_clusters_workspace_id'), table_name='factor_clusters')
    op.drop_index(op.f('ix_factor_clusters_information_family'), table_name='factor_clusters')
    op.drop_index(op.f('ix_factor_clusters_cluster_key'), table_name='factor_clusters')
    op.drop_index(op.f('ix_factor_clusters_as_of_time'), table_name='factor_clusters')
    op.drop_table('factor_clusters')
    op.drop_index(op.f('ix_divergence_definitions_workspace_id'), table_name='divergence_definitions')
    op.drop_index(op.f('ix_divergence_definitions_key'), table_name='divergence_definitions')
    op.drop_table('divergence_definitions')
    # ### end Alembic commands ###
