"""hypothesis factory and factor validation

Revision ID: ed23735efb90
Revises: 2f9e39afd435
Create Date: 2026-08-08 04:42:38.990942
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import packages.database.types


revision: str = "ed23735efb90"
down_revision: str | None = "2f9e39afd435"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_outcome_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("outcome_type", sa.String(length=48), nullable=False),
        sa.Column("horizon", sa.Integer(), nullable=False),
        sa.Column("benchmark", sa.String(length=120), nullable=True),
        sa.Column("calculation", sa.JSON(), nullable=False),
        sa.Column("temporal_truth_policy", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_outcome_definitions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_outcome_definitions")),
        sa.UniqueConstraint("workspace_id", "key", "version", name="uq_research_outcome_version"),
    )
    op.create_index(
        op.f("ix_research_outcome_definitions_key"),
        "research_outcome_definitions",
        ["key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_outcome_definitions_workspace_id"),
        "research_outcome_definitions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "research_hypotheses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("system_owner", sa.String(length=120), nullable=False),
        sa.Column("subject_entity_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("hypothesis_type", sa.String(length=48), nullable=False),
        sa.Column("economic_rationale", sa.Text(), nullable=False),
        sa.Column("machine_readable_mechanism", sa.JSON(), nullable=False),
        sa.Column("expected_direction", sa.String(length=24), nullable=False),
        sa.Column("expected_horizon", sa.String(length=64), nullable=False),
        sa.Column("required_evidence", sa.JSON(), nullable=False),
        sa.Column("required_graph_drivers", sa.JSON(), nullable=False),
        sa.Column("required_datasets", sa.JSON(), nullable=False),
        sa.Column("proposed_outcome", sa.JSON(), nullable=False),
        sa.Column("candidate_feature_specification", sa.JSON(), nullable=False),
        sa.Column("originating_method", sa.String(length=48), nullable=False),
        sa.Column("originating_model", sa.String(length=160), nullable=True),
        sa.Column("falsification_criteria", sa.JSON(), nullable=False),
        sa.Column("mechanism_confidence", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("novelty_estimate", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "simulation_eligible_time",
            packages.database.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','EVIDENCE_REQUIRED','READY_FOR_IMPLEMENTATION','IMPLEMENTED','TESTING','REJECTED','PROMISING','VALIDATED','RETIRED')",
            name=op.f("ck_research_hypotheses_hypothesis_status_valid"),
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_research_hypotheses_hypothesis_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["subject_entity_id"],
            ["economic_entities.id"],
            name=op.f("fk_research_hypotheses_subject_entity_id_economic_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_research_hypotheses_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_hypotheses")),
        sa.UniqueConstraint(
            "workspace_id", "subject_entity_id", "title", "version", name="uq_hypothesis_version"
        ),
    )
    op.create_index(
        "ix_hypothesis_subject_status",
        "research_hypotheses",
        ["workspace_id", "subject_entity_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_hypotheses_checksum"), "research_hypotheses", ["checksum"], unique=False
    )
    op.create_index(
        op.f("ix_research_hypotheses_created_at"),
        "research_hypotheses",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_hypotheses_hypothesis_type"),
        "research_hypotheses",
        ["hypothesis_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_hypotheses_originating_method"),
        "research_hypotheses",
        ["originating_method"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_hypotheses_simulation_eligible_time"),
        "research_hypotheses",
        ["simulation_eligible_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_hypotheses_status"), "research_hypotheses", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_research_hypotheses_subject_entity_id"),
        "research_hypotheses",
        ["subject_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_hypotheses_workspace_id"),
        "research_hypotheses",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "candidate_feature_specs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("hypothesis_id", sa.Uuid(), nullable=False),
        sa.Column("feature_key", sa.String(length=160), nullable=False),
        sa.Column("required_datasets", sa.JSON(), nullable=False),
        sa.Column("required_graph_paths", sa.JSON(), nullable=False),
        sa.Column("transformations", sa.JSON(), nullable=False),
        sa.Column("aggregation", sa.JSON(), nullable=False),
        sa.Column("lookback", sa.Integer(), nullable=False),
        sa.Column("lag", sa.Integer(), nullable=False),
        sa.Column("weighting", sa.JSON(), nullable=False),
        sa.Column("missing_data_policy", sa.String(length=48), nullable=False),
        sa.Column("normalization", sa.String(length=48), nullable=False),
        sa.Column("expected_direction", sa.String(length=24), nullable=False),
        sa.Column("required_output", sa.String(length=48), nullable=False),
        sa.Column("temporal_policy", sa.JSON(), nullable=False),
        sa.Column("implementation_version", sa.Integer(), nullable=False),
        sa.Column("generator", sa.String(length=120), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "implementation_version > 0",
            name=op.f("ck_candidate_feature_specs_candidate_feature_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["research_hypotheses.id"],
            name=op.f("fk_candidate_feature_specs_hypothesis_id_research_hypotheses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_candidate_feature_specs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_feature_specs")),
        sa.UniqueConstraint("workspace_id", "checksum", name="uq_candidate_feature_checksum"),
    )
    op.create_index(
        op.f("ix_candidate_feature_specs_checksum"),
        "candidate_feature_specs",
        ["checksum"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_feature_specs_feature_key"),
        "candidate_feature_specs",
        ["feature_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_feature_specs_hypothesis_id"),
        "candidate_feature_specs",
        ["hypothesis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_feature_specs_workspace_id"),
        "candidate_feature_specs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "hypothesis_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hypothesis_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_record_id", sa.Uuid(), nullable=True),
        sa.Column("stance", sa.String(length=24), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_reference", sa.JSON(), nullable=False),
        sa.Column(
            "simulation_eligible_time",
            packages.database.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "stance IN ('supporting','contradicting','neutral')",
            name=op.f("ck_hypothesis_evidence_hypothesis_evidence_stance"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_hypothesis_evidence_evidence_record_id_evidence_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["research_hypotheses.id"],
            name=op.f("fk_hypothesis_evidence_hypothesis_id_research_hypotheses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hypothesis_evidence")),
    )
    op.create_index(
        op.f("ix_hypothesis_evidence_evidence_record_id"),
        "hypothesis_evidence",
        ["evidence_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_evidence_hypothesis_id"),
        "hypothesis_evidence",
        ["hypothesis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_evidence_simulation_eligible_time"),
        "hypothesis_evidence",
        ["simulation_eligible_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_evidence_stance"), "hypothesis_evidence", ["stance"], unique=False
    )
    op.create_table(
        "hypothesis_mechanisms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hypothesis_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_driver", sa.String(length=200), nullable=False),
        sa.Column("affected_entity_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_path", sa.JSON(), nullable=False),
        sa.Column("expected_direction", sa.String(length=24), nullable=False),
        sa.Column("lag_assumptions", sa.JSON(), nullable=False),
        sa.Column("intermediate_mechanism", sa.Text(), nullable=False),
        sa.Column("target_outcome", sa.String(length=160), nullable=False),
        sa.Column("mechanism_confidence", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["affected_entity_id"],
            ["economic_entities.id"],
            name=op.f("fk_hypothesis_mechanisms_affected_entity_id_economic_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["research_hypotheses.id"],
            name=op.f("fk_hypothesis_mechanisms_hypothesis_id_research_hypotheses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hypothesis_mechanisms")),
        sa.UniqueConstraint("hypothesis_id", "version", name="uq_hypothesis_mechanism_version"),
    )
    op.create_index(
        op.f("ix_hypothesis_mechanisms_affected_entity_id"),
        "hypothesis_mechanisms",
        ["affected_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_mechanisms_hypothesis_id"),
        "hypothesis_mechanisms",
        ["hypothesis_id"],
        unique=False,
    )
    op.create_table(
        "factor_experiments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("hypothesis_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_feature_spec_id", sa.Uuid(), nullable=False),
        sa.Column("universe_version_id", sa.Uuid(), nullable=False),
        sa.Column("feature_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("outcome_definition_id", sa.Uuid(), nullable=False),
        sa.Column("graph_state", sa.JSON(), nullable=False),
        sa.Column(
            "period_start", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("period_end", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("validation_protocol", sa.JSON(), nullable=False),
        sa.Column("cost_assumptions", sa.JSON(), nullable=False),
        sa.Column("application_sha", sa.String(length=64), nullable=False),
        sa.Column("dependency_versions", sa.JSON(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("conclusion", sa.String(length=40), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "completed_at", packages.database.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','SCHEDULED','RUNNING','COMPLETED','FAILED','REJECTED')",
            name=op.f("ck_factor_experiments_factor_experiment_status"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_feature_spec_id"],
            ["candidate_feature_specs.id"],
            name=op.f("fk_factor_experiments_candidate_feature_spec_id_candidate_feature_specs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["feature_snapshots.id"],
            name=op.f("fk_factor_experiments_feature_snapshot_id_feature_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["research_hypotheses.id"],
            name=op.f("fk_factor_experiments_hypothesis_id_research_hypotheses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["outcome_definition_id"],
            ["research_outcome_definitions.id"],
            name=op.f("fk_factor_experiments_outcome_definition_id_research_outcome_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["universe_version_id"],
            ["research_universe_versions.id"],
            name=op.f("fk_factor_experiments_universe_version_id_research_universe_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_factor_experiments_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factor_experiments")),
        sa.UniqueConstraint("workspace_id", "checksum", name="uq_factor_experiment_checksum"),
    )
    op.create_index(
        "ix_factor_experiment_hypothesis_status",
        "factor_experiments",
        ["hypothesis_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_experiments_candidate_feature_spec_id"),
        "factor_experiments",
        ["candidate_feature_spec_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_experiments_checksum"), "factor_experiments", ["checksum"], unique=False
    )
    op.create_index(
        op.f("ix_factor_experiments_conclusion"), "factor_experiments", ["conclusion"], unique=False
    )
    op.create_index(
        op.f("ix_factor_experiments_created_at"), "factor_experiments", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_factor_experiments_feature_snapshot_id"),
        "factor_experiments",
        ["feature_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_experiments_hypothesis_id"),
        "factor_experiments",
        ["hypothesis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_experiments_outcome_definition_id"),
        "factor_experiments",
        ["outcome_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_experiments_status"), "factor_experiments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_factor_experiments_universe_version_id"),
        "factor_experiments",
        ["universe_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_experiments_workspace_id"),
        "factor_experiments",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "ablation_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("component_key", sa.String(length=120), nullable=False),
        sa.Column("included_components", sa.JSON(), nullable=False),
        sa.Column("statistics", sa.JSON(), nullable=False),
        sa.Column("contribution", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["factor_experiments.id"],
            name=op.f("fk_ablation_results_experiment_id_factor_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ablation_results")),
        sa.UniqueConstraint("experiment_id", "component_key", name="uq_ablation_component"),
    )
    op.create_index(
        op.f("ix_ablation_results_experiment_id"),
        "ablation_results",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "experiment_manifests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("hypothesis_version", sa.Integer(), nullable=False),
        sa.Column("feature_spec", sa.JSON(), nullable=False),
        sa.Column("feature_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("universe_version_id", sa.Uuid(), nullable=False),
        sa.Column("graph_reference_state", sa.JSON(), nullable=False),
        sa.Column("source_manifests", sa.JSON(), nullable=False),
        sa.Column("software_sha", sa.String(length=64), nullable=False),
        sa.Column("alembic_revision", sa.String(length=40), nullable=False),
        sa.Column("dependency_versions", sa.JSON(), nullable=False),
        sa.Column("model_config", sa.JSON(), nullable=False),
        sa.Column("validation_protocol", sa.JSON(), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("time_boundaries", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["factor_experiments.id"],
            name=op.f("fk_experiment_manifests_experiment_id_factor_experiments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["feature_snapshots.id"],
            name=op.f("fk_experiment_manifests_feature_snapshot_id_feature_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["universe_version_id"],
            ["research_universe_versions.id"],
            name=op.f("fk_experiment_manifests_universe_version_id_research_universe_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_manifests")),
        sa.UniqueConstraint("experiment_id", name="uq_experiment_manifest_experiment"),
    )
    op.create_index(
        op.f("ix_experiment_manifests_checksum"), "experiment_manifests", ["checksum"], unique=True
    )
    op.create_index(
        op.f("ix_experiment_manifests_experiment_id"),
        "experiment_manifests",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_manifests_feature_snapshot_id"),
        "experiment_manifests",
        ["feature_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_manifests_universe_version_id"),
        "experiment_manifests",
        ["universe_version_id"],
        unique=False,
    )
    op.create_table(
        "external_research_engine_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=True),
        sa.Column("engine", sa.String(length=24), nullable=False),
        sa.Column("engine_version", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("input_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("artifacts", sa.JSON(), nullable=False),
        sa.Column("output_checksum", sa.String(length=64), nullable=True),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "engine IN ('qlib','rd-agent')",
            name=op.f("ck_external_research_engine_runs_external_research_engine"),
        ),
        sa.CheckConstraint(
            "status IN ('unavailable','disabled','queued','running','completed','failed')",
            name=op.f("ck_external_research_engine_runs_engine_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["factor_experiments.id"],
            name=op.f("fk_external_research_engine_runs_experiment_id_factor_experiments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["input_snapshot_id"],
            ["feature_snapshots.id"],
            name=op.f("fk_external_research_engine_runs_input_snapshot_id_feature_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_external_research_engine_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_research_engine_runs")),
    )
    op.create_index(
        op.f("ix_external_research_engine_runs_created_at"),
        "external_research_engine_runs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_research_engine_runs_engine"),
        "external_research_engine_runs",
        ["engine"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_research_engine_runs_experiment_id"),
        "external_research_engine_runs",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_research_engine_runs_input_snapshot_id"),
        "external_research_engine_runs",
        ["input_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_research_engine_runs_status"),
        "external_research_engine_runs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_research_engine_runs_workspace_id"),
        "external_research_engine_runs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "factor_experiment_folds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("fold_number", sa.Integer(), nullable=False),
        sa.Column(
            "train_start", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("train_end", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "validation_start", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "validation_end", packages.database.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("test_start", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("test_end", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("purge_observations", sa.Integer(), nullable=False),
        sa.Column("embargo_observations", sa.Integer(), nullable=False),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("coverage", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("factor_statistics", sa.JSON(), nullable=False),
        sa.Column("model_statistics", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("failures", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "fold_number >= 0",
            name=op.f("ck_factor_experiment_folds_factor_fold_number_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["factor_experiments.id"],
            name=op.f("fk_factor_experiment_folds_experiment_id_factor_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factor_experiment_folds")),
        sa.UniqueConstraint("experiment_id", "fold_number", name="uq_factor_experiment_fold"),
    )
    op.create_index(
        op.f("ix_factor_experiment_folds_experiment_id"),
        "factor_experiment_folds",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        "ix_factor_fold_experiment_ranges",
        "factor_experiment_folds",
        ["experiment_id", "test_start", "test_end"],
        unique=False,
    )
    op.create_table(
        "multiple_testing_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("hypothesis_family", sa.String(length=160), nullable=False),
        sa.Column("number_of_hypotheses", sa.Integer(), nullable=False),
        sa.Column("raw_p_value", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("adjusted_p_value", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("correction_method", sa.String(length=32), nullable=False),
        sa.Column("rejected_null", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "correction_method IN ('bonferroni','holm','benjamini-hochberg')",
            name=op.f("ck_multiple_testing_results_multiple_testing_method"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["factor_experiments.id"],
            name=op.f("fk_multiple_testing_results_experiment_id_factor_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_multiple_testing_results")),
    )
    op.create_index(
        op.f("ix_multiple_testing_results_experiment_id"),
        "multiple_testing_results",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_multiple_testing_results_hypothesis_family"),
        "multiple_testing_results",
        ["hypothesis_family"],
        unique=False,
    )
    op.create_table(
        "negative_control_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("control_type", sa.String(length=40), nullable=False),
        sa.Column("statistics", sa.JSON(), nullable=False),
        sa.Column("persistent_power_detected", sa.Boolean(), nullable=False),
        sa.Column("methodology_valid", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "control_type IN ('shuffled','deterministic_noise','unrelated_sector','temporal_corruption')",
            name=op.f("ck_negative_control_results_negative_control_type"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["factor_experiments.id"],
            name=op.f("fk_negative_control_results_experiment_id_factor_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_negative_control_results")),
    )
    op.create_index(
        op.f("ix_negative_control_results_control_type"),
        "negative_control_results",
        ["control_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_negative_control_results_experiment_id"),
        "negative_control_results",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "research_promotion_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hypothesis_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=True),
        sa.Column("from_stage", sa.String(length=40), nullable=True),
        sa.Column("to_stage", sa.String(length=40), nullable=False),
        sa.Column("gate_version", sa.String(length=40), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", packages.database.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "to_stage IN ('DRAFT','EVIDENCE_CHECKED','IMPLEMENTED','LEAKAGE_CHECKED','BACKTESTED','WALK_FORWARD_PASSED','ROBUSTNESS_PASSED','OOS_PASSED','PAPER_ELIGIBLE','REJECTED')",
            name=op.f("ck_research_promotion_events_research_promotion_stage"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["factor_experiments.id"],
            name=op.f("fk_research_promotion_events_experiment_id_factor_experiments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["research_hypotheses.id"],
            name=op.f("fk_research_promotion_events_hypothesis_id_research_hypotheses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_promotion_events")),
    )
    op.create_index(
        op.f("ix_research_promotion_events_created_at"),
        "research_promotion_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_promotion_events_experiment_id"),
        "research_promotion_events",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_promotion_events_hypothesis_id"),
        "research_promotion_events",
        ["hypothesis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_promotion_events_to_stage"),
        "research_promotion_events",
        ["to_stage"],
        unique=False,
    )
    op.create_table(
        "robustness_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("variant_type", sa.String(length=64), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("statistics", sa.JSON(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("variant_checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["factor_experiments.id"],
            name=op.f("fk_robustness_results_experiment_id_factor_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_robustness_results")),
        sa.UniqueConstraint("experiment_id", "variant_checksum", name="uq_robustness_variant"),
    )
    op.create_index(
        op.f("ix_robustness_results_experiment_id"),
        "robustness_results",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_robustness_results_passed"), "robustness_results", ["passed"], unique=False
    )
    op.create_index(
        op.f("ix_robustness_results_variant_type"),
        "robustness_results",
        ["variant_type"],
        unique=False,
    )
    op.create_table(
        "factor_statistics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("fold_id", sa.Uuid(), nullable=True),
        sa.Column("metric_key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("segment", sa.String(length=120), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["factor_experiments.id"],
            name=op.f("fk_factor_statistics_experiment_id_factor_experiments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fold_id"],
            ["factor_experiment_folds.id"],
            name=op.f("fk_factor_statistics_fold_id_factor_experiment_folds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factor_statistics")),
        sa.UniqueConstraint(
            "experiment_id", "fold_id", "metric_key", "segment", name="uq_factor_statistic_key"
        ),
    )
    op.create_index(
        op.f("ix_factor_statistics_experiment_id"),
        "factor_statistics",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_statistics_fold_id"), "factor_statistics", ["fold_id"], unique=False
    )
    op.create_index(
        op.f("ix_factor_statistics_metric_key"), "factor_statistics", ["metric_key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_factor_statistics_metric_key"), table_name="factor_statistics")
    op.drop_index(op.f("ix_factor_statistics_fold_id"), table_name="factor_statistics")
    op.drop_index(op.f("ix_factor_statistics_experiment_id"), table_name="factor_statistics")
    op.drop_table("factor_statistics")
    op.drop_index(op.f("ix_robustness_results_variant_type"), table_name="robustness_results")
    op.drop_index(op.f("ix_robustness_results_passed"), table_name="robustness_results")
    op.drop_index(op.f("ix_robustness_results_experiment_id"), table_name="robustness_results")
    op.drop_table("robustness_results")
    op.drop_index(
        op.f("ix_research_promotion_events_to_stage"), table_name="research_promotion_events"
    )
    op.drop_index(
        op.f("ix_research_promotion_events_hypothesis_id"), table_name="research_promotion_events"
    )
    op.drop_index(
        op.f("ix_research_promotion_events_experiment_id"), table_name="research_promotion_events"
    )
    op.drop_index(
        op.f("ix_research_promotion_events_created_at"), table_name="research_promotion_events"
    )
    op.drop_table("research_promotion_events")
    op.drop_index(
        op.f("ix_negative_control_results_experiment_id"), table_name="negative_control_results"
    )
    op.drop_index(
        op.f("ix_negative_control_results_control_type"), table_name="negative_control_results"
    )
    op.drop_table("negative_control_results")
    op.drop_index(
        op.f("ix_multiple_testing_results_hypothesis_family"), table_name="multiple_testing_results"
    )
    op.drop_index(
        op.f("ix_multiple_testing_results_experiment_id"), table_name="multiple_testing_results"
    )
    op.drop_table("multiple_testing_results")
    op.drop_index("ix_factor_fold_experiment_ranges", table_name="factor_experiment_folds")
    op.drop_index(
        op.f("ix_factor_experiment_folds_experiment_id"), table_name="factor_experiment_folds"
    )
    op.drop_table("factor_experiment_folds")
    op.drop_index(
        op.f("ix_external_research_engine_runs_workspace_id"),
        table_name="external_research_engine_runs",
    )
    op.drop_index(
        op.f("ix_external_research_engine_runs_status"), table_name="external_research_engine_runs"
    )
    op.drop_index(
        op.f("ix_external_research_engine_runs_input_snapshot_id"),
        table_name="external_research_engine_runs",
    )
    op.drop_index(
        op.f("ix_external_research_engine_runs_experiment_id"),
        table_name="external_research_engine_runs",
    )
    op.drop_index(
        op.f("ix_external_research_engine_runs_engine"), table_name="external_research_engine_runs"
    )
    op.drop_index(
        op.f("ix_external_research_engine_runs_created_at"),
        table_name="external_research_engine_runs",
    )
    op.drop_table("external_research_engine_runs")
    op.drop_index(
        op.f("ix_experiment_manifests_universe_version_id"), table_name="experiment_manifests"
    )
    op.drop_index(
        op.f("ix_experiment_manifests_feature_snapshot_id"), table_name="experiment_manifests"
    )
    op.drop_index(op.f("ix_experiment_manifests_experiment_id"), table_name="experiment_manifests")
    op.drop_index(op.f("ix_experiment_manifests_checksum"), table_name="experiment_manifests")
    op.drop_table("experiment_manifests")
    op.drop_index(op.f("ix_ablation_results_experiment_id"), table_name="ablation_results")
    op.drop_table("ablation_results")
    op.drop_index(op.f("ix_factor_experiments_workspace_id"), table_name="factor_experiments")
    op.drop_index(
        op.f("ix_factor_experiments_universe_version_id"), table_name="factor_experiments"
    )
    op.drop_index(op.f("ix_factor_experiments_status"), table_name="factor_experiments")
    op.drop_index(
        op.f("ix_factor_experiments_outcome_definition_id"), table_name="factor_experiments"
    )
    op.drop_index(op.f("ix_factor_experiments_hypothesis_id"), table_name="factor_experiments")
    op.drop_index(
        op.f("ix_factor_experiments_feature_snapshot_id"), table_name="factor_experiments"
    )
    op.drop_index(op.f("ix_factor_experiments_created_at"), table_name="factor_experiments")
    op.drop_index(op.f("ix_factor_experiments_conclusion"), table_name="factor_experiments")
    op.drop_index(op.f("ix_factor_experiments_checksum"), table_name="factor_experiments")
    op.drop_index(
        op.f("ix_factor_experiments_candidate_feature_spec_id"), table_name="factor_experiments"
    )
    op.drop_index("ix_factor_experiment_hypothesis_status", table_name="factor_experiments")
    op.drop_table("factor_experiments")
    op.drop_index(
        op.f("ix_hypothesis_mechanisms_hypothesis_id"), table_name="hypothesis_mechanisms"
    )
    op.drop_index(
        op.f("ix_hypothesis_mechanisms_affected_entity_id"), table_name="hypothesis_mechanisms"
    )
    op.drop_table("hypothesis_mechanisms")
    op.drop_index(op.f("ix_hypothesis_evidence_stance"), table_name="hypothesis_evidence")
    op.drop_index(
        op.f("ix_hypothesis_evidence_simulation_eligible_time"), table_name="hypothesis_evidence"
    )
    op.drop_index(op.f("ix_hypothesis_evidence_hypothesis_id"), table_name="hypothesis_evidence")
    op.drop_index(
        op.f("ix_hypothesis_evidence_evidence_record_id"), table_name="hypothesis_evidence"
    )
    op.drop_table("hypothesis_evidence")
    op.drop_index(
        op.f("ix_candidate_feature_specs_workspace_id"), table_name="candidate_feature_specs"
    )
    op.drop_index(
        op.f("ix_candidate_feature_specs_hypothesis_id"), table_name="candidate_feature_specs"
    )
    op.drop_index(
        op.f("ix_candidate_feature_specs_feature_key"), table_name="candidate_feature_specs"
    )
    op.drop_index(op.f("ix_candidate_feature_specs_checksum"), table_name="candidate_feature_specs")
    op.drop_table("candidate_feature_specs")
    op.drop_index(op.f("ix_research_hypotheses_workspace_id"), table_name="research_hypotheses")
    op.drop_index(
        op.f("ix_research_hypotheses_subject_entity_id"), table_name="research_hypotheses"
    )
    op.drop_index(op.f("ix_research_hypotheses_status"), table_name="research_hypotheses")
    op.drop_index(
        op.f("ix_research_hypotheses_simulation_eligible_time"), table_name="research_hypotheses"
    )
    op.drop_index(
        op.f("ix_research_hypotheses_originating_method"), table_name="research_hypotheses"
    )
    op.drop_index(op.f("ix_research_hypotheses_hypothesis_type"), table_name="research_hypotheses")
    op.drop_index(op.f("ix_research_hypotheses_created_at"), table_name="research_hypotheses")
    op.drop_index(op.f("ix_research_hypotheses_checksum"), table_name="research_hypotheses")
    op.drop_index("ix_hypothesis_subject_status", table_name="research_hypotheses")
    op.drop_table("research_hypotheses")
    op.drop_index(
        op.f("ix_research_outcome_definitions_workspace_id"),
        table_name="research_outcome_definitions",
    )
    op.drop_index(
        op.f("ix_research_outcome_definitions_key"), table_name="research_outcome_definitions"
    )
    op.drop_table("research_outcome_definitions")
    # ### end Alembic commands ###
