import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { api } from "../api";
import { ErrorState, LoadingState } from "../components/States";

export function PaperPortfolioDetail() {
  const { id = "" } = useParams(); const client = useQueryClient();
  const portfolio = useQuery({ queryKey: ["paper-portfolio", id], queryFn: () => api.paperPortfolio(id) });
  const orders = useQuery({ queryKey: ["paper-orders", id], queryFn: () => api.paperOrders(id) });
  const fills = useQuery({ queryKey: ["paper-fills", id], queryFn: () => api.paperFills(id) });
  const performance = useQuery({ queryKey: ["paper-performance", id], queryFn: () => api.paperPerformance(id) });
  const riskRules = useQuery({ queryKey: ["risk-rules", id], queryFn: () => api.riskRules(id) });
  const toggle = useMutation({ mutationFn: (status: string) => status === "active" ? api.pausePortfolio(id) : api.resumePortfolio(id), onSuccess: () => client.invalidateQueries({ queryKey: ["paper-portfolio", id] }) });
  const cancel = useMutation({ mutationFn: (orderId: string) => api.cancelOrder(id, orderId), onSuccess: () => { client.invalidateQueries({ queryKey: ["paper-orders", id] }); client.invalidateQueries({ queryKey: ["paper-portfolio", id] }); } });
  if (portfolio.isLoading || orders.isLoading || fills.isLoading || performance.isLoading || riskRules.isLoading) return <LoadingState label="Loading paper portfolio" />;
  const error = portfolio.error || orders.error || fills.error || performance.error || riskRules.error; if (error) return <ErrorState error={error} />;
  const data = portfolio.data!;
  return <section><Link className="back-link" to="/paper-portfolios">← Paper portfolios</Link><div className="page-heading"><div><p className="eyebrow">HYPOTHETICAL PORTFOLIO</p><h1>{data.name}</h1><p>{data.warning}</p></div><div className="actions"><button onClick={() => toggle.mutate(data.status)}>{data.status === "active" ? "Pause" : "Resume"}</button><Link className="button" to={`/paper-portfolios/${id}/risk`}>Risk settings</Link><Link className="button primary" to={`/paper-portfolios/${id}/order`}>Simulate order</Link></div></div>
    <div className="metric-grid"><article className="metric"><span>Portfolio value</span><strong>${Number(data.portfolio_value).toLocaleString(undefined, { maximumFractionDigits: 2 })}</strong></article><article className="metric"><span>Available cash</span><strong>${Number(data.cash_balance).toLocaleString(undefined, { maximumFractionDigits: 2 })}</strong></article><article className="metric"><span>Realized P&amp;L</span><strong>${Number(data.realized_pnl).toFixed(2)}</strong></article><article className="metric"><span>Unrealized P&amp;L</span><strong>${Number(data.unrealized_pnl).toFixed(2)}</strong></article></div>
    <div className="panel-grid"><article className="panel"><div className="panel-title"><div><p className="eyebrow">PORTFOLIO VALUE</p><h2>Snapshot history</h2></div><span className="tag">{performance.data!.points.length} points</span></div><div className="value-bars" role="img" aria-label="Portfolio value chart">{performance.data!.points.map((point, index) => { const value = Number(point.equity); const base = Number(performance.data!.starting_cash); return <i key={index} style={{ height: `${Math.max(8, Math.min(100, value / base * 70))}%` }} title={`$${value.toFixed(2)}`} />; })}</div></article><article className="panel"><div className="panel-title"><div><p className="eyebrow">RISK STATUS</p><h2>{riskRules.data!.filter(rule => rule.is_enabled).length} controls enabled</h2></div><span className="health"><i />{data.status}</span></div><dl className="detail-list"><div><dt>Total exposure</dt><dd>{(Number(data.exposure) * 100).toFixed(1)}%</dd></div><div><dt>Open orders</dt><dd>{data.open_order_count}</dd></div><div><dt>Enabled limits</dt><dd>{riskRules.data!.filter(rule => rule.is_enabled).length} / {riskRules.data!.length}</dd></div></dl></article></div>
    <h2 className="section-title">Positions</h2><div className="table-card"><table><thead><tr><th>Asset</th><th className="number">Quantity</th><th className="number">Average cost</th><th className="number">Mark</th><th className="number">Market value</th><th className="number">Unrealized</th></tr></thead><tbody>{data.positions.length ? data.positions.map(position => <tr key={position.id}><td><Link className="symbol" to={`/assets/${position.symbol}`}>{position.symbol}<small>{position.name}</small></Link></td><td className="number">{Number(position.quantity).toFixed(4)}</td><td className="number">${Number(position.average_cost).toFixed(2)}</td><td className="number">${Number(position.mark_price).toFixed(2)}</td><td className="number">${Number(position.market_value).toFixed(2)}</td><td className="number">${Number(position.unrealized_pnl).toFixed(2)}</td></tr>) : <tr><td colSpan={6} className="muted">No open positions.</td></tr>}</tbody></table></div>
    <h2 className="section-title">Orders</h2><div className="table-card"><table><thead><tr><th>Submitted</th><th>Asset</th><th>Order</th><th className="number">Quantity</th><th>Status</th><th>Risk result</th><th /></tr></thead><tbody>{orders.data!.map(order => <tr key={order.id}><td>{new Date(order.submitted_at).toLocaleString()}</td><td>{order.symbol}</td><td>{order.side} · {order.order_type.replaceAll("_", " ")}</td><td className="number">{order.quantity}</td><td><span className="tag">{order.status}</span></td><td>{order.rejection_reason ?? "Passed"}</td><td>{["pending", "triggered"].includes(order.status) && <button onClick={() => cancel.mutate(order.id)}>Cancel</button>}</td></tr>)}</tbody></table></div>
    <h2 className="section-title">Fills</h2><div className="table-card"><table><thead><tr><th>Filled</th><th>Asset</th><th>Side</th><th className="number">Quantity</th><th className="number">Price</th><th className="number">Fee</th><th>Source bar</th></tr></thead><tbody>{fills.data!.map(fill => <tr key={fill.id}><td>{new Date(fill.filled_at).toLocaleString()}</td><td>{fill.symbol}</td><td>{fill.side}</td><td className="number">{fill.quantity}</td><td className="number">${Number(fill.price).toFixed(2)}</td><td className="number">${Number(fill.fees).toFixed(2)}</td><td><code>{fill.source_price_bar_id.slice(0, 8)}</code></td></tr>)}</tbody></table></div>
  </section>;
}
